### ISSUE TITLE
Modal and requestAnimationFrame

### ISSUE THREAD

**Issue by raptoria** [Semantic-Org/Semantic-UI-React#1010]
I noticed that the Modal component relies on requestAnimationFrame. Might this potentially cause problems in the future when React moves to React Fiber?

Also, I am having trouble writing a test case. My ModalPopup component contains the exact same code as the demo. I tried to model my test case off of Modal.test.js under the /test/ directory, where .newWaveButton refers to the className of my Button inside of the Modal trigger attribute. 

      const nativeEvent = { nativeEvent: { stopImmediatePropagation: _.noop } }
      ....
       it('Clicking Modal button should set its state to Open', () => {
           const wrapper = mount(<ModalPopup />);
           wrapper.find('.newWaveButton').simulate('click', nativeEvent);
           expect(wrapper.state().modalOpen).to.equal(true);
        });

I must be missing out on some magic, because I can't get past the requestAnimationFrame error:

         1) ModalPopup Clicking Modal button should set its state to Open:
     ReferenceError: requestAnimationFrame is not defined
      at Modal._this.setPosition (node_modules/semantic-ui-react/dist/commonjs/modules/Modal/Modal.js:178:34)
      at Modal._this.handlePortalMount (node_modules/semantic-ui-react/dist/commonjs/modules/Modal/Modal.js:129:13)
      at Portal._this.mountPortal (node_modules/semantic-ui-react/dist/commonjs/addons/Portal/Portal.js:242:20)
      at Portal.renderPortal (node_modules/semantic-ui-react/dist/commonjs/addons/Portal/Portal.js:319:12)
      at Portal.componentDidUpdate (node_modules/semantic-ui-react/dist/commonjs/addons/Portal/Portal.js:279:12)
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)

any ideas?? :D thanks!

**Comment by levithomason** [comment]
We'll handle React Fiber updates if/when they get here.  Looks like that could be a while.  My guess is that since a fiber can be thought of as a "virtual frame" that we'll be rewriting some things.  I'm really looking forward to[ siblings](https://github.com/acdlite/react-fiber-architecture#child-and-sibling) which will cause a number of rewrites for us, but I digress!

The browser you are using to test with (jsdom? PhantomJS?) doesn't seem to have `requestAnimationFrame` defined.  We test with Karma's `phantomjs-launcher` which includes `phantomjs-prebuilt`.

You'll need some kind of shim or polyfill for it or change your test browser to something that supports `requestAnimationFrame`.  There is also the slim possibility that your test browser does support `requestAnimationFrame` and it is just `undefined` in that test's context somehow (i.e. something has `delete`d it from `window` or set it to `undefined`).

**Comment by raptoria** [comment]
Thanks!
