### ISSUE TITLE
how to render Header when defined as a const like your docs

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#1017]
I'd like to replace my semantic-ui header with semantic-ui-react, but when I define it as a const as you do in the semantic-ui-react header docs, how do I get it to render?

```
const createAccountHeader = () => (
    <div>
      <Header sub>Price</Header>
      <span>$10.99</span>
    </div>
  )


  if (warningUserCreateAccountSocial) {
    return (
      <div className="ui centered grid">
        <div className={createAccountGridClassnames}>
          <CreateNewAccountFormComponent onSubmit={createAccountFunc} retrySignInFunc={retrySignInFunc}/>
        </div>
      </div>
    );
  } else {
    if (warningUserCreateAccount) {
      return (
        <div className="ui centered grid">
          <div className={createAccountGridClassnames}>
            <div className="ui center aligned padded inverted segment">
              <p>1</p>createAccountHeader
              <p>2</p>{createAccountHeader}
              <createAccountHeader/>
              export default createAccountHeader
{/*nothing works*/}
              <div className="ui large header">You are about to create a new account</div>
            </div>

...
```

**Comment by levithomason** [comment]
### Elements

React elements are renderable, `<div />`.  You can assign them to variables and place the variable in some other JSX:

```jsx
const header = <Header>Hi</Header>
const otherJSX = <div>{header}</div>
```

### Render Functions
In your case, you have not defined just a const, but an anonymous function assigned to a const (`const foo = () => ...`) that returns JSX.  So, you need to call the function to get the JSX:

```jsx
const header = () => <Header>Hi</Header>
const otherJSX = <div>{header()}</div>
```

### Casing
Since components can be plain functions, you might think you can render `createAccountHeader` like so:
```jsx
<createAccountHeader />
```

But, [lower case components are not allowed](https://gist.github.com/sebmarkbage/f1f4ba40816e7d7848ad).  You'd need to capitalize it to indicate it is a component.

### Export / Import
The `export default`, if not in an invalid location and improperly lowercase, would also correct for this case since a function is a component.  So, you could import your `CreateAccountHeader` and render it:

```jsx
import CreateAccountHeader from './CreateAccountHeader'

// in some render method:
<CreateAccountHeader />
```

**Comment by Maxhodges** [comment]
I see. thank you sir! I was just trying several ways, but i see I had it right with `  <createAccountHeader/>` except for the camelcase.

Cheers!
