### ISSUE TITLE
<Sidebar /> with 'onClose', 'onOpen', 'onMount' and 'onUnmount'

### ISSUE THREAD

**Issue by samin** [Semantic-Org/Semantic-UI-React#1034]
I believe the `<Sidebar>` component should be very similar to the `<Modal>` component in terms of behaviour. If a Modal could have a sideways animation it would be more interesting than the proposed Pusher, Pushable idea. Props like `onClose`, `onOpen`, `onMount` and `onUnmount` feel necessary.

**Comment by levithomason** [comment]
This should be opened on Semantic-UI as it is CSS/Markup related.

**Comment by samin** [comment]
I don't think `onClose`, `onOpen`, `onMount` and `onUnmount` are CSS/Markup related.

**Comment by levithomason** [comment]
>If a Modal could have a sideways animation it would be more interesting than the proposed Pusher, Pushable idea.

The animations are provided by the CSS in Semantic-UI, no animations can be added from this library (until #813 lands).  The `Pusher` and `Pushable` are HTML requirements trickled down from Semantic-UI CSS.

Apologies if I've misunderstood.  Please provide the information requested in the template so we can understand the issue and help find a solution.

**Comment by samin** [comment]
Sorry for the confusion. Simply put, I think the `<Sidebar />` component should have the following props: `onClose`, `onOpen`, `onMount` and `onUnmount` that are fired when Sidebar is closed, opened, mounted and unmounted, similar to the `<Modal />` component.

**Comment by samin** [comment]
I'll be happy to do a PR if this is something interesting to add.

**Comment by levithomason** [comment]
Since the sidebar is only opened programmatically by toggling the `visible` prop, the method toggling that value would act as the `onOpen` / `onClose`.  There is no way to open/close the sidebar without manually calling a function yourself.

I don't see a reason to incorporate `onMount` here since the Sidebar is mounted as soon as it is rendered.  The Modal has an `onMount` because it uses a Portal to render itself into the `mountNode` (defaults to `document.body`).  When it is rendered, it is not yet mounted.  This is true for all Portal components, such as a Popover.

It seems the use cases for adding these props can be achieved with the current props.  I am open to adding these props upon seeing some example code that shows where the current props are lacking support.
