### ISSUE TITLE
Radium integration Issue

### ISSUE THREAD

**Issue by athurman** [Semantic-Org/Semantic-UI-React#104]
When using radium, you pass in styles as such: `style={[style.property]}` but when they render on the page, the style attribute shows `style="0 [Object object]"` so, stardust components do not render radium styles.

**Comment by levithomason** [comment]
It looks like Radium only works on built in html components.

``` jsx
//
// Widget.js
//
import React, {Component, PropTypes} from 'react';

export default class Widget extends Component {
  render() {
    return <div {...this.props}>I'm a widget.</div>;
  }
}

//
// WidgetUse.js
//
import React, {Component} from 'react';
import Radium from 'radium';
import Widget from './Widget';

@Radium
export default class WidgetUse extends Component {
  render() {
    return (
      <div>
        <Widget style={[{background: 'coral'}]} />
        <div style={[{background: 'coral'}]}>I'm an html element</div>
      </div>
    );
  }
}
```

The result:

![image](https://cloud.githubusercontent.com/assets/5067638/11041495/ff82b606-86c6-11e5-9601-550fa8acf4f4.png)

---

The style is spread as an array, which React converts to the array like object `0: [object Object]`, before Radium can deal with it.

**Quick fix**
The quick fix would be to use Radium on all our components, however, I'd prefer not to do this since not everyone uses Radium.  Stardust shouldn't dictate it.

**Slightly Better**
We could make a decorator that is a light wrapper around Radium.  It could use Radium if it exists, if not, then it would just return the decorated component directly.  This way, if you install Radium in your project, Stardust will use it, if you don't no harm.  This is a little better because we don't dictate dependencies.  It adds a little magic and an extra wrapper to every component.

There is likely a great solution to this so I want to leave this issue here a while.  If Radium could somehow support composite components, that may be the best solution.

**Comment by levithomason** [comment]
@TechnologyAdvice has no more need for Radium as we've moved to SCSS and WebPack's style loader.  Closing for now, open to further discussion if community interest pushes it.
