### ISSUE TITLE
Dropdown onAddItem gets called on value change when text and value aren't equal

### ISSUE THREAD

**Issue by keeslinp** [Semantic-Org/Semantic-UI-React#1064]
### Steps
1. Create a Select Dropdown with AllowAdditions enabled (and search so you can add them)
2. Set the options so that the text and the values are not equal (for me I had unique id's for values).
3. Add an onAddItem function
4. Whenever the values of the dropdown are changed it calls onAddItem whether or not a new item has changed.

### Expected Result
The onAddItem should only be called when a new item is added not every time the value changes.

### Actual Result
onAddItem is called every time the selected item changes.

### Version
0.63.2

### Testcase
http://codepen.io/anon/pen/XNGNpa

Thanks :)

**Comment by keeslinp** [comment]
I just looked through the code and I think I found the culprit.


https://github.com/Semantic-Org/Semantic-UI-React/blob/50b324165fd2908d0b4aab66d3b02e3a61886a9e/src/modules/Dropdown/Dropdown.js#L417

and here:

https://github.com/Semantic-Org/Semantic-UI-React/blob/50b324165fd2908d0b4aab66d3b02e3a61886a9e/src/modules/Dropdown/Dropdown.js#L511

```
// notify the onAddItem prop if this is a new value
    if (onAddItem && !_.some(options, { text: value })) {
      onAddItem(e, { name, value })
    }
```

It looks like it is comparing the new value to the text of each object to see if the item exists already. So this works fine when they are defined as the same but if they are different then it'll have a false positive and think that you added a new item.

**Comment by levithomason** [comment]
I think this is the result of previous code smell.  I don't think we should be using a "regular" DropdownItem for the "additional item".  It should be programmatically impossible to trigger `onAddItem` from activating a regular item.  This logic should not live in [`selectHighlightedItem `](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L515).

Instead, we should have special handling of the additional item so that only that item has the ability to trigger the path that calls `onAddItem`.

I also do not want to add any more logic or props to this component.  There are currently 51 props available to this component.  I think it is becoming too confusing to use and test and also leading to more bugs.  In the long term, we'll split it up into multiple components, for now, I only want to merge simplifications to it.

That said, let's look at ways to correctly and specifically identify the "additional item" rather than add logic to filter it out of the other items.  Couple ideas that come to mind are to add a special prop (i.e. `data-additional-item`) or make a private `AdditionalItem` component.  This way, there is no cross talk or filtering needed and we don't need to add any more configuration.

**Comment by keeslinp** [comment]
That sounds like the best solution to me. I guess I figured there was a reason it was the way it was, I probably should have been more questioning/done more research.

So basically, remove filtering logic and use a special identifier to tell when the "add:" option was selected and base it on that?

**Comment by levithomason** [comment]
Agreed.  Some deterministic and absolute way of knowing which item is the "add" item.
