### ISSUE TITLE
Popup doesn't work with modal

### ISSUE THREAD

**Issue by mattmacpherson** [Semantic-Org/Semantic-UI-React#1076]
The popup appears, but under the modal. Give it a try. Not really sure if this is React specific or CSS. Apologies if it's the latter.

**Comment by levithomason** [comment]
Please provide a codepen example for repro.  You can fork this one: [codepen.io/levithomason/pen/ZpBaJX](https://codepen.io/levithomason/pen/ZpBaJX).

**Comment by mattmacpherson** [comment]
This should suffice:
https://codepen.io/methodx/pen/ObGwbM?editors=0010

**Comment by levithomason** [comment]
This is likely an issue on our end with the way the Portal works.  A Popup in a Modal is a portal within a Portal.  I haven't tested it, but I'm guessing that it is due to the Portal getting confused about where the real DOM nodes are.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.7`.

**Comment by kunokdev** [comment]
Hello similar issue is still present, in my case it displays Popup behind Modal. I tried to hack it by adding huge zIndex value but that didn't help. Any clue? 

Edit:  Ok, this happens when a modal has dimmer={"blurring"} property. After using false or default value, it is displayed properly.

Edit again:  However the position of element is buggy and similar behavior appears as on codepen example above. It is always positioned around 50px lower than it should be.

Workaround: add style property with "transform" : "translateY(...px)"

"semantic-ui-css": "^2.2.4",
"semantic-ui-react": "^0.66.0",

**Comment by natemartinsf** [comment]
I see the same behavior as @kunokdev 
With a popup in a modal, if the dimmer is set to anything but "false", the popup doesn't appear.

**Comment by levithomason** [comment]
Post a new issue please.
