### ISSUE TITLE
add loading option for modal

### ISSUE THREAD

**Issue by liesislukas** [Semantic-Org/Semantic-UI-React#1095]
i loved how you added loading option for [Form](http://react.semantic-ui.com/collections/form) component, it's so easy to build ui with such options. Would be great to have `loading` flag for [modal](http://react.semantic-ui.com/modules/modal) too. 

For now, I use [segment](http://react.semantic-ui.com/elements/segment) as wrapper, while it has loading option.

```javascript
return (
      <Modal open={true} onClose={handleClose} dimmer={true}>
        <Segment loading={foo.get('loading')}>
          <Modal.Header>...</Modal.Header>
          <Modal.Content>...</Modal.Content>
        </Segment>
      </Modal>
    );
```

**Comment by levithomason** [comment]
Since loaders are CSS powered, this issue would need to be opened on the main Semantic-UI repo.  Our project only concerns itself with JS components that render down to valid Semantic-UI HTML.  There is no CSS in this project.

Note, the core Modal component has no `loading` variation: http://semantic-ui.com/modules/modal

The proposed workaround is a good solve as well.
