### ISSUE TITLE
Pagination Support for Table Component

### ISSUE THREAD

**Issue by cschmidli** [Semantic-Org/Semantic-UI-React#1110]
It would be awesome to add a prop to automatically manage pagination support. Something like

```
<Table
  {...otherProps}
  pagination
  paginationMaxRowsPerPage={20}
/>
```

Are there any plans to add this? Or is there any reason why there are only style examples rather than including functionality?

**Comment by jeffcarbs** [comment]
I think this issue is similar to #926 (sortable tables) in that the pagination should be handled outside of the table component. Check out [this example](http://react.semantic-ui.com/collections/table#types-1) from the docs which shows one way of adding a pagination menu to the table. You'd have to connect click handlers to update the page and change which data gets displayed, etc.

@levithomason - going to close but you can reopen if you disagree here.

**Comment by cschmidli** [comment]
i understand your argument, but at the same time does it make sense that every dev needs to write his/her own 20+ extra lines of code to support pagination? or has to search for an alternative third party solution? Both costs time and is quite inefficient :)

If it's out of question for this library to support either pagination or basic sort functionality directly in the component, it would be nice to have at least some fully working examples of custom components incl. all the click handlers etc. some where in the documentation.

**Comment by levithomason** [comment]
PRs adding more usage examples are highly encouraged and would be merged promptly. Please keep in mind, most of us work on this library because we use it at our jobs. This means most of the time and energy is spent on the needs of those businesses.  Additionally, we offer_a lot_ of time and energy up to the community for free, because we love you :) 

While pagination callbacks are not completely out of the question for me, I do agree with @jcarbo here. Things like pagination and sorting tend to be very particular to the use case and difficult to handle inside the component due the limited scope of data in the component and the broader,  more global, data requirements of pagination and sorting. 

That said, I'd gladly review and merge a PR demonstrating well-designed ways of handling pagination. This library is for the world to build, use, and benefit from.

**Comment by cschmidli** [comment]
@levithomason I fully get what you're saying and we all appreciate a lot the time you're putting into this project :) And I didn't wanna suggest that someone of you would have to do this component. Sorry in case it sounded like that.

That said, I have a simple component of a wrapper that includes pagination, but will create  separate task to discuss it.

**Comment by calvinwhitehurst** [comment]
The following jquery is something I have used several times to make the SUI table pagination work.  It does not however include the chevron icons.  Declare the id of your table as "data" and plug this script in at the bottom of your page where the table is displayed.

```
$(document).ready(function(){
    $('#data').after('<div class="ui right floated pagination menu"></div>');
    var rowsShown = 10;
    var rowsTotal = $('#data tbody tr').length;
    var numPages = rowsTotal/rowsShown;
    for(i = 0;i < numPages;i++) {
        var pageNum = i + 1;
        $('.ui.right.floated.pagination.menu').append('<a href="#/" class="item" rel="'+i+'">'+pageNum+'</a> ');
    }
    $('#data tbody tr').hide();
    $('#data tbody tr').slice(0, rowsShown).show();
    $('.ui.right.floated.pagination.menu a:first').addClass('active');
    $('.ui.right.floated.pagination.menu a').bind('click', function(){

        $('.ui.right.floated.pagination.menu a').removeClass('active');
        $(this).addClass('active');
        var currPage = $(this).attr('rel');
        var startItem = currPage * rowsShown;
        var endItem = startItem + rowsShown;
        $('#data tbody tr').css('opacity','0.0').hide().slice(startItem, endItem).
        css('display','table-row').animate({opacity:1}, 300);
    });
});
```

**Comment by mishaberman** [comment]
Nice script Calvin!
