### ISSUE TITLE
Feat(Dropdown): Optionally return new text value pair from onAddItem

### ISSUE THREAD

**Issue by keeslinp** [Semantic-Org/Semantic-UI-React#1132]
As you can probably tell by now I've been having to do a lot of work with dropdown menus lately :).

I noticed recently that when a new item is added to the dropdown select it calls onChange directly afterwards with the value being the inputed string. I'm proposing we give an optional return value from onAddItem (or something to a similar effect) which would allow the user to specify what they want the value to be which is sent to the onChange function.

The scenario I ran into what that I was adding an item and inserting that item into my redux store with a unique id as the key. Say I added an item called "test", it would call onAddItem which would insert that "test" value into the store with a unique id, then onChange is called with the value "test". Of course it can't find an item with the value "test" so the dropdown just becomes empty. I solved this by using onAddItem to change the state and then blocked onChange from running but I think it would be much more elegantly done with the proposed return value.

I doubt it would take very much effort and I could write up the pull request myself, I just want to verify first that that is a direction we want to go.

Thanks.

**Comment by levithomason** [comment]
>Of course it can't find an item with the value "test" so the dropdown just becomes empty.

Help me understand why this is so, if the store in fact includes the `test` item that was added after `onAddItem`.  I'd expect the store to to find the `test` item if it were just added.

**Comment by keeslinp** [comment]
Sorry, I misspoke. I meant it cannot find a value with the key "test" in the Map. You're absolutely right that there is an item with the value "test". That is how I was able to stop onChange from running is I checked to see if test was included in the object.

In my options prop for the Dropdown I am storing the data as { text: 'some text', value: uniqueID } so when it comes out with "test" instead of a uid as the value it trips up. Adding a new value of 'test' will return { text: 'test', value: 'test' } and there isn't going to be a matching unique-id to 'test'.

Hopefully I explained that a little better :).

**Comment by levithomason** [comment]
I believe an option's value should always be unique and can/should be used as the uid in a store.  This would solve the issue.

Otherwise, I think your solution is the way to go for now:
>I solved this by using onAddItem to change the state and then blocked onChange from running.

I would, however, consider calling only `onAddItem` and allowing the user change the `value` themselves.  This might actually make more sense than the current workflow.  In that case, `onAddItem` wouldn't do anything except give you the item added.  Your use case would add the uid at this point and set state (or dispatch an action).

My resolve, for now, is to close this as is and if it comes up again in the future we'll implement one of the changes we've discussed in this issue.
