### ISSUE TITLE
Dropdown: Icon isn't displayed in selection

### ISSUE THREAD

**Issue by rbideau** [Semantic-Org/Semantic-UI-React#1147]
### Steps
1. Create a select Dropdown with options with text and icon
2. Select an option

### Expected Result
The icon and text should be displayed as the selected option

### Actual Result
Only the text is displayed , not the icon

### Version
v0.63.5

### Testcase
[semantic-ui codepen](https://codepen.io/anon/pen/PWZrLb)
[semantic-ui-react codepen](http://codepen.io/anon/pen/qRbzeW)

**Comment by levithomason** [comment]
### Workaround
I'm a little torn on which way this should go.  A Dropdown option (`Dropdown.Item`) can define both `text` and `content`.  The item's `text` value is displayed in the Dropdown when the item is active.  The `content` is used to show one value in the menu and a different value in the Dropdown when the item is active, see http://react.semantic-ui.com/modules/dropdown#item-content. So, to add text and an icon to the Dropdown for an active item, the item's `text` needs to contain both:

```jsx
const options = [
  { value: '0', text: <span><Icon name='man' /> Man</span> },
  { value: '1', text: <span><Icon name='woman' /> Woman</span> },
  { value: '2', text: <span><Icon name='genderless' /> Other</span> },
]
```

This will render what you are looking for.  Forked example http://codepen.io/levithomason/pen/apNOZp.

### Proper fix
That said, I think your use case is intuitive and should probably work.  What we'd need to do is render the `children` of the active item instead of the item's `text` prop only.  This way, how ever the item ended up rendering in the menu is the how it will render in the Dropdown when active.

This approach will need to consider the fact that the `content` should not be rendered in the Dropdown.  Also, if there are multiple children, then the item's `children` will be an array that we'll need to wrap with another element (i.e. `div`).

Likely, the proper implementation here will be to take the active item's props, remove the `content` and `children`, render a new DropdownItem with said props, and take its children.  This way, we get the proper children given the DropdownItem's props configuration.  The [logic for choosing the text](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L961) would need to handle something like:

```jsx
const { children, content, ...rest } = activeItem.props
const _text = DropdownItem.create(rest).props.children
```

**Comment by rbideau** [comment]
Thank you for your quick feedback.

Your workaround does works but generates the following warnings :
```
Warning: Only strings and numbers are supported as <option> children
Warning: validateDOMNesting(...): <span> cannot appear as a child of <option>. See DropdownParent > Dropdown > option > span.
```
I will try to put together a fix as you suggested and then open a pull request.

**Comment by levithomason** [comment]
Thanks much.  Note that the prop warnings are nonconsequential.  However, we certainly want to fix them :)

**Comment by rbideau** [comment]
I have some trouble implementing this.

It's looks like in this code:
```javascript
const _text = DropdownItem.create(rest).props.children
```
children is `undefined`. I Think it might be due to React lifecycle and the fact that the `DropdownItem `has never been renderered.

I don't want to duplicate some of the logique from `DropdownItem` but I don't the any other options.

**Comment by levithomason** [comment]
If you'd like to open a PR it may get more attention since there will be some code to review / test.

**Comment by levithomason** [comment]
Thanks to @rijk, we have improved how we handle stale issues, see #2761.   Reopening.

**Comment by ThiefMaster** [comment]
Is there any way to get a visible icon while remaining searchable? As soon as I provide an element as text I can't search it anymore.

**Comment by wendyperalta** [comment]
I am also interested in a fix for this.

**Comment by mfen** [comment]
@layershifter thanks for the Flag and Image support, but I think **Icon** support was lost in the [last commit](https://github.com/Semantic-Org/Semantic-UI-React/pull/4003/commits/867fef26b75272668ebd3a8fa426508acaed5db0) of #4003. Was this intentional or is there a chance for a fix?

**Comment by layershifter** [comment]
> @layershifter thanks for the Flag and Image support, but I think **Icon** support was lost in the [last commit](https://github.com/Semantic-Org/Semantic-UI-React/pull/4003/commits/867fef26b75272668ebd3a8fa426508acaed5db0) of #4003. Was this intentional or is there a chance for a fix?

Can you please create an issue for the problem that you mentioned? 🙏
