### ISSUE TITLE
Scroll and fixed column in table ?

### ISSUE THREAD

**Issue by blntylmn** [Semantic-Org/Semantic-UI-React#1185]
İs there a way for vertically and horizontaly scrollable table and fix columns while scrolling ?

**Comment by levithomason** [comment]
Hm, I'm not quite sure I understand exactly what you're asking, but, there is no special scrolling CSS for Tables in SUI so I believe the answer is no.  SUIR only concerns itself with JS components that render down to valid SUI markup.  This sounds like new CSS would need to be added to SUI core that we could then support here in SUIR.

Closing for now, let me know if you feel this should be reopened on our repo.  Otherwise, I'd suggest posting on https://github.com/Semantic-Org/Semantic-UI.

**Comment by henri-hulski** [comment]
So if you have an unstackable table how you make it scroll horizontally on mobile devices?
