### ISSUE TITLE
Request: Search Dropdown onAddItem should optionally prevent onChange call

### ISSUE THREAD

**Issue by mull** [Semantic-Org/Semantic-UI-React#1186]
This is highly debatable and perhaps it should be customisable. My use case is that I have a list of objects and a user needs to search for, but if it's not in the list he'll have to create his own from the name he searched for and add additional required fields. 

That makes the allowAdditions prop perfect. However what a user would enter in the search field might not be representative of an entire object, i.e. a "material object" might need additional fields such as cost.

So in my case I would show more fields (or rather remove the Dropdown and show a different set of inputs) when the user tries to add something. That functionality can easily be trigged from `onAddItem`.

However the problem I am facing is that `onChange` is called immediately after `onAddItem`, which causes awkwardness (for example onChange might be setting a `materialId` but when it's called after onAddItem its value would be the string the user entered.)

Could we make this behaviour customisable? `callOnChangeAfterAdd` is err... awkward but something along those lines you know?

I realise this issue is very verbose and contains no code examples, so apologies for that. If you give the go-ahead for this I could probably contribute the PR myself. :)

**Comment by levithomason** [comment]
Yep, I'm actually in complete agreement with the goal here.  Though, rather than add a prop, I think we should just not callback at all because I don't think we should be automatically making this new item the active item at all.  I just covered this 4days ago here https://github.com/Semantic-Org/Semantic-UI-React/issues/1132#issuecomment-272928232.

The issue is that when an item is added, we call `onAddItem`, then we also update the state of the Dropdown setting the new item as the currently active item.  This immediately fires an `onChange` because the value did change from the previous value to the new item value.  Worse, the new item text is used for the `text` and the `value` which is not ideal for several reasons.

Instead, when an item is added, I propose we only call `onAddItem` and that is it.  Then users can implement whatever workflow they want after that.  If the current value should be updated (current behavior), then pass the new item directly back to the Dropdown `value`.  If something else should be done, then do that instead.

Any thoughts on this?

**Comment by mull** [comment]
What you described is exactly the behavior I would want as well. It is a breaking change though of course.

**Comment by levithomason** [comment]
Great, this one is ready to go if you'd like to pick it up.  Feel free to open the PR as early as possible, no need to wait for it to be ready to merge before opening.

**Comment by layershifter** [comment]
I think that #2113 fully resolves problem, `onAddItem` is now called after `onChange`, so you can control new `value` without problem.

**Comment by nathanhannig** [comment]
That does not solve the issue to my understanding because the onChange event doesn't know that it was triggered from an allowAddition action so you can't cancel onChange if you want to handle everything from the onAddItem event.

**Comment by brianespinosa** [comment]
@nathanhannig if you feel this is still an issue, please open a new report. This is an extremely old ticket.
