### ISSUE TITLE
Dropdown's options can cause key warnings

### ISSUE THREAD

**Issue by Raptoer** [Semantic-Org/Semantic-UI-React#1211]
Line 999 in Dropdown.js currently reads:
```
          <option key={option.value} value={option.value}>{option.text}</option>`
```
This causes problems when two options in the dropdown have the same value since you assign the key manually. Please either do not manually assign a key or do what it does for Dropdown.Item:
 ```
<DropdownItem
        key={`${opt.value}-${i}`}
      />
```

**Comment by levithomason** [comment]
The DropdownItem's use of index for a `key` will be removed as [it is an anti-pattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318).

I'm curious what the use case is for having more than one option in a Dropdown with identical values.  I'd think all option values would be unique, since they are intended to offer a selection of values to the user.

**Comment by Raptoer** [comment]
In our case we are offering a choice of US states to the user, with the one that they are most likely to pick at the top, but it also appears again in the list in it's proper place. 
Do DropdownItems and options even need a manual key?

**Comment by levithomason** [comment]
>Do DropdownItems and options even need a manual key?

All elements in an array must have a `key`.  This is enforced by React.

Usually, when offering common choices at the top, a Dropdown (or select) will only show it once.  I'd highly suggest doing this instead.

If we get more requests for supporting items with duplicate `value`s in the Dropdown, I'll consider changing this behavior.  I'd also consider changing the behavior if you or someone else would like to submit a PR that implements a more robust solution.  I have no special reservations in keeping the current solution other than I don't currently have a better one and do not have the bandwidth to engineer one :)

**Comment by babsonmatt** [comment]
@levithomason How about situations where you might want to use an object as a value?  Is this not intended? 

Currently that yields something like ````1:$[object Object]````

Would it be possible to just pass a key property to use for each option as an override?

**Comment by levithomason** [comment]
You must use a string/number as the value.  There are several reasons for this internal to the component.  I'm currently updating the Dropdown to allow shorthand `options`, #1038, which explored the idea of allowing shorthand values, like objects.  It was decided against due to complexity and it is not simple for users.

I, unfortunately, cannot detail all the reasons ATM due to time constraints. You should use a string/number value and lookup the object in your data array with methods outside of the dropdown.

**Comment by babsonmatt** [comment]
@levithomason thanks for the reply

**Comment by TallOrderDev** [comment]
Since it's not an anti pattern to have multiple values for a dropdown this is now making a very opinionated limitation to force this. 

We use it for states and regions, each state has a region, so we have 50 states that are bringing in 7 values. Like Indiana, Ohio and Kentucky all have a value of "Region 3". 

This is not a weird use case. Instead of looking for a reason to do something, look for a reason not to do it. Which I can't think of any.

**Comment by levithomason** [comment]
@TallOrderDev this issue from Jan 2017 and the Dropdown no longer includes a hidden `select` with `option` elements.  Those old `option` elements are what used to use the key via the `value`.

If you have multiple items with the same value, you should explicitly set a `key` on those options.  If you do not supply a `key`, we are forced to use _something_ so we use the `value`.

Best!
