### ISSUE TITLE
Dropdown laggy if there are more than 1000 elements

### ISSUE THREAD

**Issue by thientran1707** [Semantic-Org/Semantic-UI-React#1268]
Somehow the Dropdown component is laggy if there are lots of elements (1000 elements)

**Comment by levithomason** [comment]
React will be several times slower in development than in production, mostly due to propType checkers and dev tools.

That said, do not put >1000 elements in a Dropdown 😄  You might consider using `<Search />` or even a `<Dropdown />` but showing far fewer items (filtering outside of the dropdown).  I'm open to all targeted optimizations, but, there are no plans to support more than 1000 items.

**Comment by thientran1707** [comment]
hi, I see, i have switched to use the Search component :) it seems ok now
