### ISSUE TITLE
Dropdown: placeholder value

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#1299]
### Steps
1. Open codepen.
2. Click on `Dropdown` element, it's value will be set to `Category 1`
3. Click outside, `Dropdown`'s value will be again `Category`

### Expected Result
Until `Dropdown`'s item will be selected, keep placeholder as `Category`.

### Actual Result
After you click on `Dropdown` it changes value to first option.

### Version
Latest.

### Testcase
http://codepen.io/pzurek/pen/mRJMov

----

@levithomason I'm not sure that this behaviour is bug. Can you clarify?

Based on [stackoverflow](http://stackoverflow.com/questions/41527520/semanti-ui-react-dropdown-how-to-stop-changing-the-placeholder-on-opening) question.

**Comment by levithomason** [comment]
I believe this is the expected behavior and in line with SUIR core:
http://semantic-ui.com/modules/dropdown#dropdown

![http://g.recordit.co/fYXZZvw6KX.gif](http://g.recordit.co/fYXZZvw6KX.gif)


The difference we have is that the dropdown is not making `Category 1` active on blur, whereas, SUIR core would.  We are also changing the placeholder rather than the text.  This makes our interaction more jarring than SUIR core.

Proposals, on selected (highlighted) item change:

- [ ] change the text, not the placeholder, for `selection`
- [ ] change the placeholder only for `search` Dropdowns
- [ ] do not change text for regular Dropdown menus

(I responded on SO as well)

**Comment by levithomason** [comment]
We've largely addressed these issues now in the latest version.  Feel free to open if you think more needs done.

**Comment by layershifter** [comment]
@levithomason I reopened this issue because it wasn't fixed and I want to pick up it.

**Comment by EulerTourist** [comment]
Hi, I'm needing this exact behaviour as well, as described by levithomason. I'd be happy to come on as a test resource.
