### ISSUE TITLE
Add animation to Modal Show AND Modal Hide

### ISSUE THREAD

**Issue by athurman** [Semantic-Org/Semantic-UI-React#13]
modal component should fade in / fade out when being shown.

**Comment by levithomason** [comment]
Agreed, ideally this should be accomplished with Semantic's jQuery.  This way it adheres to Semantic's consistent behaviors.

**Comment by levithomason** [comment]
Animation will be handled in the animation issue.

**Comment by sarbjeetsingh** [comment]
Hey @levithomason  any progress on adding animation to modal show hide

**Comment by brianespinosa** [comment]
@sarbjeetsingh whoa. Issue number 13. This is pretty old. Transitions will be handled by the new `Transition` component but they still need to be added to each component in the library. [You can watch this PR for progress on the `Dimmer` component](https://github.com/Semantic-Org/Semantic-UI-React/pull/2001). The `Modal` component will probably follow next. Community PRs are always welcome if you want to follow along yourself.

Since this issue is very outdated, with more current issues open discussing progress on PRs like above, I am going to lock to reduce noise for anyone else who might land here.
