### ISSUE TITLE
Feature request: handler for <List selection/>

### ISSUE THREAD

**Issue by rokoroku** [Semantic-Org/Semantic-UI-React#1301]
List could be selectable (or clickable) with `selection` prop, but there is no way to catch the event.

I'll be very happy when we have a new prop like `onItemClick` from menu.
```js
    /**
     * onClick handler for ListItem. Mutually exclusive with children.
     *
     * @param {SyntheticEvent} event - React's original SyntheticEvent.
     * @param {object} data - All item props.
     */
    onItemClick: customPropTypes.every([
      customPropTypes.disallow(['children']),
      PropTypes.func,
    ]),
```

**Comment by levithomason** [comment]
I would take a PR for this.

A workaround is to pass the handler to each item either as a component prop or shorthand object prop.  You can also let the event bubble and capture it.

http://codepen.io/levithomason/pen/WRYaxY

This does not give you the item's props, which is why I'd take a PR for this feature.

**Comment by rokoroku** [comment]
For someone who wants props, here is another workaround currently I use. 
We can receive props in this way :)

http://codepen.io/anon/pen/WRYYdw

**Comment by layershifter** [comment]
Was done in #1530
