### ISSUE TITLE
Feature Request: AllowAdditions in dropdown to retain text on focus

### ISSUE THREAD

**Issue by cytey** [Semantic-Org/Semantic-UI-React#1305]
### Steps
1. Have a dropdown that allow additions
2. Type "apple" in the input
3. Add "apple"
4. Click on the dropdown input

### Expected Result
It should retain the "apple" instead of clearing it and the input cursor position should be after the word "apple"

### Actual Result
Upon clicking on the dropdown input, the "apple" is no longer editable

### Version
0.64.7

### Testcase
Allow Additions section
http://react.semantic-ui.com/modules/dropdown

**Comment by levithomason** [comment]
The input value is the search query.  Retaining the input value would mean retaining the search query after a user activates an item.  My hunch is that this is not desirable for the majority of use cases.  When a user searches for something and then chooses that item, the Dropdown should show the full item that was chosen (rather than retaining the partial search query).

If we get more requests for this, we'll consider adding something.
