### ISSUE TITLE
Very thin bug

### ISSUE THREAD

**Issue by shavidzet** [Semantic-Org/Semantic-UI-React#1316]
There is 'very thin' value for Sidebar width property
<img src="http://i.imgur.com/sepnjNx.png">

**Comment by levithomason** [comment]
Note, this repo does not include nor address CSS.  This repo only concerns itself with React Components, JS.  Please post CSS issues on https://github.com/Semantic-Org/Semantic-UI.


That said, the menu is too large to fit in a very thin sidebar.  Use an `icon` menu, `size='massive'` shown here:

http://react.semantic-ui.com/collections/menu#icons

![image](https://cloud.githubusercontent.com/assets/5067638/22891730/1b6ed2c2-f1c5-11e6-9615-5fa154fd70ba.png)

Otherwise, you'll need to add some custom styling.
