### ISSUE TITLE
Tabular menu items do not display special characters

### ISSUE THREAD

**Issue by achimkoellner** [Semantic-Org/Semantic-UI-React#1340]
```
import React from 'react';
import { Menu } from 'semantic-ui-react';

class MyMenu extends React.Component {
    render () { 
        return (
            <Menu tabular attached="top">
                <Menu.Item name="Übersicht" active/>
                <Menu.Item name="Würstchen" />
                <Menu.Item name="Lärchen" />
            </Menu>
        );
    }
})

export default MyMenu
```

The code above will render Tabs labeled with "Ubersicht", "Wurstchen" and "Larchen".

**Comment by levithomason** [comment]
### Pasting this code into the docs produces:

![image](https://cloud.githubusercontent.com/assets/5067638/23072806/f184bcee-f4e7-11e6-86a9-174648dad3f5.png)

### Fixing that error produces:

![image](https://cloud.githubusercontent.com/assets/5067638/23072765/c569cdc0-f4e7-11e6-8af0-8ffb29f69d93.png)

**Comment by achimkoellner** [comment]
Hi levithomason, but look it does not display the special characters in this example.
It displays Ubersicht instead of Übersicht

**Comment by levithomason** [comment]
Ah, I see.  Yes, this is because if no `content` is provided for the menu item, the name is Start Cased and used for the content: `_.startCase(name)`.  That process appears to deburr the characters.

To keep them, you should explicitly set the `content` to the special characters you want to see:

![image](https://cloud.githubusercontent.com/assets/5067638/23076789/a2fcae42-f4f6-11e6-9d23-c8e0d6acb199.png)

The `name` prop is the "Internal name of the MenuItem".  It is the programmatic name used in the `onItemClick`, you can see the `name` usage with the callback in the 4th Menu example in the docs:

```jsx
import React, { Component } from 'react'
import { Menu } from 'semantic-ui-react'

export default class MenuExampleNameProp extends Component {
  state = {}

  handleItemClick = (e, { name }) => this.setState({ activeItem: name })

  render() {
    const { activeItem } = this.state

    return (
      <Menu>
        <Menu.Item
          name='editorials'
          active={activeItem === 'Editorials'}
          onClick={this.handleItemClick}
        />
        <Menu.Item
          name='reviews'
          active={activeItem === 'Reviews'}
          onClick={this.handleItemClick}
        />
        <Menu.Item
          name='upcomingEvents'
          active={activeItem === 'upcomingEvents'}
          onClick={this.handleItemClick}
        />
      </Menu>
    )
  }
}
```

Notice also how these names are camelCased, but the menu displays them Start Cased in the rendered items.

**Comment by achimkoellner** [comment]
However Levi, it works thanks a ton!

**Comment by jarben** [comment]
Just burned a few hours before finding this issue. Would be great if name works with utf-8!

**Comment by levithomason** [comment]
PRs welcome! See the [CONTRIBUTING.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md) setup and more info.

**Comment by Cicko** [comment]
How Can I set the content of each tab? There are no examples of it.

**Comment by levithomason** [comment]
Usage questions are best answered on gitter, see link in the README badges.  That said, I'm not exactly sure what you are asking.
