### ISSUE TITLE
Sidebar Menu UI Bugs

### ISSUE THREAD

**Issue by subodhpareek18** [Semantic-Org/Semantic-UI-React#1346]
Some comparisons with a pure semantic-ui project (non react):

```jsx
<Sidebar 
  as={Menu} 
  animation='push' 
  width='very thin' 
  icon='labeled' 
  vertical 
  inverted>
```

Expected Sidebar Behavior
![image](https://cloud.githubusercontent.com/assets/12589797/23102738/dd571976-f6d4-11e6-9592-b8a7339fe371.png)

Actual Sidebar Behavior
![image](https://cloud.githubusercontent.com/assets/12589797/23102728/afcffae0-f6d4-11e6-905c-dfe7797a8261.png)

As you can see the menu is getting hidden under `Sidebar.Pusher`

------

```jsx
<Menu.Item disabled link name='/jobs'>
  <Icon name='briefcase' />
  Jobs
</Menu.Item>
```

Expected Behavior:
![image](https://cloud.githubusercontent.com/assets/12589797/23102755/2981082a-f6d5-11e6-9248-fc7ab50f6c14.png)

Actual Behavior:
![image](https://cloud.githubusercontent.com/assets/12589797/23102770/5d72eeb4-f6d5-11e6-8b9f-0e24e39d2da8.png)

Disabled prop is having no effect on the menu item.

------

Also facing issues with most of the animations (only push seems to be usable)
![feb 19 2017 7-00 pm](https://cloud.githubusercontent.com/assets/12589797/23102825/3fa7c782-f6d6-11e6-81c7-a14a16d290d8.gif)

Now I can see in the docs that all of the animations are working fine, so what can I do to achieve better performance?

**Comment by levithomason** [comment]
A `very thin` sidebar simply does not have enough space to fit a labeled icon menu.  You'd need to customize the CSS theme and set `@labeledIconMinWidth: 0;` in the Menu overrides.  Otherwise, the menu items are set to have a min width that is wider than the sidebar.

Another option is to not use an `icon='labeled'` menu, but just an `icon` menu (`size='massive'` in this case):

<img src="https://cloud.githubusercontent.com/assets/5067638/23146221/b5651a7a-f789-11e6-8995-0d86f0907fc9.png" width="300" />
