### ISSUE TITLE
How to programatically submit a <Form> component

### ISSUE THREAD

**Issue by achimkoellner** [Semantic-Org/Semantic-UI-React#1348]
Please add documentation on how to programatically submit a <Form> component.
I guess it's about adding a ref and calling submit on it or is there another option?

**Comment by levithomason** [comment]
Manually call the method that you'd otherwise pass to the `onSubmit` prop.  You should capture your form data in state using form control `onChange` handlers.

PRs welcome :)

**Comment by dvdzkwsk** [comment]
Also, unless it's explicitly documented, you should avoid using internal methods of the form (or any other) component. This is because doing so means reaching through what should be an opaque abstraction into internal methods that may change at any time.

So, unless these methods become a formal part of the public API, it's likely best to follow @levithomason 's advice. Furthermore, it's generally bad practice to reach _downward_ through the React tree in order to initiate side effects.

**Comment by levithomason** [comment]
FWIW, I actually plan to remove the onSubmit handler as it has caused lots of confusion and encouraged bad practice.  The current implementation is DOM based anyhow, which just makes it this much worse.
