### ISSUE TITLE
Add `textAlign` and `verticalAlign` to Table component

### ISSUE THREAD

**Issue by levithomason** [Semantic-Org/Semantic-UI-React#1389]
We currently support these props on headers, row, and cells.  However, the CSS allows for a single top level prop on the table as well:

https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/table.css#L419

We should support this:

```jsx
<Table textAlign='center' verticalAlign='middle' />
```

The props should exist and work identically to how they work on the `Table.Header`, `Table.Row`, and `Table.Cell` components.

When the prop is added, we should update the descriptions of these examples in the docs:

http://react.semantic-ui.com/collections/table#vertical-alignment
`A table header, row or cell can adjust its vertical alignment.`

http://react.semantic-ui.com/collections/table#vertical-alignment
`A table header, row, or cell can adjust its text alignment.`

Both of these should then include `A table, header, row, or cell...`.

**Comment by ctlusto** [comment]
One potential problem with `verticalAlign` is that some user agents (notably newer Chrome and FF, at least) set `vertical-align: middle;` on `<thead>` and `<tbody>` elements, so rows and cells actually inherit _that_ alignment instead of the alignment set on the `<table>` itself. It doesn't appear that Semantic CSS does anything to help that.

Not sure the right thing to do.

**Comment by levithomason** [comment]
One purpose of the React components is to render valid SUI HTML. That said, I'd still like to check out an example of the issue you are referring to :)  I use the latest Chrome and haven't yet noticed any vertical alignment issues with adding this className to tables.

Here I'm cycling through the three values for the `* aligned` className.  I've applied the className to the table, the entire first row, and a single column in the second row.  I see there is a CSS rule for the table selector for each align value.  In the far lower right, I can also see that the computed style for the table shows the proper vertical-align value, indicating that at least my browser's user agent (latest Chrome) does not override the CSS rule.

I do see that even though the user agent style for `td` is `vertical-align: inherit` its computed value is still `vertical-align: middle`.  Is this what you are referring to?

See `td` first child in row 2, it does not inherit the table vertical align.  I should point out that this is purely curiosity, we actually don't handle CSS here. CSS issues and development are posted at https://github.com/Semantic-Org/Semantic-UI :)

![http://g.recordit.co/riftRW3CsG.gif](http://g.recordit.co/riftRW3CsG.gif)

**Comment by ctlusto** [comment]
Sorry, what I meant was if you apply, say, `vertical-align: top;` to _only_ the `<table>` element, the `<td>` elements' text will still be aligned to the middle because `tbody: { vertical-align: middle; }` and `td: { vertical-align: inherit; }` are set by the UA stylesheet.

Which is maybe not the behavior people expect. But like you said, that's probably beside the point here.

**Comment by levithomason** [comment]
Whoops, closed this one by mistake :)  We still want the props added.  Thanks for the clarification as well.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.1`.

**Comment by layershifter** [comment]
@levithomason Props were added in #1411 or I miss something?

**Comment by levithomason** [comment]
I see what happened, I thought I somehow closed this issue by mistake, however, it was merging the PR 11 days ago that closed it. Reopening it was a mistake. 😸
