### ISSUE TITLE
Dropdown: Clicking on "No results found." leads to hard to remove text from input

### ISSUE THREAD

**Issue by nreijmersdal** [Semantic-Org/Semantic-UI-React#1451]
### Steps
1. Type enough characters in a "fluid multiple selection search" dropdown until "No results found." is displayed.
2. Click "No results found."
3. Double click the empty space right of the typed text to select it. Do not double click the text itself.
4. Press backspace or delete

### Expected Result
The text is removed

### Actual Result
Text stays selected

### Notes

- Semantic-UI doesn't allow clicking on "No results found."
- Only with **fluid**, text selection works fine without fluid.
- Maybe click on "No results found." should just remove the text just as if you click outside the dropdown to cancel it.

### Version
Semantic-UI 2.2.9
React Semantic-UI 0.67.0

### Testcase
http://codepen.io/nreijmersdal/pen/JWJbbg

**Comment by levithomason** [comment]
Having a hard time reproducing this, what am I missing?

![http://g.recordit.co/VyBKDYtREM.gif](http://g.recordit.co/VyBKDYtREM.gif)

**Comment by nreijmersdal** [comment]
@levithomason thanks for your effort. Seems you need to double click more to the right. Like in the middle of the bar. Its about 200pixels right from the text during my testing.

Could also be a Chrome (Version 56.0.2924.87 64-bit) issue. Haven't tested on other browsers.

**Comment by levithomason** [comment]
Ah yes, it appears the issue is that the search input is far too narrow:

![image](https://cloud.githubusercontent.com/assets/5067638/23886411/f64fa654-0837-11e7-966b-1a4407f59780.png)

It would appear this is also the case in SUI core:
![image](https://cloud.githubusercontent.com/assets/5067638/23886454/43f21eb4-0838-11e7-92f1-4cd0495108b4.png)

However, the core Dropdown focuses the search input when the Dropdown is clicked.  We need to implement something similar.

**Comment by ozzy432836** [comment]
Is it possible to add a click event to no results found? I have put a compnent that returns an Icon with an onClick event instead of a string and it works but I get an error Failed prop type: Invalid prop `noResultsMessage` of type `object` supplied to `Dropdown`, expected `string`.
