### ISSUE TITLE
Sidebar behavior issues?

### ISSUE THREAD

**Issue by DanHarman** [Semantic-Org/Semantic-UI-React#1459]
I'm trying to port a sidebar example I found for semantic-ui https://codepen.io/redshift7/pen/VaKmjq to semantic-ui-react and have run into a few problems. I'm not sure if they are mistakes on my part but thought I'd raise it.

Here is my codepen with it ported as best I can http://codepen.io/mmph/pen/ryzYmB. I am observing the following issues:

1. The height of the sidebar and the basic segment is not filling the window. : edit : I guess that's because it's nested in a div, so that's an easy fix by modifying the style of the containing div.
2. There is something up with how far the menu is pushing the pusher. It should only push it as far as it needs, but it pushes way further. I can fix this by putting an explicit width on the Sidebar, but its a bit awkward compared to the non react version which seems to dynamically accommodate the content of the sidebar?
3. This may be unimplemented at the moment, but the pusher isn't dimming when pushed?

Thanks for the great work on the project. It's really nice to have it all as components!

**Comment by jonmajorc** [comment]
Hello @DanHarman I took a look into this tonight because I had this similar issue too actually. 

In response to your following issues:
1. It seems like you answered your first question so I didn't really look into it.
2. This was my problem too, so I did some recon looking into the css that is being generated by the class `pusher` and it looks like there is a: `    transform: translate3d(260px,0,0);` so there is some logic that is by default choosing `260px`, so here is the a quick work around I did in a forked codepen of your react-semantic-ui example of the sidebar: http://codepen.io/sirJconny/pen/BRzQEx
3. I swore looking in the react-semantic-ui documenation there was the ability to dim the `pusher` but I looked again, and there is currently nothing. 

I plan to look into `#2` tomorrow to see if I can fix this issue. This would also be my first PR too 😊

**Comment by levithomason** [comment]
1. You need more vertical content on the page.
1. `width='thin'` so the Sidebar is only as wide as the icon menu.  Semantic UI CSS provides [5 widths](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/sidebar.variables#L37).
1. `<Sidbar.Pusher dimmed />`, this should be toggled with your `menuVisible` state.  There is no example but the prop is documented here:
    
    <img src=https://cloud.githubusercontent.com/assets/5067638/25306093/68cac372-273b-11e7-91d0-9421204ce63a.png width=500>

***

Here is a fork with the fixes above, http://codepen.io/levithomason/pen/ZKOXPd:

![http://g.recordit.co/kg7g5EUxYD.gif](http://g.recordit.co/kg7g5EUxYD.gif)

**Comment by jonmajorc** [comment]
@levithomason what do you think about adding custom support to width size? Currently its limited to the 5 widths.

**Comment by levithomason** [comment]
Unfortunately, I don't think it is within our scope to do so as it is CSS driven by the theme variables.  The width prop renders a CSS className which has a corresponding width associated:

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/sidebar.variables#L37

As we move toward a future library possibly based on generated CSS, we'll have the ability to style any component the way we wish.  This is likely 2.0 work and far out in the timeline, but you can see seeds of it in #1579.

**Comment by sundeer** [comment]
OP issue-(2) is still a problem.
[https://react.semantic-ui.com/modules/sidebar#sidebar-example-left-push](https://react.semantic-ui.com/modules/sidebar#sidebar-example-left-push)
Remove width='thin' prop. I like that default width but content is pushed way to far.

**Comment by Shuliyey** [comment]
update (override to be more precise) the css of the `left sidebar` and `pusher`

```
    .ui.left.visible.vertical.menu ~ .pusher {
      transform: translate3d(86px, 0, 0)
    }
```

`86px` can be replaced the width of the `.ui.left.visible.vertical.menu`
