### ISSUE TITLE
Form.Select error style is messed up

### ISSUE THREAD

**Issue by jeremyjohn** [Semantic-Org/Semantic-UI-React#1462]
### Steps
The **error** prop for **Form.Select** styling is messed up.
There is a white background on the active selected option.
```
const countryOptions = [ 
   { key: 'af', value: 'af', flag: 'af', text: 'Afghanistan' }, 
   { key: 'cn', value: 'cn', flag: 'cn', text: 'China' }
];
<Form>
    <Form.Select 
       error 
       placeholder='Select Country' 
       fluid 
       options={countryOptions} 
    />
</Form>
```
### Expected Result
_Using `<Dropdown />` component works fine:_
![screenshot-react semantic-ui com-2017-03-15-11-07-58](https://cloud.githubusercontent.com/assets/12860603/23931918/c41b2dd2-096f-11e7-844e-bc656ae88ac5.png)
### Actual Result
_But `<Form.Select />` doesn't_ 
![screenshot-react semantic-ui com-2017-03-15-11-05-39](https://cloud.githubusercontent.com/assets/12860603/23931923/c58a9b8a-096f-11e7-8953-9f24d3b45948.png)
### Version
0.67.0

**Comment by levithomason** [comment]
Heads up `Form.Select` produces a `Form.Field` that contains a `Select`, whereas, a `Select` has no wrapping element.  When using the form field shorthand, the `error` is then a form field error, and not a `Select` error.

So the issue is that a select in a form field is incorrectly styled:

![http://g.recordit.co/cVMjzuNVbC.gif](http://g.recordit.co/cVMjzuNVbC.gif)

This is a CSS issue and should be opened on https://github.com/Semantic-Org/Semantic-UI as this repo only contains React components that render down to valid SUI markup.

**Comment by jeremyjohn** [comment]
@levithomason @layershifter 
Hi I think the problem is with the **"text"** class inside span in dropdown item see this JSFiddle which has a comparison render between SUI and React's SUI:
http://jsfiddle.net/uwp6a3ux/

If you remove the text class it works, i think the error class is not following SUI markup completly

**Comment by levithomason** [comment]
OK, looks like there are 2 issues here. One is ours and one is SUI core's:

SUIR should only add the `text` class when there is an adjacent `description`.  Though, technically it should always work if SUI fixes their error.  I actually wouldn't call this an error since the markup is valid and once they fix the issue, ours will still work.  I don't think the extra logic to add this class is worth it.

SUI core still has this issue in its own CSS.  To see it, you need to put a dropdown with `text` spans (requires `descriptions`) into a `.ui.form > .error.field`:

I've simply wrapped the dropdown with `text` from this example: https://semantic-ui.com/modules/dropdown#description

![image](https://cloud.githubusercontent.com/assets/5067638/24433591/a714ada2-13de-11e7-8c51-de9f5f5709e2.png)

```html
<div class="ui form">
  <div class="error field">
    <div class="ui floating labeled icon dropdown button active visible" tabindex="0">
      <i class="filter icon"></i>
      <span class="text">Filter Tags</span>
      <div class="menu transition visible" tabindex="-1" style="display: block !important;">
        <div class="header">
          Filter by tag
        </div>
        <div class="divider"></div>
        <div class="item">
          <span class="description">2 new</span>
          <span class="text">Important</span>
        </div>
        <div class="item">
          <span class="description">10 new</span>
          <span class="text">Hopper</span>
        </div>
        <div class="item">
          <span class="description">5 new</span>
          <span class="text">Discussion</span>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by lubber-de** [comment]
The CSS Part was fixed in the community fork [Fomantic-UI](https://fomantic-ui.com) by
https://github.com/fomantic/Fomantic-UI/pull/1803
