### ISSUE TITLE
Dropdown: Unnecessary extra calls state of focus.

### ISSUE THREAD

**Issue by realgvard** [Semantic-Org/Semantic-UI-React#1495]
### Steps
1. Initialize component with a property of state "options".
2. Try to remotely update the same property of state "options".

### Expected Result
The size of collection items should be changed or not, it's no matter. But behavior should be quite silent.

### Actual Result
I see like component manually change several properties of state: focus, open And it affects on a manual opening of this dropdown. My question, why it's happening? Because in my case it's produced like the bug. Seems like every change of property "options" manually change this state. Is it normal?

### Version
React Semantic-UI 0.67.1

### Testcase
http://react.semantic-ui.com/modules/dropdown#dropdown-example-inline

**Comment by levithomason** [comment]
I believe you are saying that setting the `options` asynchronously results in the the focus and open state of the Dropdown changing.  Please correct me if I misunderstood that.

If I am correct, here is an example of a Dropdown who's options are changing on an interval every 2s.  Note that the focus and open states are unaffected by the changing options:

![http://g.recordit.co/WT5AsFz4st.gif](http://g.recordit.co/WT5AsFz4st.gif)

If I've missed the issue here, please post a codepen.io demonstrating the bug and I'll reopen and investigate.  You can fork this one to get started: https://codepen.io/levithomason/pen/ZpBaJX
