### ISSUE TITLE
`<Item />` image prop needs to be extended

### ISSUE THREAD

**Issue by athurman** [Semantic-Org/Semantic-UI-React#150]
currently, the image prop accepts a node, but the Item component just spreads the props of that node onto an `<img />` element: https://github.com/TechnologyAdvice/stardust/blob/master/src/views/Items/Item.js#L43

There are use cases where this particular piece of the item is not specifically an image but different elements, such as icons or divs. The Item image prop needs to be able to extend on those nodes as well.

**Comment by levithomason** [comment]
Looking in the [Item docs](http://semantic-ui.com/views/item.html) I only see that the definition includes `image` as content.  There is one example with an icon, but it is in the `header`  Could you provide an example of how it is not working where it should be in Stardust?

The `<Item />` is doing some funky stuff with images here.  IIRC this was due to the two variations of images in Semantic UI.  They can be either an image, or a div wrapped image.  The `<Image />` element chose the more simple `img` tag.  This means when used in an `<Item />` the `<Image />` needs to be wrapped in a div and it's classes remove and applied to the `div` instead.

It is ambiguous and debateable where the rest of the user's props should be spread.  We chose the image as our current convention is to the spread the props on the "element of concern" in a component (ie `img` for `<Image />`).

**Comment by levithomason** [comment]
This issue is no longer relevant as the components are being revamped for v1. 0.  Props will not be the primary way of building components.
