### ISSUE TITLE
Use Semantic-UI-React without Webpack ?

### ISSUE THREAD

**Issue by bcmdev** [Semantic-Org/Semantic-UI-React#1522]
I noticed all samples rely on Webpack, using "import". Is it possible at all to use the components without webpack?

Just tried to do it that way but it is not working.

<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui-react/0.67.2/semantic-ui-react.min.js"></script>
<script>

    const ButtonExampleAnimated = () => (
        <div>
            <Button animated>
                <Button.Content visible>Next</Button.Content>
                <Button.Content hidden>
                    <Icon name='right arrow' />
                </Button.Content>
            </Button>

            <Button animated='vertical'>
                <Button.Content hidden>Shop</Button.Content>
                <Button.Content visible>
                    <Icon name='shop' />
                </Button.Content>
            </Button>

            <Button animated='fade'>
                <Button.Content visible>
                    Sign-up for a Pro account
                </Button.Content>
                <Button.Content hidden>
                    $12.99 a month
                </Button.Content>
            </Button>
        </div>
    );
    
</script>

Thanks,
Marc

**Comment by levithomason** [comment]
You can use any bundler you like.  We use Webpack, but you can use Rollup, Browserify, or any other build tool that can handle modules.  The choice of module syntax is up to you, AMD, CommonJS, ES imports, or even a UMD browser global (not recommended).

We provide several build targets:

- `semantic-ui-react/dist/umd` - for browser globals
- `semantic-ui-react/dist/es` - includes ES imports (e.g. Rollup, etc)
- `semantic-ui-react/dist/commonjs` - the default, uses `require()` module syntax

You can also compile the source yourself if you choose by loading:

- `semantic-ui-react/src` - for the full library
- `semantic-ui-react/src/elements/button` - for a single component

It looks like you're going for a browser ready build.  While this is OK for prototyping, it is not recommended for production apps.  You should use a build tool.  That said, you can see a browser global setup in our repo here:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/browser/index.html

Just replace `<script src="../dist/umd/semantic-ui-react.min.js"></script>` with your CDN link.  This will compile in the browser, which is why it is not recommended for production.  We do use this exact setup for our [codepen.io example](codepen.io/levithomason/pen/ZpBaJX) as well.

**Comment by bcmdev** [comment]
Thank you!
