### ISSUE TITLE
Checkmark icon changes to Medium icon with size medium

### ISSUE THREAD

**Issue by cemremengu** [Semantic-Org/Semantic-UI-React#1550]
Bug ? Easter egg ? More coffee ? :smile: 

### Steps
`<Icon name='checkmark' color='green' size='medium'/>`

### Expected Result
![capture](https://cloud.githubusercontent.com/assets/1297759/24746970/81db700c-1ac3-11e7-8199-d3ce266cafa1.PNG) (this is with `tiny` size I expect a size `medium` checkmark)

### Actual Result
![medium](https://cloud.githubusercontent.com/assets/1297759/24746994/96988b6a-1ac3-11e7-8c29-18a0876e7f05.PNG)

### Version
0.67.1

**Comment by layershifter** [comment]
`Icon` component [doesn't support](https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.67.2/src/elements/Icon/Icon.js#L113) `medium` size. In SUI, [too](https://semantic-ui.com/elements/icon.html#size).

**Comment by levithomason** [comment]
Indeed, omitting the size results in the "medium" size.  This is an intentional implementation detail to support the `medium` brand name.

![image](https://cloud.githubusercontent.com/assets/5067638/24747517/76f4daa4-1a71-11e7-9ad5-76ac92a463fa.png)

Note, many components do not support a `medium` size and instead use no size as the medium size.

**Comment by cemremengu** [comment]
Thanks for the quick response and, of course, great work! @layershifter @levithomason
