### ISSUE TITLE
Grid verticalAlign="middle" FOUC

### ISSUE THREAD

**Issue by itsmoops** [Semantic-Org/Semantic-UI-React#1708]
I'm trying to create a center aligned FlexContainer wrapper component using the Grid component:
https://github.com/itsmoops/react-redux-webpack/blob/master/src/components/shared/flex-container.jsx

### Steps
Create a height: 100% Grid with verticalAlign="middle"

### Expected Result
Grid content should render in the center of the page

### Actual Result
Content flashes on the top of the screen before rendering correctly in the center (only on initial page load)

### Version
0.68.3

### Testcase
This codepen does not seem to produce the issue
https://codepen.io/itsmoops/pen/WjWMxb

But I am seeing it in my boilerplate which (seemingly) is doing the same thing...
https://github.com/itsmoops/react-redux-webpack
```
npm i
npm start
```

**Comment by levithomason** [comment]
Semantic UI React components simply render to valid Semantic UI HTML, there is no window of opportunity available to create a FOUC.  In order for this to happen, the CSS must be getting loaded _after_ the HTML body is loaded.

It appears [you are using](https://github.com/itsmoops/react-redux-webpack/blob/master/webpack.config.js#L23) the [style-loader](https://github.com/webpack-contrib/style-loader), which:

>Adds CSS to the DOM by injecting a <style> tag

It can only do this once the bundle has loaded because the injection code is within the bundle itself.  The bundle also includes the components.  The bundle is also loaded in the `<body>`.  Therefore, the bundle is loaded, parsed, and executed which renders the components before the CSS can be injected into the page.  Then, the CSS is injected, parsed, and applied by the browser.  Hence, your components are loaded before the initial CSS is applied causing a FOUC.

You'll need to load critical CSS in the `<head>` of your document so that it is loaded, parsed, and applied by the browser _before_ your components are rendered.

**Comment by itsmoops** [comment]
@levithomason thank you for the thorough explanation, this was exactly the issue! I ended up adding extract-text-webpack-plugin to my webpack build process and referencing the generated file in the `<head>` as you suggested and boom, no more FOUC.
