### ISSUE TITLE
Dropdown: content shorthand prop not working for search dropdown

### ISSUE THREAD

**Issue by saitonakamura** [Semantic-Org/Semantic-UI-React#1754]
### Steps

Use a `search` dropdown with `options` prop using `content` shorthand instead of text

### Expected Result

Dropdown filters the result correctly

### Actual Result

Dropdown filters the result incorrectly

### Version
0.68.5

### Testcase
[https://codepen.io/saitonakamura/pen/LLGQKa?editors=0010](https://codepen.io/saitonakamura/pen/LLGQKa?editors=0010)

[This line](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L757) is causing this

```
filteredOptions = _.filter(filteredOptions, (opt) => re.test(opt.text)
```

I think it should be like that
```
filteredOptions = _.filter(filteredOptions, (opt) => re.test(opt.text || opt.content)
```

**Comment by levithomason** [comment]
The `text` and `value` pair are used sort of like they are in an HTML `option`.  We can safely filter on `text` because it is always a string.  The `text` is also used as the display value inside the Dropdown when an item is made active.  This means, `text` is required for searching and is required for displaying the active item.

However, `content` is used for the display value _within the menu_.  It is not intended to be used with a string, use `text`, but intended when you want to render something more complex in the menu.  However, `text` is still required as when you make that complex item active, we show the item's `text` in the Dropdown:

https://react.semantic-ui.com/modules/dropdown#dropdown-example-item-content

![image](https://user-images.githubusercontent.com/5067638/26987557-d839f166-4d00-11e7-8cbe-e5681a48accf.png)
