### ISSUE TITLE
Dropdown: doesn't change text on select when using text prop

### ISSUE THREAD

**Issue by saitonakamura** [Semantic-Org/Semantic-UI-React#1756]
### Steps

Create a dropdown with `text` prop and set some options

### Expected Result

Text changes when selecting an option
[original Semantic UI docs proof](https://semantic-ui.com/modules/dropdown.html#header)

### Actual Result

Text is not changing

### Version
0.68.5

### Testcase
[https://codepen.io/saitonakamura/pen/NgxMNL?editors=0010](https://codepen.io/saitonakamura/pen/NgxMNL?editors=0010)

**Comment by levithomason** [comment]
By setting `text` you are controlling the value yourself.  You'd have to change the `text` prop on item change in order to update it.  Read more on controlled/uncontrolled components here:

https://facebook.github.io/react/docs/uncontrolled-components.html

If you'd like the text to change on select, simply remove the `text` prop (making it uncontrolled) and the component will control the value itself.
