### ISSUE TITLE
Message: add the ability to provide custom color

### ISSUE THREAD

**Issue by LeoAref** [Semantic-Org/Semantic-UI-React#1844]
Unfortunately the `Message` component does not support providing custom colors, what if I need the message to have `white` color for instance?

So I think adding this ability will be very handy.

**Comment by vaidsu** [comment]
@LeoAref  Won't wrapping the message in a div and overriding the style color won't help?

**Comment by LeoAref** [comment]
Yeah, this should work, but this means I've to do that with all other elements as well, the idea is making the `color` property could accept one of the available colors or hex color

**Comment by layershifter** [comment]
> The color names are defined by Semantic UI css selectors, they are not actual inline style css colors.

Duplicate, #941.

**Comment by sharno** [comment]
As Progress component as well has a inner div, it's not possible to style without a css file because it's hidden from the API, I think adding the ability to add custom colors to certain elements which hide other nested elements would be great.
Semantic UI originally doesn't do this because there's full control on all elements. But the react way hides some elements that are necessary sometimes to style. If that makes sense can we open the issue again?

**Comment by layershifter** [comment]
Use CSS/LESS and Semantic UI's theming. It's the way for now as SUIR doesn't provide styling at all now.
