### ISSUE TITLE
Cannot access docs site

### ISSUE THREAD

**Issue by geofmureithi-zz** [Semantic-Org/Semantic-UI-React#1870]
### Steps
Visit http://react.semantic-ui.com/

### Expected Result
Be able to Browse through docs

### Actual Result
Nothing loads
app.676cd4b….js:50 Uncaught SyntaxError: Unexpected identifier
### Version
N/A
Browser: Chrome

### Testcase
N/A

**Comment by layershifter** [comment]
Docs site is working, however I had a same problem some time ago.

@levithomason it's not a first request from our users, I think the time has come for decisive changes. My proposals:
- remove usage of CDNs, we regularly have issues with ad blockers
- switch to cloudflare instead of rawgit, BTW [semantic-ui.com](http://semantic-ui.com) uses it.

**Comment by levithomason** [comment]
Let's start with replacing `rawgit` with `cdnjs` for consistency (most our CDN scripts are loaded from `cdnjs` right now).

**Comment by layershifter** [comment]
@levithomason can you clarify? How we can change `rawgit` to `cdnjs`? As I understand we serve only our bundle from it.

Also, we can't switch to `cdnjs` fully because it doesn't contain `prop-types` and actual version of `faker.js`.

**Comment by levithomason** [comment]
Whoops, moving far too quickly.  I double checked and you're correct, we only use `rawgit` for our own bundle.

I looked around at some competitors but they are just clones of rawgit.  I also checked S3 but it looks like we'll break the free tier limits for our usage, based on my estimates.

I'm now wondering if we simply should have `react.semantic-ui.com` redirect to `semantic-org.github.io/Semantic-UI-React`.  The URLs aren't pretty, however, we may have better up times and it is free without size/usage restrictions.

Given the infrequency and geographic limits of this bug, I'm just not sure if the migration is worth the added uptime.  It seems we'll gain maybe 1% or so?

**Comment by layershifter** [comment]
@levithomason I can't agree with you about frequency. There were really many issues about our site (#1373, #1383, #1404, #1412, #1566, #1590), they can be easily divided into two categories: CDN and `rawgit`. 

As I see we switched to `rawgit` in #786 because there were problems with access to the bundle on `gh-pages`. I tried to serve it now from github and there are no problems. Can you check?

**Comment by levithomason** [comment]
We never found out what the issue was with `gh-pages` originally.  I had assumed it was simply that they didn't guarantee uptime.

I'm OK switching back and seeing if it is any better.

**Comment by levithomason** [comment]
PR up.
