### ISSUE TITLE
Floating Label on Menu.Item is clipped

### ISSUE THREAD

**Issue by hubertguillemain** [Semantic-Org/Semantic-UI-React#1876]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
Open the sample from the documentation:
https://react.semantic-ui.com/maximize/label-example-floating
### Expected Result
The floating label is not clipped.
Would there be a workaround having the label floating on the content (Icon or text) instead of the menu.item container ?
### Actual Result
The floating label is clipped
### Version
0.71.1

**Comment by brianespinosa** [comment]
@hubertguillemain are you talking about the floating labels going outside of the viewport? That is because the Menu is in a container with no padding up against the top of the viewport. If you add padding to the body they are not actually clipped.

Those styles are CSS related from https://github.com/Semantic-Org/Semantic-UI but they are behaving as expected.

**Comment by layershifter** [comment]
This is a styling issue so it should be posted on https://github.com/Semantic-Org/Semantic-UI, but I don't think that it's a really issue. However, @brianespinosa is right you can `padding` to body or `margin` to `Menu`.
