### ISSUE TITLE
Invalid HTML from Header

### ISSUE THREAD

**Issue by technion** [Semantic-Org/Semantic-UI-React#1893]
### Steps

I created an item straight from your online guide:
```
  <Header as='h2'>
    <Icon name='plug' />
    <Header.Content>
      Uptime Guarantee
    </Header.Content>
  </Header>
```
### Expected Result
Valid HTML

### Actual Result
HTML output from [this documentation page](http://react.semantic-ui.com/elements/header#header-example-settings-icon) is:

```
<h2 class="ui header">
  <i aria-hidden="true" class="plug icon"></i>
  <div class="content">Uptime Guarantee</div>
</h2>
```

If you paste it into [the W3C checker](https://validator.w3.org) you get informed it isn't valid HTML:

    Element div not allowed as child of element h2 in this context. (Suppressing further errors from this subtree.)

I'm happy with the way everything renders, I'm just concerned about the effect of compliance on potential future issues.

### Version
0.71.1

### Testcase
As above

**Comment by layershifter** [comment]
Current markup is taken from [SUI](https://semantic-ui.com/elements/header.html#icon-headers) and I'm not sure that we really need to change it. However, you can easily override the default behaviour:

```jsx
<Header.Content as='span'>Uptime Guarantee</Header.Content>
```

**Comment by technion** [comment]
Thanks for that @layershifter !

**Comment by levithomason** [comment]
For more context here, the `Header` by default renders a `div` with the `ui header` class.  The default `Header.Content` is then valid as a `div`.

Since the `Header` is explicitly being set to render `as='h2'`, it does seem reasonable that the `Header.Content` element type may also need to be set explicitly to comply.

I wouldn't be opposed to a PR updating the docs to render content and subheaders `as='span'` in those cases.
