### ISSUE TITLE
fix(Grid): Stacking doesn't appear to do anything

### ISSUE THREAD

**Issue by ericis** [Semantic-Org/Semantic-UI-React#1932]
**Steps to Reproduce**
1. https://react.semantic-ui.com/collections/grid#grid-example-stackable
2. Resize the window
3. Also, try Chrome dev tools with "device toolbar" for testing mobile devices (e.g. "iPhone 5" in portrait mode)

**Expected**
The Grid columns should stack on top of one another when the window becomes smaller.

**Result**
Stacking seems to happen _occasionally_ for desktop dynamic window resize, but not reliably.

**Testcase**
Docs show the issue, use: https://react.semantic-ui.com/collections/grid#grid-example-stackable

**Comment by ericis** [comment]
Related issue: #1931 (has a screenshot)

**Comment by layershifter** [comment]
![image](https://user-images.githubusercontent.com/14183168/28979776-bef9035c-7953-11e7-8076-fe4690b139f9.png)

In fact, all works correctly, because columns are stacked. It works same as in [SUI](https://semantic-ui.com/collections/grid.html#stackable) docs.

However, our docs aren't mobile friendly, they even doesn't define [`viewport`](https://www.w3schools.com/css/css_rwd_viewport.asp). PRs that improves this are welcome.

**Comment by ericis** [comment]
@layershifter interesting. When using "Responsive" under Chrome emulated devices, it simply scales the 2 columns down and never stacks them. But, you're right... not using any emulation seems to work.

**Comment by ericis** [comment]
What happened to 2009's "mobile first"? ;)

**Comment by layershifter** [comment]
@ericis It doesn't work because `viewport` isn't defined in our docs, see my reply.

However, SUIR and SUIR are responsive and perfectly works on mobile devices. BTW there is PR that will facilitate complex responsive markups, #1872.

> What happened to 2009's "mobile first"? ;)

I have not seen any developer working with the mobile :smile This is not my priority, we have enough other tasks.
