### ISSUE TITLE
How do I prevent React from unloading the content of the previous tab?

### ISSUE THREAD

**Issue by itwy** [Semantic-Org/Semantic-UI-React#1947]
Say I have this in my app:
```
    import React from 'react'
    import { Tab } from 'semantic-ui-react'
    
    const panes = [
      { menuItem: 'Tab 1', render: () => <Tab.Pane>Tab 1 Content</Tab.Pane> },
      { menuItem: 'Tab 2', render: () => <Tab.Pane>Tab 2 Content</Tab.Pane> },
      { menuItem: 'Tab 3', render: () => <Tab.Pane>Tab 3 Content</Tab.Pane> },
    ]
    
    const TabExampleBasic = () => (
      <Tab panes={panes} />
    )
    
    export default TabExampleBasic
```
Whenever the tab is switched, it's being reloaded from scratch and I am losing all the changes inside the tab that I switched from if I return to it.

What is causing this and how I can keep the changed contents of tabs I switch from? Or this is a bug?

**Comment by brianespinosa** [comment]
@itwy If you are using React's local state for those components, you are going to lose state each time those components are removed and mounted back into the DOM. If you have application state that you are trying to maintain, you need to use some sort of application state container like Redux or Flow. I am just guessing this is your issue since I do not see what is going on inside your other components. This is not a bug. Local component state in React should not be used for maintaining overall application state.

**Comment by layershifter** [comment]
The problem is that the `render` function is called at each switch of `Tab`, duplicate #1877.

**Comment by rmirabelle** [comment]
I'm not sure I understand the solution, if one exists, for this.  Once a tab pane is rendered, I don't want it to re-render when switching to another tab and back again.  Is this possible without a ton of code?
