### ISSUE TITLE
style="pointer-events: all;" WHY?

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#2136]
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

You are emitting `"style="pointer-events: all;"` in *Option* and *Select*. Not sure why, but that is not the point. That would not be an issue but you seem to emit it in random places (attribute order).

This is a disaster for snapshot-based testing as tests will always fail.

Sorry for not filling out the form, but this is not really a bug, but correction of a feature request.

**Comment by levithomason** [comment]
>

>You are emitting "style="pointer-events: all;" everywhere. Not sure why, but that is not the point. That would not be an issue but you seem to emit it in random places.

"Everywhere" is quite the overstatement when there is one quite literally [one occurrence](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1218) in the codebase.  Though, I am not sure what "emitting" means in this context either.

Also, I do not understand what is "random" about this.  It is hard-coded into a single location, due to #791.

>This is a disaster for snapshot-based testing as tests will always fail.

There is a single use of `pointerEvent: 'all'` in DropdownItems.  It is rendered this way every time with no conditions, so it should not affect snapshot tests.

>Sorry for not filling out the form, but this is not really a bug, but correction of a feature request.

Please complete the form.  It is there so avoid the miscommunications we seem to be experiencing here.
