### ISSUE TITLE
MenuItem: containing a button of a chosen size does not work

### ISSUE THREAD

**Issue by valentinabojan** [Semantic-Org/Semantic-UI-React#2228]
**Steps to Reproduce**
I am trying to have a Menu.Item containing a 'tiny' Button.

**Expected**
The menu should contain a 'tiny' button.

**Result**
The MenuItem does not do this. The rendered button does not respect the chosen size (i.e. tiny, small, ..., massive).

**Testcase**
https://codepen.io/valentinabojan/pen/wrZKqy

**Comment by layershifter** [comment]
`Menu` styles override `Button`'s, as temporialy workaround you can use [`size`](https://react.semantic-ui.com/collections/menu#menu-example-size-mini) of `Menu`.

This issue is valid, but it's a CSS only, please post in on main repo: https://github.com/Semantic-Org/Semantic-UI Don't forget, to port your markup to HTML when you will create an issue.
