### ISSUE TITLE
Dropdown: when selecting one dropdown, the value of other dropdown becomes null. (after json response) 

### ISSUE THREAD

**Issue by RamyaChinnadurai** [Semantic-Org/Semantic-UI-React#2262]
#semantic-ui-search-dropdown #selection_null #bug #helpneed

**Comment by layershifter** [comment]
Please fill our issue template.

**Comment by RamyaChinnadurai** [comment]
Where is the issue template?

**Comment by layershifter** [comment]
https://raw.githubusercontent.com/Semantic-Org/Semantic-UI-React/master/.github/ISSUE_TEMPLATE.md

Testcase is required.

**Comment by airamrguez** [comment]
### Steps
Use the testcase below to reproduce these steps.

1. Add a user from the dropdown list.
2. Click on fetch.
3. Add other user.

### Expected Result
The selected items should be displayed in the dropdown box.

### Actual Result
Values are not shown in the dropdown box.
The same happens when you add a new element that doesn't come from the fetch result.
Dropdown component is receiving an array with all values but is not displaying them.

### Version
0.75.1

### Testcase

https://codesandbox.io/s/z25461w4pm

/cc @layershifter

**Comment by layershifter** [comment]
Your codepen doesn't contain any bug. To display values of multiple dropdown, `options` **should** contain it.

![0a3a72d34558bbca07b5383dec92349e](https://user-images.githubusercontent.com/14183168/32144324-d73113e2-bcbf-11e7-9053-c3313d7e6bd6.png)

**Comment by airamrguez** [comment]
@layershifter You're right! Aggregating the values in options make this work like a charm.
I've updated the codesandbox with that change: [https://codesandbox.io/s/z25461w4pm](https://codesandbox.io/s/z25461w4pm)

Thank you! 🙌
