### ISSUE TITLE
Visibility type fixed not implemented?

### ISSUE THREAD

**Issue by farebord** [Semantic-Org/Semantic-UI-React#2344]
```
        $('.main.menu').visibility({
            type: 'fixed',
            zIndex: 15
        });
```

I'm trying to make top menu fixed without any padding-top/margin-top on next element. With the code above I was able to fix the menu without needing extra css. (Especially when my menu has different height on every browser)

**Comment by layershifter** [comment]
This future will be never supported as it needs to make DOM manipulations.

However, it's easy to get this behavior, see [this example](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/app/Layouts/HomepageLayout.js). Instead of hiding `Menu`, just pass the state value of `Visibility` to the `fixed` prop of `Menu`.

**Comment by farebord** [comment]
I actually find a better solution for that:

JSX:
```
    <MainMenu fixed={true} />
    <MainMenu />
```

CSS:
```
    .mainMenu {
        border-rounded: 0 !important;
        visibility: hidden !important;
        margin: 0 !important;
    }
    .mainMenu.fixed {
        visibility: visible !important;
    }
```

Thanks!
