### ISSUE TITLE
Change Default value in <Search/>

### ISSUE THREAD

**Issue by wildfrontend** [Semantic-Org/Semantic-UI-React#2355]
two question:

## 1. How to Use <Search/> when it have a default value?
i have a default value :  value={this.state.product_card_detail}
and i change value use onSelectionChange={this.handleInputChange}
this.handleInputChange function look like this:

```
 //setState input value
 handleSearchValueChange = (e, { value }) => {
    this.setState({ value: e.target.value });
  };
```
it is not working , i don`t no why reason

i use Search ref from :[Semantic-UI-React Doc](https://react.semantic-ui.com/modules/search#search-example-standard)

this is my <Search/>
````
       <Search
                  name="value"
                  loading={isLoading}
                  onResultSelect={this.handleResultSelect}
                  onSearchChange={this.handleSearchChange}
                  results={results}
                  onSelectionChange={()=>this.handleInputChange}
                  value={this.state.product_card_detail}
         />
````
## 2. How to Change <Search> results dataFormat
result have the  static dataformat look like this
```
const source = _.times(5, () => ({
  title: faker.company.companyName(),
  description: faker.company.catchPhrase(),
  image: faker.internet.avatar(),
  price: faker.finance.amount(0, 100, 2, '$'),
}))
```
if i want to use default style
results title name must have to `title`,`description`,`image`,`price`
else result can`t show content 
can i change title name?
or i must be covert my data and set title as `title`,`description`,`image`,`price`?

**Comment by smallbrownbike** [comment]
@Luis-Chen 

**1.** So, when you call `handleSearchValueChange`, you're setting `this.state.value` to the new value when you want to be setting `this.state.product_card_detail` to the new value. Since the Search component's value prop is pulling from `this.state.product_card_detail` in your code, changing `this.state.value` won't give you the result you want. But making changes to `this.state.product_card_detail` will.

So maybe try updating `handleSearchValueChange` to this first:
```
handleSearchValueChange = (e, { value }) => {
  this.setState({ this.state.product_card_detail: e.target.value });
};
```

**2.** Check out the `resultRenderer` prop to  render a component that correlates with your specific data. Otherwise, `Search` will render a default component with image, price, title, and description as props.

**Comment by layershifter** [comment]
@smallbrownbike made a good answer. Closing.
