### ISSUE TITLE
event propagation

### ISSUE THREAD

**Issue by ggunia** [Semantic-Org/Semantic-UI-React#2400]
### Steps
1. There are modal trigger and window on page
2. Window has key press handler (closes on escape press)
3. Open modal
4. press Escape
5. Window closes

### Expected Result
Press event should not effect window. It would be nice to pass onKeyPress callback to modal so that i could stop event propagation

### Actual Result
Window closes

### Version
0.77.1

### Testcase
https://codesandbox.io/s/7mrzy0wj6

**Comment by layershifter** [comment]
I think that we don't to expose this callback, because:
- `Modal` uses [`eventStack`](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/src/lib/eventStack) to handle events, I've made a fork of your codepen, [see](https://codesandbox.io/s/ppw3zr0pkq) how to use it.
- `Portal` handles only click on Escape and passes event in `onClose` callback

--- 

Possible @levithomason has another opinion.

**Comment by base698** [comment]
What's the workaround?  I have an input in a Popup and every keypress on the input closes the popup.
