### ISSUE TITLE
verticalAlign not work when a Form in Table.Cell

### ISSUE THREAD

**Issue by Shoutmon** [Semantic-Org/Semantic-UI-React#2475]
### Steps
Use a `Form` in `Table.Cell`, the `verticalAlign` attribute of `Table.Row` cannot affect the `Form`.

### Expected Result
The `Form` and words in the same cell are supposed to be aligned in the `Table.Cell`
such as:
![image](https://user-images.githubusercontent.com/5486422/35608681-0c83ddbc-0695-11e8-8a61-326bd7c0c65f.png)

### Actual Result
Not vertical Aligned.
![image](https://user-images.githubusercontent.com/5486422/35608815-b6feb8d4-0695-11e8-8f8b-cf9619f37f85.png)

### Version
0.77.2

### Testcase
https://codesandbox.io/s/pw29qorx4x
The code above will run wrong result:
![image](https://user-images.githubusercontent.com/5486422/35610076-f5a9cd30-069a-11e8-86f1-55d331ce0907.png)

But paste it to https://react.semantic-ui.com/collections/table#table-example-fixed-line will get my result:
![image](https://user-images.githubusercontent.com/5486422/35610260-930aa996-069b-11e8-8f78-add65074a840.png)

**Comment by brianespinosa** [comment]
@Shoutmon your screenshots are of different viewport widths, so that is why they are rendering differently. Both `Table` and `Form` have responsive styles related to the viewport width.

If you do not want your `Form.Group` to stack on small screens the way it is in your screenshot, you need to use the `unstackable` prop on it. The `Table` component can also receive the same boolean prop which will prevent rows from stacking.

Regarding the vertical alignment inside of the form, the `Table` vertical alignment will not target those. It works the same way in SUI core css. If you want to add that behavior you'll have to add your own CSS for it, which is outside of the scope of this React based project.
