### ISSUE TITLE
Dropdown: option to disable "infinity" list

### ISSUE THREAD

**Issue by Unsfer** [Semantic-Org/Semantic-UI-React#2476]
Can you add some flag option to disable jumping to first/last item when selecting items by up and down arrow keys and reached the end of list.
It's a defauld behavior of an <select> html element and I want to reproduce it.

**Comment by levithomason** [comment]
I'm typically opposed to adding more branch logic to the Dropdown as it is quite massive and complicated as is.  However, I would accept a PR for this as I prefer we mimic HTML controls when possible.

How about `wrapSelection`?

**Comment by Unsfer** [comment]
Sure. Something like this?
`
<Dropdown 
        selection 
        options={friendOptions}
        wrapSelection
/>
`
And will it concern only Semantic-UI-React or pure js version too?

**Comment by levithomason** [comment]
Yep, that seems great to me.  It will affect only the React version.

**Comment by GCrispino** [comment]
Hello guys. I went ahead and tried to implement this. It was basically just change a couple of lines inside Dropdown component's moveSelectionBy() method, and it works. However, 4 Dropdown component's tests failed. If I understood that correctly, they all failed because the tests relied on the behavior of "infinite" selection, as @Unsfer named it. 

The failed tests were "× moves up on arrow up when open", "× scrolls the selected item into view", "× updates value on up arrow", "× keeps the selection within the range of remaining options". 

What should be done? Should the tests be updated to not rely on that behaviour? I'm not too experienced with unit testing in Javascript, but I think I can take care of this, with your help, if needed

EDIT: I just realized again that the feature has to be activated by a flag, which means that the tests would probably not fail, then. But I think that new tests should be added, right?
