### ISSUE TITLE
Dropdown - 'value' attribute must return the full object instead of just the value property 

### ISSUE THREAD

**Issue by neerajhiretual** [Semantic-Org/Semantic-UI-React#2519]
**Steps to Reproduce**
1. Try any example on semantic-ui-rect page for Dropdowns ([Link](https://react.semantic-ui.com/modules/dropdown#dropdown-example-remote))

**Expected**
The Dropdown selected value should return the selected options object and not just the value property.

**Result**
The Dropdown returns just the value property from the selected options object.

**Comment by brianespinosa** [comment]
Hello @neerajhiretual, [this is actually how the core SUI component works too](https://semantic-ui.com/modules/dropdown.html#/usage
), which is why SUIR does it the same way. If you need to get the entire object from your shorthand array, you can find the object based on the value of your selected property.
