### ISSUE TITLE
Progress Bar 0% not reflecting correctly

### ISSUE THREAD

**Issue by imoby** [Semantic-Org/Semantic-UI-React#2524]
Description: Progress bar currently defaults the progress indicator to show around 5-10% progress even if value is set to 0. 

https://codesandbox.io/s/5w1oq86yx4

### Steps
1. Create progress bar component
2. Set value to 0

### Expected Result
1. Should display a progress bar with nothing filled in the progress
### Actual Result
1. Displays progress bar with 10-15% filled
### Version
Latest

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/5w1oq86yx4

**Comment by brianespinosa** [comment]
Hi, @imoby thanks for taking the time to open this issue. The width of the completed progress actually has a `min-width` defined in the core SUI CSS. You can override this yourself if you want. Or you can compile your own SUI theme and override the property there. Either way, this is by design for the core SUI project. https://semantic-ui.com/modules/progress.html

**Comment by brianespinosa** [comment]
@imoby if you want to propose a change to the core styles you can also open an issue in that repository instead.
