### ISSUE TITLE
Reveal component couldn't be a controlled component

### ISSUE THREAD

**Issue by sharno** [Semantic-Org/Semantic-UI-React#2529]
### What's Expected
Reveal component https://react.semantic-ui.com/elements/reveal couldn't be controlled. The active prop just controls if hovering works or not. But no way to control the actual reveal of the hidden part. Not sure if that's intended but the component would be much more practical if it's possible to control the reveal programmatically

### Example
https://codesandbox.io/s/xjpjk43rnp

### Version
0.78.2

**Comment by brianespinosa** [comment]
@sharno I updated your Codesandbox example. You CAN actually control the Reveal element. The issue was how you were trying to do it. Your click function was on the container. 

https://codesandbox.io/s/q3m651vr16

**Comment by sharno** [comment]
Ok here's what I was trying to do to clarify my point:
A user has a card with hidden info and just a cover for this info hiding it. The user then needs to click on the cover to reveal the hidden info and further clicking shouldn't hide the info any more. (I don't want the info to be covered by hovering)

Controlling the reveal itself  is necessary for this use case and I thought the Reveal component should have this functionality which it seems it doesn't at the moment. Hope it's clear now

**Comment by brianespinosa** [comment]
@sharno I see now what the issue is. The problem is in the CSS. The `.active` and `:hover` selectors are grouped together with the transition. You'll have to separate them. That will require you either compiling your own SUI styles to separate them in your `reveal.overrides` file or you can include some CSS in your project to separate these, as I have quickly done in this codesandbox:

https://codesandbox.io/s/lrx50p9kn9

This is actually a CSS issue, not part of how the component itself works in the React end of things.

**Comment by sharno** [comment]
@brianespinosa I got it, didn't think it's in SUI styles. Thanks a lot, your solution seems to be great for my use case
