### ISSUE TITLE
Thoughts on adding displayName?

### ISSUE THREAD

**Issue by chrisbrainerd** [Semantic-Org/Semantic-UI-React#2532]
I noticed that none of the components in this library use displayName, which makes debugging a _whole_ lot easier. I'd be happy to go through and put up a PR, but I wanted to check with some of the maintainers if anyone has thoughts on the matter first, or if there was a specific reason it hadn't been done already (didn't see anything in the issue log though). 

For those not familiar, if you've been debugging your app and noticed in react devtools that Semantic-UI-React components show up as things like `<t>`, that's an autogenerated name as a result of the fact that the component didn't have a displayName set.

**Comment by levithomason** [comment]
Local development:

![image](https://user-images.githubusercontent.com/5067638/36356993-84091bba-14ad-11e8-989c-cc4fe3640315.png)

***

`displayName` is auto-generated during the build.  If you're seeing those types of names, that is because you are running a minified build.  It is a best practice to avoid minification during development as it is slow and destroys debugging capability as you mentioned.

We've gone through painstaking efforts to minimize the production bundle so I'm less inclined to ship display names to production.
