### ISSUE TITLE
Modal inside a Table

### ISSUE THREAD

**Issue by cinjon** [Semantic-Org/Semantic-UI-React#2563]
Hi, I'm using version 2.2.12 of semantic-ui-css and 0.77.2 of semantic-ui-react. I originally posted this in regular Semantic-UI because I thought it was more relevant there, but they said to post it here. 

I have a Modal inside a Table like the following. When I click the button to open, two issues arise:

1. It flickers a lot. Looking in the console, this seems to be caused by the scrolling attribute constantly being added and removed. If instead of putting it in the Table I put it outside of the Table, then the issue does not arise. (I actually want to use a Table here though)

2. When I test the above outside of the Table, it's really big. I was aiming for something like the first Modal example on https://react.semantic-ui.com/modules/modal, but instead the modal takes up the whole page and there is a lot of whitespace (because the image and text do not). As mentioned, this is not related to the Table concern.

```
class MyTable extends Component {
  render() {
    var isMe = this.props.isMe;

    return (
      <Table celled striped>
        <Table.Header>
          <Table.Row>
            <Table.HeaderCell textAlign="center">Details</Table.HeaderCell>
          </Table.Row>
        </Table.Header>

        {this.props.data.map((agent, i) => <MyTableRow data={data} defaultOpen={this.props.defaultOpen && i === this.props.data.length - 1} key={i} />)}
      </Table>
    )
  }
}

class MyTableRow extends Component {
  modal() {
    return (
      <Modal defaultOpen={this.props.defaultOpen} trigger={<Button>Click</Button>}>
        <Modal.Header>Detailed Instructions</Modal.Header>
        <Modal.Content image>
          <Image wrapped size='small' src={instructionsImg} />
          <Modal.Description>
            <p>{this.props.data.txt}</p>
          </Modal.Description>
        </Modal.Content>
      </Modal>
    );
  }

  render() {
    var row;
    var isMe = this.props.isMe;
    return (
      <Table.Body>
        <Table.Row>
          <Table.Cell collapsing>{this.modal()}</Table.Cell>
        </Table.Row>
      </Table.Body>
    );
  }
}

```

**Comment by layershifter** [comment]
Please add an example on codesandbox.

**Comment by sag1v** [comment]
@layershifter  [here you go](https://codesandbox.io/s/2zzrjk7qxp).
Although this is not inside a table like the OP mentioned, but the same behavior happening. I'm not sure but i think the reason is that the  `Button` inside `Modal.Actions` has a `floated` prop (without it it looks ok).
I've tried to mimic this bug with the regular `semantic-ui` but it seems to be ok.
To see this in action you should minimize the height of the screen so the bottom edge should touch the close button: 
![semantic err](https://user-images.githubusercontent.com/9153149/38815095-ceae9724-419b-11e8-9cbd-0c68354403bf.png)
