### ISSUE TITLE
Input: adding icon to Input in Form.Field with action and actionPosition in left makes the icon to misalign 

### ISSUE THREAD

**Issue by SanthoshDhandapani** [Semantic-Org/Semantic-UI-React#2588]
Steps to Reproduce
1) Use this page to reproduce: https://react.semantic-ui.com/elements/input#input-example-action
2) Paste the below code 

import React from 'react'
import { Form, Input, Button, Icon } from 'semantic-ui-react'

const InputExampleActionDropdown = () => (
  <Form.Field control={Input} icon='terminal' iconPosition='left' actionPosition='right'  
              action={<Button.Group basic>
                           <Button icon><Icon name={'plus'}/></Button>
                           <Button icon><Icon name={'minus'}/></Button>
                         </Button.Group>
                } />  
)
export default InputExampleActionDropdown

### Expected and actual result are Same
![semantic_ui_input_right_align](https://user-images.githubusercontent.com/10140204/36828012-21bbfc64-1d3d-11e8-931c-3b6ceedb2d45.jpg)

3) Now change the actionPosition='left'
### Expected Result
![expected_input](https://user-images.githubusercontent.com/10140204/36828027-347bb74a-1d3d-11e8-9e0a-6b14e0302411.jpg)
But ### Actual Result
![semantic_ui_input_misalign](https://user-images.githubusercontent.com/10140204/36828039-48f61684-1d3d-11e8-9efd-8d3b535d9e92.jpg)

**Comment by brianespinosa** [comment]
@SanthoshDhandapani You did not make a codesandbox example, so we can't easily test this... but form the screenshot you posted, you have `actionPosition` AND `buttonPosition` both set to `left`. This is how these elements will align based on the CSS. Both the buttons and the icon are on the left. What you are expecting (based on your screenshots) is not correct.

**Comment by levithomason** [comment]
There is also an `iconPosition` if you want the icon to be on the right.

**Comment by SanthoshDhandapani** [comment]
Hi @levithomason thanks for your time. I want the icon to be displayed on left inside the input box as shown in the picture that's why i opened this issue.

**Comment by brianespinosa** [comment]
@SanthoshDhandapani if you want both the icon and the buttons on the left, you are getting that according to your screenshot. They just occupy the same space. This is part of the way the styles work. It's not an issue with SUIR.

You MIGHT want to try using a `Label` on the input instead. A `Label` when combined with an input is intended to occupy space in the row, and not overlap the input content like the `Icon`.

Here's a Codepen to show you how you'd accomplish this with the subcomponent API. You won't be able to use the shorthand API to do this because of the order the `Label` component gets rendered. Also, this is not really how these components were ever intended to be combined with the core styles in SUIR so doing this will require some small CSS updates for it to look correct with removing the rounded corners on the `Button.Group`, etc. Styling is beyond the scope of SUIR within this repo. If you need help customizing styles you could take this codesandbox example and ask for some help on StackOverflow.

https://codesandbox.io/s/m5j7xo4jj9

**Comment by SanthoshDhandapani** [comment]
Hi @brianespinosa thanks for the brief 👍 and i achieved it by some alignments and styling customization. Thank you for the quick response :)
