### ISSUE TITLE
RFC: add `sideEffects: false` to package.json

### ISSUE THREAD

**Issue by djMax** [Semantic-Org/Semantic-UI-React#2589]
Webpack 4 now supports a `sideEffects: false` value in package.json which indicates to the tree shaking algorithms that there are no side effects from loading modules. This is fairly important to semantic-ui-react because defaultProps are essentially side effects as far as babel is concerned. BUT, if that's the only side effects semantic-ui-react uses, since they're only relevant to the component itself, they should be safe to shake out. Not a great explanation, but the TL:DR; is that we should add sideEffects: false to the package. Agreed? I can make a PR if that's desired.

https://github.com/webpack/webpack/tree/master/examples/side-effects

**Comment by layershifter** [comment]
@djMax Thanks for suggestion, it's one of the most expected things. It will allow to omit `babel-plugin-lodash`.

However it should be tested before we will add this param to `package.json`.

**Comment by goenning** [comment]
I would be happy to help test this whenever available!

**Comment by brianespinosa** [comment]
@goenning PRs are welcome if you'd like to submit something and help us start the testing process. 🎉

**Comment by levithomason** [comment]
Yes, please!  I've been wanting to add an analytics build step to our PRs as well.  I want to see at least bundle size in something like a markdown file so we can easily see diffs in the PRs.  We could track full library size as well each component.

I did this last year in #1233 and tracked [doc site bundle stats](https://github.com/Semantic-Org/Semantic-UI-React/blob/3aa72bc76aac05c526e2b14a6ed4687995cd11af/stats-app.md) as well as [library stats](https://github.com/Semantic-Org/Semantic-UI-React/blob/3aa72bc76aac05c526e2b14a6ed4687995cd11af/stats-library.md) in well formatted markdown.  Have a look at those to see what I'm after here.

IIRC the final engineering hurdle here was figuring out how to generate these so that PRs include them.  Looking back, I think I'd just use [`husky`](https://www.npmjs.com/package/husky) to fire this on `pre-push`.  This way, PRs are updated only when pushing to the remote.

Thoughts?

**Comment by layershifter** [comment]
### Webpack 4 in `production` mode, without `sideEffects`

![image](https://user-images.githubusercontent.com/14183168/41807278-5dd135a6-76d5-11e8-963c-8c018f41f52a.png)

### Webpack 4 in `production` mode, with `sideEffects`

![image](https://user-images.githubusercontent.com/14183168/41807326-30dfdb8c-76d6-11e8-8c7c-87cf03155f05.png)

---

### Tested JSX

```jsx
import React from 'react'
import { Button, Ref } from 'semantic-ui-react'

const App = () => (
  <Ref innerRef={(n) => console.log(n)}>
    <Button>Example</Button>
  </Ref>
)
```

It's a cool result 👍

**Comment by layershifter** [comment]
Option was added in #2941.
