### ISSUE TITLE
Modal.Header with Icon creates wrong result

### ISSUE THREAD

**Issue by SaphuA** [Semantic-Org/Semantic-UI-React#2590]
### Steps
```
<Modal open={true}>
    <Modal.Header icon="lab" content="Modal" />
    <Modal.Content />
</Modal>
```

### Expected Result
```
<div class="ui header">
    <i class="lab icon"></i>
    <div class="content">Modal</div>
</div>
```

### Actual Result
```
// NOTE: icon="lab"
<div icon="lab" class="header">Modal</div>
```

### Version
0.78.3

### Testcase
https://codepen.io/anon/pen/GQeeKE

**Comment by brianespinosa** [comment]
Hello, @SaphuA 

The `Modal.Header` component does not have an `icon` prop if you [take a look at the docs in `Modal`](https://react.semantic-ui.com/modules/modal).

The markup being returned is correct for SUI and is as expected. What you are expecting for markup is invalid SUI markup though technically it will work because of the `header` class. If you [take a look at the SUI core docs for Modal](https://semantic-ui.com/modules/modal.html#/definition), the modal itself has three types of direct children, all without the `ui` class. These are `header`, `content`, and `actions`.

If you want to get the icon you are looking for, don't use `Modal.Header`. Use `Header` instead. Not all of the additional `props` of the `Header` component will work correctly in this use case, but the `icon` prop will.

```
<Modal open={true}>
    <Header icon="lab" content="Modal" />
    <Modal.Content />
</Modal>
```
