### ISSUE TITLE
Dropdown (non-simple) inside Menu with newly introduced 'direction' prop will always stay open

### ISSUE THREAD

**Issue by gregor-mueller** [Semantic-Org/Semantic-UI-React#2620]
### Steps

1. Have a Dropdown inside a Menu
2. Add the `direction` prop to the Dropdown
3. **Don't** add the `simple` prop

### Expected Result
Dropdown only opens when clicked (focused)

### Actual Result
Dropdown will always stay open

### Version
0.78.3

### Testcase
https://codesandbox.io/s/4zkyvyl1l7

### Video
I created a gif showing the behavior on the example page (https://react.semantic-ui.com/modules/dropdown#dropdown-example-menu-direction);
![2018-03-08_10-17-09](https://user-images.githubusercontent.com/28727932/37143244-dc450c88-22ba-11e8-880b-084b034b248e.gif)

**Comment by brianespinosa** [comment]
@ffgregormueller Thanks for opening the report. The issue is that you are using the `direction='right'` prop on your `Dropdown` component. If you remove that it will work. The `direction` prop is not needed for Dropdown items in a menu. If the Dropdown is part of a nested menu that is aligned right, the styles in SUI CSS already account for the alignment. Basically that prop is adding a `.right` class to the `Dropdown.Menu` which you don't want in this case as there are `display: flex;` styles associated with it which makes it show up.

**Comment by gregor-mueller** [comment]
@brianespinosa 

So I updated the example to show you where my issue is:
https://codesandbox.io/s/4zkyvyl1l7
I added a `Dropdown` with children as well as one with the `options` short tag.
Both will break even without the `widths` prop in the menu and without the 'other stuff' part that is just there to show that the options will be cut out to the right (preview window width of about 650).

Edit: Here is another gif:

![2018-03-09_11-48-47](https://user-images.githubusercontent.com/28727932/37204001-ea140cbc-238f-11e8-9d80-2baf2451d01d.gif)

**Comment by brianespinosa** [comment]
@ffgregormueller This is a separate issue from the one you reported. In the future, please open new issues for new bug reports.

At present, dropdowns that detect which direction they should open based on the most left/right space are still not supported (see #720).

In your particular UI case you could use the subcomponent API to set `style={{right: 0, left: "auto"}}` on your `Dropdown.Menu` if you wanted it to go the other direction. I wouldn't do it this way personally because that would require knowing the keys, etc. Instead I would add some custom CSS that targets `:last-of-type` on the final `Dropdown` in your menu and have the last one always open left.
