### ISSUE TITLE
fix(Dropdown): Search Dropdown (example with Languages)

### ISSUE THREAD

**Issue by g-wozniak** [Semantic-Org/Semantic-UI-React#2628]
**Steps to Reproduce**
1. Type manually a text in a search box

**Expected**
Searched phrase is visible in real-time.

**Result**
Dropdown shows possible results but there is no option to preview and see what was typed in.

Reproduced in Chrome 64.0.3282.186, Firefox 58.0.2

**Comment by brianespinosa** [comment]
@gregiolo please complete the entire bug report, which includes a minimum codesandbox example.

**Comment by g-wozniak** [comment]
The code and component that behaves incorrectly is on [documentation page](https://react.semantic-ui.com/modules/search) (section as in the post title) so I decided to not copy/paste it from the documentation as it is. 

Currently I can see the whole doc page there is broken along with examples.

![image](https://user-images.githubusercontent.com/26707212/37415431-4f512de6-27a3-11e8-8b69-332c6db06e2c.png)

**Comment by brianespinosa** [comment]
@gregiolo in your screenshot no results show because nothing has been typed. Here you can see in the very first example, I have typed "th" and that text is showing in the search box, and the matching result is showing below.
![image](https://user-images.githubusercontent.com/1161781/37418454-7d3472d8-276f-11e8-8007-88e4cffc7b10.png)

Here I have typed text that does not match any results. The searched phrase is still showing in the search box and the result is showing below... which is telling me I have no matches.
![image](https://user-images.githubusercontent.com/1161781/37418534-b5761746-276f-11e8-93bc-33a2f36f0d3b.png)

Additionally, [this is exactly how SUI core search works too if you look at those examples](https://semantic-ui.com/modules/search.html).

> Result
> Dropdown shows possible results but there is no option to preview and see what was typed in.

Based on both screenshots above, you see what is typed in the search box on all of them.
