### ISSUE TITLE
CSS Issue -> Modal window render out of screen

### ISSUE THREAD

**Issue by SajagTiwari** [Semantic-Org/Semantic-UI-React#2697]
the css comes with the CDN link
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.12/semantic.min.css"></link>

and the css that come with semantic-ui-css package are different.
I am using the css come with package that create problem with modal window.
half of the modal window render out of the winow screen.
![snapshot](https://user-images.githubusercontent.com/13046829/38185497-f37bbc3e-366b-11e8-9f6b-ecf39ce3c514.jpg)

**Comment by SajagTiwari** [comment]
this is about the version  Semantic UI 2.2.12

**Comment by ekrokowski** [comment]
This happens because the newer Version of Semantic-ui-css doesn't use the CSS `position: fixed; top: 50%; left: 50%;` anymore. Semantic-UI-React however still applies `margin-top: -(half-height)px` to the `.ui.modal`-element. 

This happens when using Semantic-UI-CSS Version `2.3.X`. Forcing version `2.2.12` fixes this problem for now.

**Comment by brianespinosa** [comment]
Duplicate of #2550
