### ISSUE TITLE
fix(Progress): Indicating props doesn't work with Progress

### ISSUE THREAD

**Issue by durgeshrkumari** [Semantic-Org/Semantic-UI-React#2713]
**Steps to Reproduce**
```
 <Progress percent={99} size="tiny" color="orange" indicating>
     <span>Generating report...</span>
 </Progress>
```
If you use above code you won't see the indicating animation on the progress. However, when I add inverted then the indicating animation works.
```
 <Progress percent={99} size="tiny" color="orange" indicating inverted>
     <span>Generating report...</span>
 </Progress>
```

**Expected**
Indicating props should work without inverted.

Otherwise, fork this to get started: http://codepen.io/levithomason/pen/ZpBaJX

**Comment by brianespinosa** [comment]
@SageDurgesh could you please create a Codesandbox or Codepen example of the issue you are experiencing? I am seeing the animation just fine (even though it is SUPER small on the tiny size). Also, you don't need to define the color prop here since the indicating Progress component changes colors as the bar progresses which override any color you have defined.

**Comment by durgeshrkumari** [comment]
aah maybe that's my problem- the color. I am trying to use it as an infinite progress bar so, wanted to have it  as one color. But I think that's what is creating my problem. If I remove the color it works fine. But I will close this issue. Thanks for the quick response.
