### ISSUE TITLE
Closing a nested modal that has a canvas element closes the parent modal as well

### ISSUE THREAD

**Issue by sharno** [Semantic-Org/Semantic-UI-React#2716]
### Steps
1. make nested modals with a button to close the inner one
2. put a `canvas` element in the child modal
3. clicking the nested modal's close button closes the parent modal as well

### Expected Result
closing the nested modal shouldn't close the parent modal

### Version
0.79.1

### Testcase
https://codesandbox.io/s/znx91x17q4

**Comment by levithomason** [comment]
The `<canvas>` is unrelated to the issue.  The inner Modal is closing because it is a child of the outer modal.  You're closing the parent modal and expecting it's child to stay mounted.  The modals must not have a parent/child relationship.

After fixing this, I also see a `handleClose` on the first modal.  This is unnecessary as you are controlling the open state directly.  There is no need to toggle the `open` state _and_ handle the close event.  Instead, it is enough to toggle the close prop only via state.

Once both issues are fixed, all is well:

https://codesandbox.io/s/l9lxyqxm4l

**Comment by levithomason** [comment]
I see. Thank you for pushing the issue a bit as I was not only wrong about the canvas but also about the order of the state updates.  Apologies!

It seems any other element besides a canvas (e.g. `<p />`) does not cause this problem.  Moreover, placing the canvas anywhere else, besides inside the second modal, also does not cause this problem.

This smells like a React issue but I'd really like to know _why_ the `<canvas />` element is magical and why it must be a child of the second modal.  This just seems so strange.

**Comment by sharno** [comment]
Thanks for taking a second look at it. Really appreciate your effort

**Comment by sharno** [comment]
Hope this wouldn't get closed

**Comment by eclewlow** [comment]
It seems the inner modal closes the outer modal because of the size of the inner modal.

If the inner modal's close button is outside of the boundaries of the outer modal, the click will propagate through the close button (inner modal) to the outside boundary of the outer modal, thus closing the outer modal.

For example, if I remove the canvas element and just add padding, the issue still occurs.

(https://codesandbox.io/s/pmkql26kp7)

**Comment by eclewlow** [comment]
You can add `closeOnDimmerClick={false}` on the outer modal, but then it won't close unless you have a button to close it.
Semantic-UI-React should really consume the inner modal click event and not let it propagate to the outer modal.

**Comment by eclewlow** [comment]
I guess it's called 'event bubbling'

**Comment by eclewlow** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/issues/2493

**Comment by eclewlow** [comment]
Here's a temporary workaround.

https://codesandbox.io/s/lxq6169kk9

**Comment by layershifter** [comment]
https://codesandbox.io/s/my8lw043op

Tested with latest SUIR and React, works as it should 🌟
