### ISSUE TITLE
RFC: Update New Issue Template

### ISSUE THREAD

**Issue by brianespinosa** [Semantic-Org/Semantic-UI-React#2719]
I think it might be worth updating our new issue template to more closely resemble the [new issue template for Atom](https://github.com/atom/atom/issues/new). Asking users to check the box when they have fulfilled the requirements will let us know right away if prerequisites have been fulfilled when we look at the list of new issues, [as seen here](https://github.com/atom/atom/issues).

I am not sure if they also have a bot that pokes the author if they have not done this, which would save actual humans time when working on new issues, but that might be something we could add later if we went with a pattern like this.

Thoughts?

**Comment by levithomason** [comment]
Better ways of filtering issues are definitely preferred.  I've been through many updates of the template and am happy to try more.

One suggestion, put the instructions in `<>` instead of `[]` so that they aren't rendered 😉 Users often leave the extra text in the template.

Also, we're using already Probot and they may also have an app (think plugin) for verifying issues.  See https://probot.github.io/apps.

Want to take a stab?

**Comment by brianespinosa** [comment]
Yeah, I'll take a look at this. That is even better not having the items rendered but still having a checkbox. Haven't seen Probot but I will take a look and put together a proposal. Probably a week or so out.

**Comment by levithomason** [comment]
Try our new issues :) #2763
