### ISSUE TITLE
Close button on the modal doesn't show in the viewport for certain window sizes

### ISSUE THREAD

**Issue by robespmun** [Semantic-Org/Semantic-UI-React#2728]
### Steps

Use a 'large' size Modal and resize the window. 

### Expected Result

The close button should be shown inside or outside the modal depending on the size of the window, but never outside of the viewport.

### Actual Result

There are some window sizes that make the close icon display outside of the modal but *not* inside the viewport.

### Version
0.77.2

### Testcase
https://codesandbox.io/s/jvw9rzmm5y

Play around with the width between 1040 and 990.

**Comment by brianespinosa** [comment]
@robespmun this looks like it is an issue with the CSS in SUI Core. I believe this is fixed in the latest version but we don't have our latest compatibility release to work with the latest yet.

**Comment by brianespinosa** [comment]
Likely resolved with #2550

**Comment by levithomason** [comment]
Confirming the provided codesandbox is using https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.css.

However, it seems this issue only appears on CodeSandbox due to their injecting `style#detectElementResize`.  This style element contains styling that breaks SUI's container.  That is unfortunate.  Remove it manually from the `head` and you'll see it works as advertised.

Here is the working example in our docs as well:

https://react.semantic-ui.com/modules/modal#modal-example-close-icon

**Comment by levithomason** [comment]
Womp.  Our large size is also broken.  This is a then a CSS bug as noted by @brianespinosa.  Unforunately, it needs to be posted over at https://github.com/Semantic-Org/Semantic-UI as we don't control the CSS here, yet (#2710).
