### ISSUE TITLE
Menu inverted pointing secondary  - returns weird results

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-React#2741]
### Steps
When having `<Menu inverted pointing secondary />`
### Expected Result
expect it to show underline under active item
### Actual Result
menu is white, not inverted and items are not visible
### Version
0.79.1

### Testcase
https://codesandbox.io/s/pjj25r8wmq

**Comment by levithomason** [comment]
Inverted components are only appropriate in on an inverted background, such as an inverted Segment:

https://codesandbox.io/s/3x6j2znl45

![image](https://user-images.githubusercontent.com/5067638/39341682-288ffbe4-4989-11e8-9e43-ff9b1f03a5d0.png)

**Comment by levithomason** [comment]
Note, this is because secondary background menus do not have backgrounds.  The "secondary" style in the default theme helps elements blend into the background by being less pronounced.  You can opt to change this in your theme if you like, instead of adding an inverted background element as I did.

**Comment by avalanche1** [comment]
> Inverted components are only appropriate in on an inverted background, such as an inverted Segment:

Ok, but why do I have to specify `inverted` for the second time on the menu? If the segment is already inverted? I think `inverted` property of the menu is absolutely redundant. It should always get it from the parents or not at all.

And secondly I've checked your sandbox - but is that case described in the docs? Maybe I've overlooked it but I don't remember a mentoin of my case in the docs.

**Comment by levithomason** [comment]
You're not missing any menu docs.  There is no example of an `inverted secondary pointing` menu.  I think there are too many possible combinations of props to list all permutations.

However, you can see other inverted components need an inverted background such as the `inverted` button.  Otherwise, they'd be white on white.

https://react.semantic-ui.com/elements/button#button-example-inverted

>If the segment is already inverted? I think inverted property of the menu is absolutely redundant.

I can see your point.  Consider also the number of CSS selectors that would have to be generated to automatically invert children if a parent were inverted.  The combinatorial cases would bloat the CSS file considerably.  You would need to define a selector and inverted style for every component that could possibly be a child of an inverted parent.

Plus, it is possible to have a normal segment within an inverted segment.  You wouldn't then want components within the normal segment to also be inverted, so you'd again have to write nested overrides for `.inverted :not(.inverted)` cases. This continues as there is no limit to how many levels of nesting could be achieved.

The conclusion is that the file would be monstrous and outweighs the benefit of explicitly marking inverted components as inverted.

***

Sidenote, as we move to CSS in JS #2710 we have made it a goal to remove as much parent / child coupling as possible.  This means things will only become more explicit than they are today.  Parents and children will have limited awareness and limited effect on each other's styles.  This is to increase portability and expected behavior.

**Comment by avalanche1** [comment]
I see your point. I am all for css in js approach.
Still I propose this: have Menu automatically look for `inverted` property passed down from a parent. If it's there - Menu sd automatically invert  itself. And if the dev wants to have a normal Menu on an inverted parent - he can pass `inverted: false`.
Don't see why it shouldnt work?

**Comment by levithomason** [comment]
Indeed.  I understand the proposal and both options.  I'm not 100% sure of either direction yet.  I am still leaning hard toward parents not affecting the styling of their children.  However, `inverted` is one of those properties that I'm likely in agreement with you on. Despite it not being implemented in CSS today, we can achieve it in React via theming and context.

### Case for isolation

When we design modular code we adhere to principles like the law of demeter, limited awareness, encapsulation, and black boxes. In functional programming, we employ pure functions, avoid side effects, and never reach outside scope.  These principles (and their friends) make our code portable, reusable, easy to reason about, easy to test, and most importantly they make systems that are predictable and maintainable.

It seems to me that when it comes to styling we too easily throw these principles out.  We are quick to entangle the styling of components with the implementation details of their potential neighbors. 

The output of a function ought to be owned by the function alone.  I see components as functions and style as output. The style of a component then ought to be owned by that component alone.  A component should provide arguments for changing the style.  Just as a good function provides arguments for changing its output.

Consider this analogy of an `inverted` Segment with a Menu inside:

```jsx
const menu = () => {
  return inverted ? 'inverted menu' : 'menu'
}

const segment = () => {
  const inverted = true

  return Menu()
}
```

What's wrong?  The `menu()` is relying on an out of scope variable to exist.  Most PR reviewers would call this out for correction.  Why?  First, `inverted` is not defined in the menu's scope and will throw.  OK, let's strictly fix the undefined issue:

```jsx
const menu = () => {
  return typeof inverted === 'undefined' ? 'menu' : 'inverted menu'
}

const segment = () => {
  const inverted = true

  return Menu()
}
```

Still, PR reviewers would likely call this out.  Why?  It is not pure!  The output is not predictable nor consistent.  Depending on where you call this function, it will behave differently even though you used the exact same arguments.  This may seem helpful in an isolated case, but a system built on these kinds of blocks will be unreasonable chaos.

In order to be pure, the menu must be honest about it's dependencies and own the value it is referencing.  It needs to accept it as an argument:

```jsx
const menu = (inverted = false) => {
  return inverted ? 'inverted menu' : 'menu'
}

const segment = () => {
  const inverted = true

  return Menu(inverted)
}
```

Cool, now this is testable, reusable, moveable, predictable, consistent, intuitive, and simple.   Most PR reviewers would accept this code. I hope the correlation is clear, but here it is in JSX just in case:

```jsx
<Segment inverted>
  <Menu />
</Segment>
```

Ask ourselves, should the Menu be inverted?  I'm thinking no.  Segment should not know about Menu and vice versa.  Segment should not be allowed to reach into implementation details (styling) of Menu and change them.  Segment and Menu both should be pure, rending the exact same UI when given the same props, no matter when or where they are rendered.

We have a real problem currently with how many child component styles are completely changed when placed in the context of a parent.  Menu's do this to Labels when used in a Menu Item.  The Label props are largely ignored and the Menu overrides their style.  This is not good and something we will get away from.

### Case for cascading

There are limited scenarios when globals are acceptable, such as base theme information.  It is clear that some aspects of styling should not be global or cascade, like borders and shadows.  This is harder to answer for some aspects of styling, like sizing.

My counter thought to the isolation argument is that the concept of `inverted` may in fact be nothing more than a `dark` theme.  Theme is an acceptable global and should also be configurable at any point in the tree.  We can imagine changing the theme from `light` to `dark` for a given branch in the tree and expecting all components in that branch to take on the theme.

In the CSS in JS conversion, it may be that `inverted` goes away and we instead embrace it as a theme variant.  It is also valid that we keep the concept of `inverted` and treat it as a theme parameter, passing it through context.

**Comment by avalanche1** [comment]
Thank you for the comprehensive write up. Deserves a blog post IMO.

As far as functional programming goes - I'm all into it myself and purity in styling is a very-nice-to-have; but I'm not sure that in case of SUI that is achievable - the components are WAY TOO interdependent and it will be a really tough job to make them pure and isolated. Anyway, I support the effort wholeheartedly.

> Segment should not know about Menu and vice versa.  

This goes against the foundations of SUI IMO.

Yet all of this brings us back to where we started: 
inverted menu must be inverted no matter the context; and this is exactly what I was expecting before opening this issue.
This also makes your answer not valid:

> Inverted components are only appropriate in on an inverted background, such as an inverted Segment

And finally

> This is not good and something we will get away from.

When, where and how? In a different project? Once again, SUI components do not go hand in hand with the notion of purity - quite the opposite.

**Comment by avalanche1** [comment]
I think this discussion has deviated quite a bit from the original issue.
I hope that you compile your posts here into an article, really - so that much more ppl can benefint from the insights 😄

**Comment by levithomason** [comment]
Agreed and agreed 😄 I often consider doing so.

**Comment by avalanche1** [comment]
Then stop considering and start doing! :wink:
I'm sure you're in for a warm reception.
