### ISSUE TITLE
Update Portal to use ReactDOM.createPortal

### ISSUE THREAD

**Issue by geoff-wasilwa** [Semantic-Org/Semantic-UI-React#2746]
### Steps
Mount a react component that has a modal form using enzyme and try searching for children nodes.

### Expected Result
A call to `wrapper.find(<content>)` should return content with specified selector.

### Actual Result
It's not possible to get modal content using enzyme wrapper.

### Version
0.79.1

**Comment by levithomason** [comment]
Agreed.  We'll need to plan release timing.  This will be part of a breaking change update that will require users to use [React >=16](https://reactjs.org/blog/2017/09/26/react-v16.0.html#portals) so they have the API.

There are other React 16 updates such as returning arrays and strings.  This can really help us in some areas.  Our Accordion has ugly markup and code due to not being able to return arrays.

At any rate, let's batch these changes into a major update.  PRs welcome!

**Comment by levithomason** [comment]
### Workaround

In the meantime, if you have to mount and test Modal code you can find the elements in the DOM using conventional DOM APIs.  This is in fact how our [Moda tests](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/test/specs/modules/Modal/Modal-test.js) have worked for years in the absence of a first-class Portal API.

**Comment by geoff-wasilwa** [comment]
Thanks @levithomason, I actually ended up using [this](https://github.com/airbnb/enzyme/issues/252#issuecomment-266125422) suggestion.

**Comment by layershifter** [comment]
Was fixed in #2755.
