### ISSUE TITLE
The loader is looking weird

### ISSUE THREAD

**Issue by AmitJoki** [Semantic-Org/Semantic-UI-React#2772]
## Bug Report
Ubuntu 16.04 Chrome Latest.

### Steps
Open the loader docs and you can see that loader is having a weird animation. The loader is not rotating, instead, it is moving linearly.

### Expected Result
Loader rotating in circular way.

### Actual Result
It is moving linearly.

### Version
0.80

### Testcase
It is clearly visible in the Loader docs itself.

**Comment by levithomason** [comment]
I cannot reproduce this in Chrome or Firefox.  Which version of Chrome has this issue?  Also, could you post a gif or screen recording?

**Comment by layershifter** [comment]
Works fine at my work and home PCs.

**Comment by levithomason** [comment]
If we can get a successful repro, we'll gladly reopen and investigate.

**Comment by AmitJoki** [comment]
@layershifter @levithomason I've attached a screencast with the chrome version at the end of the screencast - https://www.useloom.com/share/31618a19fe9f4a29ab594a5b3cfc4fad

**Comment by brianespinosa** [comment]
@AmitJoki Yeah, that was as I suspected. The issue is something in the CSS animation, and not part of SUIR. You should open a bug on SUI core to take a look at this in the CSS. It looks like there is something going on with the transform-origin property since the animation is still happening but it's off.

My initial guess is that you might have a chrome extension enabled that is injecting some styles into your DOM that are conflicting with the SUI class names. I'd try disabling ALL chrome extensions and see if this still happens for you.
