### ISSUE TITLE
Sticky content taller than center content causes issues

### ISSUE THREAD

**Issue by james-ff** [Semantic-Org/Semantic-UI-React#2773]
### Steps
- Go to: https://react.semantic-ui.com/modules/sticky#sticky-example-oversized
- Adjust the Segment code such that there are less segments, e.g:
`<Segment>{_.times(5, i => <Placeholder key={i} />)}`

### Expected Result
Unsure, but:
- Space allocated around the center content in proportion to how much taller the sticky content is?
- Scrolling of the sticky closely tied to the smaller center content size?

### Actual Result
The left sticky, which is taller than the center content, does not render very well

### Version
0.80.0

### Testcase
https://react.semantic-ui.com/modules/sticky#sticky-example-oversized

**Comment by levithomason** [comment]
### Sticking
I think the Sticky behavior is correct here, however, this markup is not a valid use case.  Showing the index of the left rail items makes it more clear:

![http://g.recordit.co/6UTkd1fMvw.gif](http://g.recordit.co/6UTkd1fMvw.gif)

### Scrolling

The example is showing how sticky can handle content larger than the _viewport_.  When reducing the number of placeholder images, the sticky content is now larger than its _parent container_ (context). That is a use case for a scroll container rather than sticky content.

Scrolling passed the sticky content makes its bottom stick to the bottom of the context, hence 11 jumping to the bottom.  When scrolling up again, the top of the sticky content sticks to the to of the context.  I believe this is this is the correct behavior for sticky.  The bad alignment at the bottom is due to overflow.

This type of content is better suited for a simple scroll container to handle the overflow:

```diff
-<Rail position='left'>
-  <Sticky context={contextRef}>
+<Rail position='left' style={{ overflowY: 'auto' }}>
    <Item.Group divided>
      ...
    </Item.Group>
-  </Sticky>
</Rail>
```

![http://g.recordit.co/rF3kwVhUlL.gif](http://g.recordit.co/rF3kwVhUlL.gif)
