### ISSUE TITLE
issue loading css

### ISSUE THREAD

**Issue by hashir-uh** [Semantic-Org/Semantic-UI-React#2824]
### Steps
i have used create-react-app package.
i have run npm run eject in the terminal to add my custom css styles to the components.
Now got an below error
./node_modules/semantic-ui-css/semantic.min.css
Module not found: Can't resolve 'themes/default/assets/fonts/brand-icons.eot' in 'C:\Users\Hashir\Desktop\Masjid One\masjidone\node_modules\semantic-ui-css'

and also the styles in the component cannot be seen.
ended up  causing an error.

Is it possible to use semantic ui react css in npm run ejected project

### Expected Result
Expecting a solution so that i can start using both custom css and semantic ui components

### Actual Result
./node_modules/semantic-ui-css/semantic.min.css
Module not found: Can't resolve 'themes/default/assets/fonts/brand-icons.eot' in 'C:\Users\Hashir\Desktop\Masjid One\masjidone\node_modules\semantic-ui-css'

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
This issue isn't related to SUIR, please use StackOverflow for questions with a wepback config.

There is also the ready to use example with Webpack configured with the ejected CRA, https://github.com/Semantic-Org/Semantic-UI-React/tree/master/examples/webpack3

**Comment by mbutsykin** [comment]
I know, comment is a bit outdated. But today this issue happened to me aswell and i had to spend like an hour to figure out what happened =)

The issue is happening when you are trying to [enable css modules](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/examples/webpack3/config/webpack.config.common.js#L130) for SUI.
Make sure you restricted usage of css only for [your's internal sources](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/examples/webpack3/config/webpack.config.common.js#L114)
