### ISSUE TITLE
Portal: recent change breaks in IE11

### ISSUE THREAD

**Issue by traverse** [Semantic-Org/Semantic-UI-React#2886]
## Bug Report

A change introduced in #2657 to the portal component causes an error in IE11 when trying to open anything using a portal.

The change: 
https://github.com/Semantic-Org/Semantic-UI-React/blob/500df9ae073dc99b3425fda89fe6b3a3d8f56760/src/addons/Portal/Portal.js#L355

### Steps
Use anything with a portal in IE11 and try to open it.

### Expected Result
Should open the portal.

### Actual Result
Throws the following error:
```
SCRIPT5045: Assignment to read-only properties is not allowed in strict mode
```
Which points to the changed line.

### Version
`semantic-ui-react@0.81.1`

**Comment by layershifter** [comment]
Will be fixed in #2880.

**Comment by jbraithwaite** [comment]
Hi @layershifter, thanks for addressing this bug. Is there a timeline for when this will be released?

**Comment by mgandley** [comment]
@levithomason @layershifter per https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style you could probably fix this with one line of code by changing this `this.rootNode.style = style || '' ` to this `this.rootNode.cssText = style || '' ` or this `this.rootNode.setAttribute('style', style || '')`

Not sure how much more work is needed for #2880.  Considering this bug is affecting all portals for a major browser, this quick fix might be worth doing if it's going to be more than a few more days.

**Comment by mihai-dinculescu** [comment]
I support an individual release of the fix. Currently my team is stuck with using version 0.80.2. Even if #2880 comes soon, it looks like a risky upgrade to do right after the release.

**Comment by layershifter** [comment]
@mgandley @mihai-dinculescu Feel free to submit PR 👍

**Comment by mgandley** [comment]
Done!
