### ISSUE TITLE
React Router Link only works in Dropdown.Item.

### ISSUE THREAD

**Issue by casperOne** [Semantic-Org/Semantic-UI-React#2937]
### Steps
- Go to test case
- Click on "Login" to the right, or the Login link (in blue) below the menu bar.

### Expected Result
"Login page" is displayed.

### Actual Result
Page does not change, continues to display "Home page"

### Version
0.81.1

### Testcase

https://24km5okj3n.codesandbox.io

### Additional Info

Apologies in advance if this is the wrong place for this.

Normally I'd post this in the react router project, but the link *does* work when I use a dropdown and augment *that* as a link.

In the test case, you will see three ways to login:

- A Menu in the upper right hand corner
- A link below the menu bar
- A drop down on the left (Login => Dropdown 1 => Item 1)

When clicking on the first two, the URL changes, as expected, but the content ("Home page" in red) does not.

When clicking on Item 1 in the dropdown, the URL changes and the content *does* change to "Login page" (the desired outcome).

Is there something special going on in Dropdown.Item that isn't happening otherwise?  The only difference I can see is that the A tag is being rendered with a role of "option".

However, when setting the role property to "option" on the Link element, it still does not work.

**Comment by layershifter** [comment]
Please make a **minimal** example. Your testcase is too complicated and it's difficult to define the source of issue.

Sorry, but we don't have time to debug your code 🐱 I will reopen issue, if you will attached more simple testcase.

However, I almost sure that issue is not related to SUIR. Try to debug your render cycles, as I see it's not occured in `Shell` when I click on `Link`. I think it's the core of problem.

**Comment by pbechliv-zz** [comment]
Just want to say that it is happening to my project as well. The last version that navigation is working correctly is 0.79.1
