### ISSUE TITLE
Popup: not working with open prop

### ISSUE THREAD

**Issue by ZachHaber** [Semantic-Org/Semantic-UI-React#2991]
### Steps
Create a Popup with a trigger and then set it to have open=true.
### Expected Result
I expect that always open popups will display where they are meant to.
### Actual Result
The always open popup shows at the top-right corner of the page (top=0, right=0) rather than at the button.
### Version
0.82.0
### Testcase
https://codesandbox.io/s/oj2o7mmqky

**Comment by levithomason** [comment]
This is a regression introduced in #2934 here:
https://github.com/Semantic-Org/Semantic-UI-React/pull/2934/files#diff-daca312d5932d8a0a079b86773c0ee3cL363

We removed the `requestAnimationFrame()` from the positioning logic.  What we need to do is position the popup appropriately on mount if open is true.  This has to be done _after_ the context ref (trigger or context) is established, otherwise, there is no node to measure and align to.

This means we'll need to trigger positioning and a second render after mount to ensure the context node has also been created and mounted.

**Comment by ZachHaber** [comment]
Hi, I wanted to check if there were any updates on this issue.

**Comment by Goondrious** [comment]
> Hi, I wanted to check if there were any updates on this issue.

Looks like there has been some progress in #3029 (mentioned here: https://github.com/Semantic-Org/Semantic-UI-React/issues/3293)

@layershifter, the above comment seems to imply #3029 might be close to merging? Happy to pick up where you left off to get it finished. Been wanting to contribute since I started using Semantic recently.
