### ISSUE TITLE
TextArea font IS incorrect

### ISSUE THREAD

**Issue by kierenj** [Semantic-Org/Semantic-UI-React#2999]
Please reopen

https://github.com/Semantic-Org/Semantic-UI-React/issues/2864#issuecomment-404203316

...this is the case inside a form, too

**Comment by layershifter** [comment]
Please fill issue template and add a n example on codesandbox.

**Comment by kierenj** [comment]
Maybe you could re-open the other issue?  I think you incorrectly assumed that this was caused by not enclosing in a form?

**Comment by brianespinosa** [comment]
@kierenj the original bug was opened without a minimal replicated example of the problem. The CSS is not part of SUIR so the issue is more likely a collision in styles within your application, or possibly due to something like a Chrome plugin. These are all guesses because the OP did not include any sort of information about how they were generating their CSS. This is why a minimum code example is required when opening bugs. Nobody can root cause a problem if we have to guess at all of the variables.

**Comment by layershifter** [comment]
It seems that related to Semantic-Org/Semantic-UI#5546
