### ISSUE TITLE
[RFC] Configurable popup keepInViewPort logic

### ISSUE THREAD

**Issue by Rinaldo** [Semantic-Org/Semantic-UI-React#3009]
## Feature Request
The Popup component should take an optional `positionFallbacks` prop which would be an ordering of positions to fall back on if the chosen position is outside the viewport

### Problem description
I have an issue where there is a row of popups across the middle of a page where the `position` prop is set to `bottom center`. The popover on the left edge of the page is displaying with a `position` of `top left` instead of `bottom left` which would be closer to the position of all the other popups.

### Proposed solution
The Popup component should take an optional `positionFallbacks` (or similarly named) prop. This prop would be an array of other positions that would override the default ordering of the `POSITIONS` array used in `setPopupStyle()`.

Example:
```
const fallbacks = ['bottom left', 'bottom right', 'top center', 'top left', 'top right', 'right center', 'left center', 'bottom center']

<Popup
  position='bottom center'
  positionFallbacks={fallbacks}
/>
```

Alternatively, logic could be added to `setPopupStyle()` to select the next best position automatically. I spent some time thinking about a possible set of rules to implement this, but I think any ordering is ultimately somewhat subjective and that it's best to just to let the user set the order they want.

**Comment by levithomason** [comment]
>I spent some time thinking about a possible set of rules to implement this, but I think any ordering is ultimately somewhat subjective and that it's best to just to let the user set the order they want.

Agreed.  Due to this, I think it is best to work this into a callback somehow and let the user handle it.  Our history shows there is no end to options and configuration that user's will want for components.  I'm very focused on simplifying component props.

I'd like to support this, but not with more hard-coded logic.  Any ideas?

**Comment by Rinaldo** [comment]
> I think it is best to work this into a callback somehow

Could you clarify what you mean by this? Do you mean integrating this into the `onMount` prop or some other prop like it?

I can understand wanting to keep the number of props to a minimum, but I think either adding a `positionFallbacks` prop or modifying the `position` prop to optionally take an array would be a reasonable solution.

**Comment by levithomason** [comment]
It seems fallbacks are reasonable.  It may conflict with `keepInViewport` as providing fallbacks seems to infer the user wants the Popup to be kept in the viewport.

@layershifter @brianespinosa any thoughts on this?

**Comment by brianespinosa** [comment]
If we are specifically trying to use these fallbacks to keep the popup in the viewport, maybe we make `keepInViewport` enumerated instead of boolean and allow the user to specify fallbacks there? Not sure if there would be a way to reduce those declarations to single strings versus pairs. Then let the viewport determine whether the popup should get a verical/horizontal override based on viewport/popup position.

This is mostly woodshedding. I think allowing `position` to be an array could be a better solution if we can envision a use case where the user may not be using this solution to keep a popup in the viewport.

**Comment by sudo-tee** [comment]
I also vote for a way to configure it.
Use case is that I want my popups with the arrow in the "bottom center", but if there is no space at the bottom of the page I would like it to be "top center". But currently there is no way of doing it :(

**Comment by sudo-tee** [comment]
In the meantime this is what I did.

https://gist.github.com/inkubux/697357d5c1d0df506a450f6a9975972e


it's not perfect but hey it works.

setPopupStyle is the same as the source code except minor tweaks the take positions from the props.

**Comment by layershifter** [comment]
Good news, this feature is already available 🐱 

---

We switched to `Popper.JS` in #3532 (`semantic-ui-react@0.87.0`) and added access to `popperModifiers` (`semantic-ui-react@0.87.2`) so this behavior can be completely configurable 🚀 

You can check for more information:
https://popper.js.org/popper-documentation.html#modifiers..flip.behavior
https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.priority

### Disable flipping
```jsx
<Popup
    content='Hello'
    open
    position='top center'
    popperModifiers={{
      flip: { enabled: false },
    }}
    trigger={<Button content='Already Open' />}
  />
```

### Flip to `right` instead of `bottom`
```jsx
  <Popup
    content='Hello'
    open
    position='top center'
    popperModifiers={{
      flip: { behavior: ['top', 'right'] },
    }}
    trigger={<Button content='Already Open' />}
  />
)
```
