### ISSUE TITLE
Dropdown value vs. highlighted item inconsistency

### ISSUE THREAD

**Issue by Coder-Sharon** [Semantic-Org/Semantic-UI-React#3088]
## Bug Report
I'm working on an image viewer that depends on three interrelated dropdowns to display the desired image. There are three levels of the viewer: 1) Anatomy, 2) ROI, and 3) Overlay. Changing the value of Anatomy also updates the values and options for ROI and Overlay, changing the value of ROI also updates the value and options for Overlay, and updating Overlay only changes itself. 

The problem occurs after the value of Anatomy or ROI changes, and the other updated values are set. Even though all active values seem to be updated properly, when I actually click to open the dropdown menu, the old active value is still highlighted, and closing the dropdown sets it back to the old active value.

Thanks in advance for any help!

### Steps
Use this to try out the steps: https://codesandbox.io/s/3vx1vjlrwm

One example:
1. Update ROI (second) dropdown to "ROI2"
2. Update Anatomy (first) dropdown to "Body," which proceeds to update ROI and Overlay dropdowns successfully. ROI should now show "ROI1"
3. Open ROI (second) dropdown. Even though "ROI1" is the value, the old value "ROI2" is still highlighted. Closing the dropdown will now set it back to "ROI1"

A second example:
1. Update Anatomy (first) dropdown to "Body"
2. Update ROI (second) dropdown to "ROI2" which updates the Overlay dropdown successfully. Overlay should now show "overlay2"
3. Update ROI (second) dropdown to "ROI5" which proceeds to update the Overlay dropdown again. Overlay should now show "overlay1"
4. Open Overlay (third) dropdown. Even though "overlay1" is the value, the old value "overlay2" is still highlighted. Closing the dropdown will now set it back to "overlay2"

### Expected Result
I expect the highlighted value to match the value of the dropdown.

### Actual Result
The highlighted value is reflecting its previous value rather than it's current value.

### Version
0.78.2 - however, the codesandbox example has the same issue, and it's using version 0.81.1

### Testcase
https://codesandbox.io/s/3vx1vjlrwm

**Comment by levithomason** [comment]
Superb report, thanks.  This is a confirmed bug.  I believe it is a duplicate but will leave open for now.  We need a good bug fix pass on Dropdown.

**Comment by Stefie** [comment]
In case anyone else is ending up here like I just did: I had a similar Bug and I tracked it down to the use of different lifecycle methods.

This Bug here can be temporarily fixed by using the soon to be deprecated `componentWillMount` like the Dropdown component instead of `componentDidMount` OR by updating the SUI component to the new lifecycle methods like suggested here https://github.com/Semantic-Org/Semantic-UI-React/issues/2732.

@kohakukun already had a PR open in october  to update the component, but these changes seem to have gotten lost somewhere on the way https://github.com/kohakukun/Semantic-UI-React/blob/8c649dc707cfedb61f7037861dbdffdc29f21d5a/src/modules/Dropdown/Dropdown.js

**Comment by layershifter** [comment]
@Coder-Sharon the report is great, thanks 👍 

----

`Dropdown` received lifecycles update in `v1.0.0.`, I checked this and this bug was fixed 🚀 

### 0.81.1

![case1-bug](https://user-images.githubusercontent.com/14183168/88807741-69584d80-d1b2-11ea-8177-9e9a915c6865.gif)
![case2-bug](https://user-images.githubusercontent.com/14183168/88807748-6bbaa780-d1b2-11ea-9c36-ad16f5356675.gif)

### 1.0.0

![case1-works](https://user-images.githubusercontent.com/14183168/88807775-71b08880-d1b2-11ea-9f36-69b79b8ae1f5.gif)
![case2-work](https://user-images.githubusercontent.com/14183168/88807794-75440f80-d1b2-11ea-817e-e26743c7e24e.gif)

I also update CodeSandboxes to verify: 
- 0.81.1 https://codesandbox.io/s/semantic-ui-react-6kkbd?file=/index.js
- 1.0.0 https://codesandbox.io/s/semantic-ui-react-vv06k?file=/index.js
