### ISSUE TITLE
Dropdown: Controlled Dropdown component ignores spaces

### ISSUE THREAD

**Issue by mic4ael** [Semantic-Org/Semantic-UI-React#3146]
### Steps
Create a controlled `Dropdown` component and by controlled I mean setting the `open` prop manually.
Then, add a debounced `onSearchChange` callback. The problem here apparently stems from the fact that I am setting `open` prop in a debounced function. After first call of this function I am able to properly type words separated by a space.

### Expected Result
Changing the search query would properly register each character.

### Actual Result
Apparently typing e.g. `adam tr` ignores the space in between the words.

### Version
0.82.4

### Testcase
https://codesandbox.io/s/ppxwk52xqx

**Comment by mic4ael** [comment]
It is worth to mention that the problem is not visible as soon as I don't specify the `open` prop manually.

**Comment by layershifter** [comment]
Almost sure that issue is comes from there: https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.82.4/src/modules/Dropdown/Dropdown.js#L552

However, I doesn't have a good how to fix this.

**Comment by mic4ael** [comment]
Why does it even behave like this? Why should the dropdown show the options after typing a space? I can't come up with a good usecase for a situation where I would like the dropdown to be open on pressing space.

**Comment by xReaven** [comment]
I don't know if it's really related to this issue, but i'm facing a similar problem with minCharacters ;
I am unable to input a space right after an other character, while I didn't write at least the <minCharacters> value of minCharacters.

Here's an example : https://codesandbox.io/s/upbeat-franklin-ovolw?fontsize=14

Try to press "a" then "space" (quickly or not, it seems that it doesn't matter). You simply can't. It opens the dropdown.

Otherwise if you press "a" then "space" then "space", it works, because the dropdown is already open. The next space (the third) will not work, because it opens... etc etc

**Comment by pavle-lekic-htec** [comment]
I have the same problem, if I enter "wqe" then it stops responding to space, but if I erase all text and try again then space works. Weird.

**Comment by layershifter** [comment]
I simplified the test case, https://codesandbox.io/s/semantic-ui-react-tm7q5
Bug is still present in `v1.0.0`.

**Comment by layershifter** [comment]
A fix was released in `semantic-ui-react@1.2.1` 🎉
