### ISSUE TITLE
Setting NODE_ENV and $(npm bin) on Windows

### ISSUE THREAD

**Issue by joshuazmiller** [Semantic-Org/Semantic-UI-React#315]
I want to bring up a bug with setting NODE_ENV in our npm scripts. When I run `npm run test` I get the following error:

> 'NODE_ENV' is not recognized as an internal or external command,
> operable program or batch file.

For reference `npm run test` executes:

> "test": "NODE_ENV=test babel-node $(npm bin)/karma start build/karma.conf.babel.js"

Upon a bit of research it appears that Windows does not support setting a variable this way. Windows requires the SET command. 

As such, and based on some digging, I recommend installing and requiring the npm module `cross-env`. This solves the issue and you'd modify the script to: 

> "test": "cross-env NODE_ENV=test babel-node $(npm bin)/karma start build/karma.conf.babel.js"

Additionally $(npm bin) is not recognized on Windows for some reason. Therefore, **the version that would work on Windows** (and hopefully the other OS' too) is:

> "test": "cross-env NODE_ENV=test babel-node node_modules/karma start build/karma.conf.babel.js"

**Comment by dvdzkwsk** [comment]
Nice find, we noticed this earlier today and already have plans to fix it (https://github.com/TechnologyAdvice/stardust/issues/313). I'm personally still a bit torn between `cross-env` and `better-npm-run`, mainly due to https://github.com/kentcdodds/cross-env#known-limitations, but I'll have to take a look at our current script execution cycle before determining whether or not that case is relevant.

If you can justify picking one over the other and want to submit a PR we'd more than welcome it, otherwise I will get to the fix in the AM tomorrow. I'll reference this issue from the existing one so we can keep track of this all in one place. Thank you!

**Comment by joshuazmiller** [comment]
Great! My personal opinion from comparing `cross-env` to `better-npm-run` is that `cross-env` seems cleaner to me and adheres to the standard npm script structure. `better-npm-run` appears to deviate a bit with `scripts` in turn pointing to `betterScripts`. I personally dislike when a library does that because it confuses people who are familiar and prefer the standard structure. However, if there is a real reason why `cross-env` doesn't cut it then I guess `better-npm-run` is an option.

Aside from the issue with env var assignments, it appears that `$(npm bin)` also is an issue in Windows. I'd prefer to substitute it with a hard-coded `node_modules` but I'm not sure what the argument is against doing that. Doesn't everyone have node_modules in the root directory of a React project? I have never seen otherwise.
