### ISSUE TITLE
Custom icon is not showing

### ISSUE THREAD

**Issue by jansedlon** [Semantic-Org/Semantic-UI-React#3152]
### Steps
Install RPG Awesome font
`yarn add rpg-awesome`

Import RPG Awesome font
`import 'rpg-awesome/css/rpg-awesome.min.css';`

Use it with Icon component
`<Icon className='ra ra-burning-eye'/>`

### Expected Result
Displayed icon

### Actual Result
Blank space

### Version
0.82.4

### Testcase
https://codesandbox.io/s/v8q283r2m3

### Description
Looks like font-family from "icon" class replace RPGAwesome font-family

**Comment by brianespinosa** [comment]
This isn't a bug in Semantic UI React or Semantic UI. The CSS you are including is not specific enough to override the out of the box styles you are using.

SUI targets `i.icon`
Your css uses `.ra`

The first rule is more specific so it is going to override your single class.

For your use case, I would actually recommend creating your own `Icon` component that you can use instead of the one in this project. You are going to have to override a lot of out of the box SUI styles to get your other icons to work. At least the way their minified  CSS is written. That or compile your own CSS and remove the styles in SUI for the Icon.

Closing this issue as it is not a bug. If you have any questions on how to move forward based on the above info, you will get better help on Stack Overflow.
