### ISSUE TITLE
Dropdown click and enter events are not the same

### ISSUE THREAD

**Issue by ka7eh** [Semantic-Org/Semantic-UI-React#3155]
## Bug Report
I have a dropdown that I need to modify its event when `onChange` is called in order to make it usable for formik (https://github.com/jaredpalmer/formik). When I click on an option, the dropdown receives a synthetic event, I update some of its attributes, and then call formik event handler. But if I press enter instead of clicking on an option, the event is not a React synthetic event and its target is a different element, which causes problem with formik.

### Steps
In the test case below, first pick a country by clicking on it and see the event in the console. Then try selecting another country by pressing enter and see the difference between events.

### Expected Result
In both cases, dropdown should pass React synthetic events to `onChange`.

### Actual Result
As mentioned above, events are not consistent across click and key press events.

### Version
0.82.5

### Testcase
https://codesandbox.io/s/w663wm3n1k

**Comment by layershifter** [comment]
These events cannot be same by design, one comes from React and other comes from DOM. The best solution for third party form libraries is to create custom wrappers and grab values from the second argument.

Something similar is done for `redux-form`, you can check our Prototypes section: https://react.semantic-ui.com/prototypes. As I see, wrappers for `formik` are already exist, please check them: https://github.com/turner-industries/formik-semantic-ui
