### ISSUE TITLE
Dropdown Search Text Stays After Item is Picked

### ISSUE THREAD

**Issue by chuanqin3** [Semantic-Org/Semantic-UI-React#3156]
### Steps
1) Input the string in the the searchable dropdown list
2) Select the wanted item
3) The string remains
![semantic react ui bug](https://user-images.githubusercontent.com/7230816/45506545-8e2dae00-b75d-11e8-9cb0-b0c3bb3b38eb.gif)

### Expected Result
I expect the search text to go away automatically when the item is picked

### Actual Result
The actual result that happened 💣

### Version
`<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">`

### Testcase
Coulnd't reproduce the problem in Codepen.. Is this because of React's state sometimes does not update on time?

**Comment by brianespinosa** [comment]
@chuanqin3 if you cannot reproduce in codepen that means the issue has to do with how you have implemented this in your own project. My guess is you are passing in a value to the input that should be a defaultValue instead. But there is no way to tell because you have not provided a code example of what you are doing.
