### ISSUE TITLE
Remote multiple dropdown was bugged

### ISSUE THREAD

**Issue by yuritoledo** [Semantic-Org/Semantic-UI-React#3254]
### Steps
Using a dropdown with remote option active, try to search a name in a API, selected 2 items , then search for another name, and selected 1. Only the last is showed in searchQueryBar.

### Expected Result
I expect that all 3 selected options be showed in dropdown

### Actual Result
Only show the last one.

### Version
0.83.0

### Testcase
![multisearch_remote](https://user-images.githubusercontent.com/18474538/47877073-c23a5c80-ddf9-11e8-91bd-e0ad2efdf916.gif)

**Comment by layershifter** [comment]
Please add a codesandbox example, it's not clear how you did reach this result. I will reopen issue when it will be present.

**Comment by mustafa519** [comment]
I'm having the same issue that above. Any progress?

I think it's a bug or undocumented issue.

## Scenario
- First API call sets the `options` of `Dropdown` component.
- User selects items from the options.
- And then, second API call to get other items causes the bug.
- Second call, hides all selected items that first call.
- When i set the first call options, then they being seen.

The bug, might be related to option item filter issue. Because, it hides unmatched or already selected items.
