### ISSUE TITLE
Modal: close Icon not showing 

### ISSUE THREAD

**Issue by hommalex** [Semantic-Org/Semantic-UI-React#3263]
### Steps
The Close Icon is not showing when the modal has exaclly the same height as the window.
If you also have the closeOnRootNodeClick set to false, It become impossible to close the modal.

### Version
I updated from 0.3 to 0.8 and the problem still here.

### Fix
I had to change the node_module because it's easier to re-calculate the all modal position there
on Line 159 of the Modal.js
`var scrolling = height >= (window.innerHeight-60);`
I show a close in every of my modal. 
You may have modified this if you only use close icons on the od times

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please correct used versions, it's hard to understand with what version we have a deal. However, I should confirm that issue is there in the latest versions of SUI & SUIR. This issue can't be fixed on our side because it comes from SUI styles.

As workaround you can use `fullscreen`:
```jsx
<Modal size='fullscreen' />
```

Or set icon to be always inside the modal:
```jsx
<Modal closeIcon={{ style: { top: '1.0535rem', right: '1rem' }, color: 'black', name: 'close' }} />
```
