### ISSUE TITLE
Pagination: button dissapears when `ellipsisItem` is null

### ISSUE THREAD

**Issue by JoelViney** [Semantic-Org/Semantic-UI-React#3266]
### Steps
1. Goto the following site: https://codesandbox.io/s/54noj82lxn 
2. Count the number of buttons. Confirm that it is 6 which are (<. 1, 2, 3, 4, >)
3. Click the button '4'
4. Count the number of buttons. Confirm that it is now 5 which are (< 3, 4, 5, >)
5. Wonder where your 6th button has gone

### Expected Result
I expected that the number of buttons wouldnt change.

### Actual Result
The number of buttons went from 

### Version
0.82.5

### Testcase
https://codesandbox.io/s/54noj82lxn

**Comment by layershifter** [comment]
Looks like a bug, should be additionally checked. There are should be `[<, 1, 2, 3, >]` by default, as I understand the issue caused by disabled ellipsis.

**Comment by layershifter** [comment]
Fixed in #3271. Thanks for report 👍 

![image](https://user-images.githubusercontent.com/14183168/48299905-a95a3700-e4dc-11e8-8f1d-682415121cd9.png)
![image](https://user-images.githubusercontent.com/14183168/48299909-af501800-e4dc-11e8-97f0-1d8215bacb97.png)
![image](https://user-images.githubusercontent.com/14183168/48299913-b545f900-e4dc-11e8-8e8d-b3a1e6fa9be2.png)
