### ISSUE TITLE
Popup: should contain `disabled` prop

### ISSUE THREAD

**Issue by spirkovskii** [Semantic-Org/Semantic-UI-React#3339]
### Problem description
I have an issue when using Popup to display validation error on some input.

If the input is invalid I render it in the popup via trigger prop, if it's not invalid I render just the input.
The problem with this is when the state changes from invalid to valid and vice versa, my input loses state.

![example](https://user-images.githubusercontent.com/14183595/49969110-ff7d2880-ff27-11e8-9440-3af236ccdf1d.PNG)

### Proposed solution
I would like the popup to have prop disabled, which would only render the component passed via trigger.
If you think this makes sense, I am willing to implement it

**Comment by levithomason** [comment]
Tips:

1. You can use the [`context` Popup prop](https://react.semantic-ui.com/modules/popup/#usage-context) to pass a node reference.
2. You can use the [Ref component](https://react.semantic-ui.com/addons/ref/) to ensure you always get a DOM node reference.

This will always render the same `Input` element, even when the `invalid` state changes.  The Popup will only be added to the page when the input is invalid.  Since the Input is not a trigger of the Popup, it should not lose state or focus.  It will always exist in the DOM:

```jsx
import { Input, Popup, Ref } from 'semantic-ui-react'

// ...

<>
  {invalid && <Popup context={this.inputRef} />}

  <Ref innerRef={node => (this.inputRef = node)}>
    <Input />
  </Ref>
</>
```

**Comment by spirkovskii** [comment]
Thank you for your answer Levi,

I think it would be good idea to add example with using Ref in the documentation, since Ref is buried in the bottom of the components under addons, and no clue that it could be used like this was provided in the docs.

This solves my problem but I still think 'disabled' prop should be added, it may solve some other specific scenarios for the consumer and after all it doesn't bring any breaking changes and would save few lines of unnecessary implementation.

**Comment by levithomason** [comment]
Agreed on both counts.  We have an update coming for the Popup as well, #3377.  Would you like to add an example for the `Ref`?
