### ISSUE TITLE
Table with fixed head and scrollable body?

### ISSUE THREAD

**Issue by zheyujie** [Semantic-Org/Semantic-UI-React#3363]
## Feature Request
Is it possible to support table with fixed head and scrollable (overflow) body?
Thanks

**Comment by layershifter** [comment]
It's not possible to do this with raw SUIR. Previously I did this using [react-table](https://react-table.js.org/#/story/readme).

We have an issue for this, #1133, but we didn't reach any progress there.

**Comment by nicholascm** [comment]
@layershifter @zheyujie We were able to accomplish fixed header/scrollable body in SUIR using a variation of this solution: https://codesandbox.io/s/scrollable-tbody-semantic-ui-8pred 

Ours was not identical as we have fixed-width columns and side scrolling as well...but this codesandbox was hugely helpful in getting there.

**Comment by RubenMaier** [comment]
> @layershifter @zheyujie We were able to accomplish fixed header/scrollable body in SUIR using a variation of this solution: https://codesandbox.io/s/scrollable-tbody-semantic-ui-8pred
> 
> Ours was not identical as we have fixed-width columns and side scrolling as well...but this codesandbox was hugely helpful in getting there.

Hey good work! I am needing something similar. In my case, I need to freeze the first column of the table in addition to the header. Did or know how to do something like that with Semantic Ui React Components?

**Comment by mkirby** [comment]
@nicholascm Any ideas or suggestions how to retool that code and get it to work on a SUIR table with multiple columns? It seems that to make the scroll work the SUIR table is broken out of SUIR formatting and the re-converted to a table and this breaks the column headers so that they no longer match up with the data below. 

I've retooled the working single column example and added what I've been trying to get work here: https://codesandbox.io/s/scrollable-tbody-semantic-ui-react-not-lining-up-pmmzn

edit: I've also found this example of a scrollable table: https://embed.plnkr.co/plunk/GjVcvH
But that also seems to break my ability to set columns/ cell widths and general formatting.
