### ISSUE TITLE
Range input or slider

### ISSUE THREAD

**Issue by alexandrtovmach** [Semantic-Org/Semantic-UI-React#3384]
### I've discovered what Semantic UI haven't any slider soluitions.
After some research I found separate package [react-semantic-ui-range](https://github.com/iozbeyli/react-semantic-ui-range) for react, which is actually based on [semantic-ui-range](https://github.com/tyleryasaka/semantic-ui-range), but why does Semantic not have something like this "inside the box"?

### I would be happy to create this, or maybe colaborate with someone
I want to create this component from scratch, because I'm not sure that it'll be fair to use codebase above.  The authors of these packages didn't create any PR's for Semantic UI repo, therefore, probably, they do not want to cooperate with them.

The main reason for this ticket is to understand:

> “Do we need to have a slider inside the Semantic UI, or better to continue using a third-party solution?”

**Comment by levithomason** [comment]
I would love to see a range component added as well.  Right now, the path for adding components is a little tough since we need to add them to both [Semantic UI](https://github.com/Semantic-Org/Semantic-UI) (jQuery) and Semantic UI React.

The best way to get this added for now is to get it merged to Semantic UI core, then we can add the port here in Semantic UI React.

I'm working on ways for sharing state, styles, and accessibility between the frameworks.  Once we have this, we can have a central place for adding components like this.

**Comment by alexandrtovmach** [comment]
Okay, sounds good. So if I understand correctly, firstly we need to implement slider for Semantic UI core, using jQuery. Do you already have some code for this, or need to develop from scratch? Can I help with that?

**Comment by alexandrtovmach** [comment]
I found [that issue](https://github.com/Semantic-Org/Semantic-UI/issues/1336), so I'll take a look more tomorrow

**Comment by alexandrtovmach** [comment]
@levithomason What is the current status? As I can see @gdaunton already implemented everything on jQuery, and created PR's to core, but then it'll be closed because... it was been ignored? So what is the plan?

**Comment by transfer1992** [comment]
@alexandrtovmach Not sure if SUIR team has it maybe already under discussion, but there actually is a Slider component in Fomantic UI, which is a fork of Semantic UI core created to continue its active development. Due to lack of Slider component in Semantic UI React I had to blend its Fomantic's jQuery implementation into my React application. @levithomason Is Semantic UI React team maybe considering an option to switch to Fomantic UI as a base in future?

**Comment by SuchMonkey** [comment]
I second the notion to use Fomantic UI fork. Not only as an option but as the actual base for this project. Reason being that the folks behind the Fomantic fork actually intend to merge with Semantic once active development there picks up again (Well that's the plan at least...)

There are lot's of benefits to be gained:
- Various bug fixes
- New components like the after mentioned range slider but also a date picker, placeholder segments and recently global text colors
- Active development

The bulk of the work for such a feat would come in the form of new component implementation and replacing the jQuery stuff with React. Also implementing new features on existing components, like the clear able option for the drop down. Mostly in the form of new properties.
The bug fixes mainly concern the CSS / LESS.

I'd hate to see a Fomantic-UI-React fork as well since this repo is far from being stale. However the current state of affairs simply limit future progress considering that the code (LESS, JQuery) already exists over at Fomantic.

**Comment by transfer1992** [comment]
> Reason being that the folks behind the Fomantic fork actually intend to merge with Semantic once active development there picks up again (Well that's the plan at least...)

I'm afraid that is no longer true:
https://github.com/fomantic/Fomantic-UI/issues/319#issue-393243230

**Comment by y0hami** [comment]
@transfer1992 @SuchMonkey SUIR switching to FUI has already been discussed here https://github.com/Semantic-Org/Semantic-UI-React/issues/3397

@transfer1992 I don't want to take this issue off-topic so I will keep it brief but FUI does still have the intention to merge back into SUI but under different circumstances. If you want to read more I just posted a comment [here](https://github.com/fomantic/Fomantic-UI/issues/319#issuecomment-461736399)

**Comment by CarlQLange** [comment]
@alexandrtovmach Hi, may I ask why you closed the issue? I think the need for this is still there, or am I wrong?

**Comment by alexandrtovmach** [comment]
@CarlQLange in reason of no any progress, and seems like it'll be never realized

Semantic UI is stopped active development of new features, so this issue haven't any sense

**Comment by felipenmoura** [comment]
Hey folks...it's from 2019.
No merge from FUI into SUI that could bring such feature?
A range/slider is simply a "must have" for any interface library :)
