### ISSUE TITLE
Changing a Dropdown's options fails to reset state.selectedIndex properly

### ISSUE THREAD

**Issue by jskeate** [Semantic-Org/Semantic-UI-React#3423]
### Steps
https://codesandbox.io/s/866yxp039

1. Open dropdown. Observe that "Two" is both the selected option and the option in the box at the top.
2. Click button to swap the options to a different set (both texts and values)
3. Observe the dropdown shows "Tres" (correctly).
4. Open dropdown. Observe that "Tres" is highlighted still, but "Uno" is selected.
5. (optional) Click outside of the dropdown. "Uno" becomes the selected value.

### Expected Result
Step 4: "Tres" is highlighted and selected.
Step 5: "Tres" remains the selected.

### Actual Result
"Uno" is selected

### Version
Tested on 0.84, 0.85

### Testcase
https://codesandbox.io/s/866yxp039

I also tried to fix this myself, got a failing test:

```
    it('resets selectedIndex on options change', () => {
      const firstOptions = [
        { text: 'One', value: 1 },
        { text: 'Two', value: 2, selected: true },
        { text: 'Three', value: 3 },
      ]
      wrapperMount(<Dropdown options={firstOptions} value={2} />)
      wrapper.find('.text').first().text().should.equal('Two')

      const secondOptions = [
        { text: 'Uno', value: 'a' },
        { text: 'Dos', value: 'b' },
        { text: 'Tres', value: 'c' },
      ]
      wrapper.setProps({
        options: secondOptions,
        value: 'c',
      })

      wrapper.find('.text').first().text().should.equal('Tres')
      wrapper.simulate('click')
      dropdownMenuIsOpen()
      wrapper.find('.text').first().text().should.equal('Tres')
    })
```

### Commentary

As best I can tell, this is happening because [the state update from the parent AutoControlledComponent](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/AutoControlledComponent.js#L178) hasn't propagated yet by the time we [check if the options have changed in Dropdown](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L429-L436).

**Comment by layershifter** [comment]
Actually, it's an edge and it can be handled by component properly.
Please consider to use keys with your sets: https://codesandbox.io/s/13o3on27v4

However, thanks for the detailed report, really appreciate it 👍

**Comment by maxhudson** [comment]
@layershifter seems like odd usage of key - typically key is used to help determine if a component corresponds to the same item in a collection. If you wanted to create `<Dropdown>`s in a loop and have changing options, you'd have to go ``<Dropdown key={`item-${itemKey}-options-${optionsKey}`}>`` or something like that.

I'm not actually running into that key conflict because I only have one select input, but I did spend about an hour trying to figure out how to fix this issue (which seems like a bug to me).

Attached screenshot is straight from the first [react doc](https://reactjs.org/docs/lists-and-keys.html) on keys that shows up when googling 'react key'. Nobody is going to expect to have to provide a key for this.

<img width="777" alt="screen shot 2019-02-14 at 7 04 28 pm" src="https://user-images.githubusercontent.com/7915687/52832034-bd897380-308b-11e9-803c-559610d1d355.png">
