### ISSUE TITLE
Use @brandFontName for brand icon's font-family CSS rule

### ISSUE THREAD

**Issue by lolero** [Semantic-Org/Semantic-UI-React#3434]
## Bug Report
The `@brandFontName` vatiable is not consumed in `icon.overrides` as it should be.

### Steps
I have an open [PR](https://github.com/Semantic-Org/Semantic-UI-LESS/pull/54/files) with the fix.

### Expected Result
If I want to use different icon libraries aside from those offered by SUI, overriding the `@brandFontName` variable should render the icons that I want.

### Actual Result
Overriding the `@brandFontName` variable does not render my third-party icons.

**Comment by layershifter** [comment]
Sorry, but we don't handle CSS issues there, you should move it to the main repo: https://github.com/Semantic-Org/Semantic-UI

As I see, it also fixed in Fomantic UI: https://github.com/fomantic/Fomantic-UI/blob/7128a9324a835796d625b77507a7c8881ba913a9/src/themes/default/elements/icon.overrides#L1888
