### ISSUE TITLE
Dropdown.Item doesn't render

### ISSUE THREAD

**Issue by tslater** [Semantic-Org/Semantic-UI-React#346]
Dropdown.Item isn't rendering.

I'm trying examples like this:

```
 <Dropdown text='File' action='hide'>
        <Dropdown.Item text='New' />
        <Dropdown.Item text='Open...' description='ctrl + o' />
        <Dropdown.Item text='Save as...' description='ctrl + s' />
        <Dropdown.Item text='Rename' description='ctrl + r' />
        <Dropdown.Item text='Make a copy' />
        <Dropdown.Item icon='trash' text='Move to trash' />
        <Dropdown.Divider />
        <Dropdown.Item text='Download As...' />
        <Dropdown.Item text='Publish To Web'>
          <Dropdown.Menu>
            <Dropdown.Item text='Google Docs' />
            <Dropdown.Item text='Google Drive' />
            <Dropdown.Item text='Dropbox' />
            <Dropdown.Item text='Adobe Creative Cloud' />
            <Dropdown.Item text='Private FTP' />
            <Dropdown.Item text='Another Service...' />
          </Dropdown.Menu>
        </Dropdown.Item>
        {/* item text can also be defined as children */}
        <Dropdown.Item>E-mail Collaborators</Dropdown.Item>
      </Dropdown>
```

**Comment by tslater** [comment]
I mistakenly wrote in issue #168 that it's not exported. I realized that you can import it like it says here: `Dropdown.Item`. The real issue is that it looks like they just aren't showing up. Maybe the children are no longer being used, only options? the main thing I'd like to do here is render custom html elements for/inside the items.

**Comment by levithomason** [comment]
Correct, this was a calculated decision.  We opted to use an array of `options` due to complexity and issues with calculating the `active` item.

Items are `active` when their value matches the currently selected value of the dropdown:

![image](https://cloud.githubusercontent.com/assets/5067638/17079289/4d51aa5e-50c0-11e6-844e-d0ad6f83cd0e.png)

This means, we have to loop over the items during render and compare the item `value` to the currently active `value` of the dropdown.  If those are the same, then the item is made `active.  This is very straight forward if we are given an array of items to work with at the dropdown level.

However, if the user defines Dropdown.Items in the markup, it becomes more convoluted to loop through them and make the correct one `active`.  This is because looping over children only loops immediate children, but the immediate child to a Dropdown is the Dropdown.Menu.  One way to loop the Dropdown.Item children is to ask the Menu (via instance methods through refs) for an array of it's Item children.  This wasn't a great solution, so we opted not to support it for the time being.

All said, I've added https://github.com/TechnologyAdvice/stardust/pull/347 to support this now.  There are known limitations.  I'll continue conversation over there.
