### ISSUE TITLE
Don't throw error if jquery is detected

### ISSUE THREAD

**Issue by wallslide** [Semantic-Org/Semantic-UI-React#352]
The error that is thrown here was preventing our app from loading:
https://github.com/TechnologyAdvice/stardust/blob/3d3dab56d1de1a87b946f77c7f04ffc7cfbb48fa/src/utils/jquery.js#L14

jquery might be loaded for any number of reasons. I don't think it's reasonable to throw an error if it exists. Just not using it within stardust should be enough. In our case, we're using stardust in a Meteor app.  Meteor makes it notoriously difficult to remove jquery completely, although we're trying.

**Comment by levithomason** [comment]
The reason it is an error is because the Semantic UI form plugin has not yet been removed, see #247. That plugin needs to extend your jquery in order for it to work.  This was added to solve duplicate jQuery issues other users were having. 

As you can see in the linked issue, jQuery will soon be removed entirely and we'll all be much better off. For now, we can demote this error to a console error.

**Comment by levithomason** [comment]
@wallslide fixed and released, install the latest version and give it a go.
