### ISSUE TITLE
Modal - unknown prop 'settings'

### ISSUE THREAD

**Issue by ljubic** [Semantic-Org/Semantic-UI-React#354]
According to Stardust documentation Modal has property 'settings', but when I add it to the component it throws me an error that property is unknown.

Here is the code:

```
<Modal settings={{"observeChanges": true}}>
     /* other code... */
</Modal>
```

Is there any solution to this? Modal is also not centered vertically.

**Comment by levithomason** [comment]
@ljubic the modal is soon to be updated to our v1 component API, see https://github.com/TechnologyAdvice/stardust/issues/269.  We'll likely attack this component soon since we also need it here at @TechnologyAdvice. 

If you'd like to use it anyway, while it is in development, let me know your use case and I'll see if I can help.

To be future proof, I'd avoid using the settings prop and wrap it as a controlled component. Once it is updated, we'll support both controlled and uncontrolled versions as we do with all our modules. 

Thanks much.

**Comment by levithomason** [comment]
Closing for now in light of the thumbs up.  Let me know if there are any further issues on this that we can help with.
