### ISSUE TITLE
Module not found: Can't resolve 'semantic-ui-react' 2019

### ISSUE THREAD

**Issue by tooyangski** [Semantic-Org/Semantic-UI-React#3545]
I already imported the semantic-ui-css to my index.js file

![image](https://user-images.githubusercontent.com/30281886/55398759-eacaac00-557b-11e9-8e7e-8988d0da94df.png)

But still gets the error of 
![image](https://user-images.githubusercontent.com/30281886/55398787-fcac4f00-557b-11e9-8139-0e44e6ac448d.png)

FYI I already did the 'yarn add semantic-ui-react' before importing the semantic-ui-css and using it in my LoginPage.js

![image](https://user-images.githubusercontent.com/30281886/55398879-31b8a180-557c-11e9-8b51-1180050e014c.png)

**Comment by velsonjr** [comment]
Could you show me your Login Page?
And I hope you have installed the package using **npm install semantic-ui-react** or **yarn add semantic-ui-react**

**Comment by layershifter** [comment]
Please create a repro repository. However I almost sure that it the issue with package manager, try to reinstall `semantic-ui-react` package.

**Comment by tooyangski** [comment]
@layershifter  that did work, thanks..

**Comment by hridayeshs** [comment]
still not working

**Comment by waylandc** [comment]
Also not working. Tried uninstalling and reinstalling but VSCode still doesn't seem it. FWIW, import React from 'react' works fine.

**Comment by ErnestoDevs** [comment]
Having same issue

**Comment by brianespinosa** [comment]
Locking this issue for further comments as it is very old and does not have anything to do with SUIR.

As @layershifter suggested in the initial closure asking for a repro case, this is almost surely to do with the dependency not being installed at the package level. This likely means that the package was not added to the `package.json` file, or if it was, a fresh `yarn install` or `npm install` needs to be run in order to get the package added as a dependency.
