### ISSUE TITLE
How to access input value while typing on Dropdown

### ISSUE THREAD

**Issue by padsbanger** [Semantic-Org/Semantic-UI-React#355]
Hello,

I am trying to implement dynamic Dropdown. When user starts typing I want to pull the value from the input and send request  to API with text entered and get options returned. My component looks like this:

```
<Dropdown
  className="fluid selection dropdown"
  placeholder={'Start entering some value for dynamic suggestions'}
  onChange={this.handleChange.bind(this)}
  search={true}
  multiple={false}
  simple={true}
  options={this.state.options}
  disabled={this.state.isFetching}
  loading={this.state.isFetching}/>
```

Normally you would use onChange callback for this, but in your Dropdown component it is used to get value from options selection not from the text input.

Any suggestions on how to tackle this ?

**Comment by levithomason** [comment]
My first thought is a PR that adds something like `onSearchChange`. It would fire with the event and value of the search input when the search input value changes. Would this accomplish what you are after? 

---

As a side note,  you don't need className here. The `dropdown` class is automatically added and there are boolean props for `fluid` and `selection`.  Also, React props without values are "true" by default. Stardust doesn't default anything to true, so `multiple` can be omitted since it is already false. It won't change the functionality of your code, but might clean it up a bit:

``` jsx
<Dropdown
  simple
  fluid
  search
  selection
  placeholder={'Start entering some value for dynamic suggestions'}
  onChange={this.handleChange.bind(this)}
  options={this.state.options}
  disabled={this.state.isFetching}
  loading={this.state.isFetching}/>
```

**Comment by padsbanger** [comment]
Something like `onSearchChange` would be perfect. I noticed that Dropdown holds the value on input as state in `searchQuery`, I  was trying to access it somehow but no luck.

**Comment by levithomason** [comment]
See #360 for the PR.

**Comment by levithomason** [comment]
@padsbanger I've merged this and shipped it in `v0.27.4`.  Once CI ships the updated doc site (few minutes from now), then you can also see it at play [here](http://technologyadvice.github.io/stardust/modules/dropdown#selection).

Let me know if this works for you.

**Comment by padsbanger** [comment]
Thank you, it works, I am now able to get current value from text input.

 However now I run into this weird problem. Because options object is created dynamically (returned from API) any values that already are inside of the Dropdown that don`t match the new options object are not displayed.

Example:

I type `a` into a Dropdown. The API returns options like this [{value: 'a', 'text:'a'}, {value: 'aa', text: 'aa'} {...}]

Inside my Dropdown I already have value like this: ['a', 'b']. Only 'a' will be displayed because it matches current options.

I understand that working with dynamic data was never a use case for this component. My suggestion for a quick fix would be to have an option like `allowFreeInput` that would allow adding values that don`t much current options.

**Comment by levithomason** [comment]
> I type a into a Dropdown. The API returns options like this [{value: 'a', 'text:'a'}, {value: 'aa', text: 'aa'} {...}]
> 
> Inside my Dropdown I already have value like this: ['a', 'b']. Only 'a' will be displayed because it matches current options.

If the dropdown `options` are `[{value: 'a', 'text:'a'}, {value: 'aa', text: 'aa'}]` then there are two options available.  If the `value` is `['a', 'b']`, then this is a `multiple` dropdown.  The option `{value: 'a', 'text:'a'}` should be `active`.  Active options in multiple dropdowns are removed from the dropdown menu as they are placed as labels in the dropdown input area.  This would leave a dropdown menu of only one option remaining `[{value: 'aa', text: 'aa'}]`.  The other active value, `'b'` would not match anything since there are no options in the array that match `'b'`.

I don't quite have enough information to on this use case but it sounds like everything is working the way it should.  You may need to consider merging the options arrays instead of replacing the options?

> I understand that working with dynamic data was never a use case for this component.

The dropdown was written to handle dynamic options.  Refer to the doc site [Selection](http://technologyadvice.github.io/stardust/modules/dropdown#selection) example "Fetch" button.  We also use the Dropdown here at TechnologyAdvice to fetch options from an API.

It sounds like you may be looking for `allowAdditions` though, see #356.
