### ISSUE TITLE
Dropdown: Search does not preserve value

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#3552]
## Bug Report

When searching for values with the dropdown, the searched value is not preserved in the next consecutive search.

### Steps
A clear and concise description of steps to reproduce the problem.

Consider "Search Dropdown" from the documentation page.

Normal Behavior:

1. Open Dropdown values
2. Click on any value
3. Click inside the dropdown again
4. Value is preserver

Error Behaviour

1. Open Dropdown values
2. Search for any value
4. Click on this value
3. Click inside the dropdown again
4. Value is LOST ;(

![ReactBug](https://user-images.githubusercontent.com/2682705/55529825-e541a300-56ee-11e9-8af8-77c21b65cc70.gif)

### Expected Result

Selected value will be preserved

### Actual Result

Value is lost

### Version

Latest

### Testcase

You can just use your documentation page
![ReactBug](https://user-images.githubusercontent.com/2682705/55529825-e541a300-56ee-11e9-8af8-77c21b65cc70.gif)

**Comment by mihai-dinculescu** [comment]
This sounds like the expected behaviour. The "search" is supposed to be help with finding the option that you're looking for in the dropdown. Once you select an option, you're previous "search" has no further value. The next time you open the dropdown, the expected behaviour is to see all the available options, with no pre-existing filter.

The way this is implemented (in general, not just in SUIR) is by allowing the dropdown the store any text (the "search" term) as selected value, while the dropdown is open. Once you select an option, the option becomes the selected value, thus overwriting whatever you've typed previously. If you close the dropdown without selecting an option, the selected value is cleared because it does not match any of the available options, thus clearing your "search".

"Search" it's a bit of a misleading term in this context. Instead of a regular search, this feature is more like auto-complete, or option filter.

**Comment by tomitrescak** [comment]
@mihai-dinculescu did you watch the gif? I am pretty sure that is not the standard behaviour. Even when I select the value from the dropdown the value is not preserved. In the gif check that after selecting "California", when reclicking to the Input the value disappears

**Comment by mihai-dinculescu** [comment]
Oh yes, that is definitly an issue. It seems to be the same as #3560.
