### ISSUE TITLE
Input does not display error inside Form.Field with  form control component

### ISSUE THREAD

**Issue by tomerjann** [Semantic-Org/Semantic-UI-React#3571]
### Steps
I'm creating a table component with Input, Select and Button elements in the first row.
Click on the button should add new entry to the table.

If one of the values is empty it should set the Input and Select error attribute to true.
When creating a new `Form`  with ` Form.Field control={Component}`
and click the add button, the Input element does not display error.

### Expected Result
Clicking on the Add button should display error if the Input or Select value is empty

### Actual Result
Only the Select error is displayed

### Version
0.86.0

### Testcase
https://codesandbox.io/s/109y4wx34j

**Comment by layershifter** [comment]
Sorry, but we don't have time to debug your code. Please come with minimal repro case if your issues still exists.

All I see, everything works fine in examples:
https://react.semantic-ui.com/elements/input/#states-error
https://react.semantic-ui.com/modules/dropdown/#states-error

**Comment by adamhazon** [comment]
@layershifter This is the most annoying and unprofessional answer I've ever seen.

@tomerjann said specifically that it happens when you use Input inside a FormField, not by itself,
and it still happens today, August 2020!

The examples / documentations are not cover this case.

**EXPLANATION OF THE BUG:**
`.ui.form input[type=text]` style is overriding the `.ui.input.error>input` style,
so you don't see the error style when using `Input` inside `Form.Field`.

Pretty easy to fix, but I guess you just don't have the time 🤷‍♂️

**Comment by layershifter** [comment]
> @layershifter This is the most annoying and unprofessional answer I've ever seen.

I asked for a minimal bug reproduction as the original CodeSandbox contained too many things. And never got a response...

> The examples / documentations are not cover this case.

Please provide a minimal repro case as it still unclear what happens 🤦 

```jsx
  <Form>
    <Form.Input error />
    <Form.Select error />
  </Form>
```

![image](https://user-images.githubusercontent.com/14183168/89389227-753d9580-d705-11ea-9d39-26cf2dfa8680.png)


```jsx
  <>
    <Input error placeholder='Search...' />
    <br />
    <Select error />
  </>
```

![image](https://user-images.githubusercontent.com/14183168/89389357-9605eb00-d705-11ea-94f0-5534d1602063.png)

```jsx
  <Form.Field>
    <Input error placeholder='Search...' />
  </Form.Field>
```

![image](https://user-images.githubusercontent.com/14183168/89389611-ec732980-d705-11ea-942f-2649ab8badf3.png)

**Comment by adamhazon** [comment]
This one is not working, I don't know how it works for you.
I attached a screenshot of the CSS conflicts.
```
<Form.Field>
    <Input error placeholder='Search...' />
</Form.Field>
```
![image](https://user-images.githubusercontent.com/6360458/89506050-c95e7d80-d7ca-11ea-9e50-1a491100a4b7.png)

**Comment by layershifter** [comment]
@adamhazon you export any example in one click to CodeSandbox and then edit it, this will definitely simplify the conversation and will clarify the issue 🙏 

![image](https://user-images.githubusercontent.com/14183168/89507388-ba78ca80-d7cc-11ea-9dc0-1a30c648ae13.png)

---

So styles will collide only in this case:

```jsx
<Form> {/* <- Form is required */}
  <Form.Field>
    <Input error placeholder="Search..." />
  </Form.Field>
</Form>
```

https://codesandbox.io/s/laughing-babbage-y6fqb?file=/example.js

A solution there will be to move `error` to `Form.Field` or use `Form.Input` (it does exactly the same):

```jsx
<Form>
  <Form.Field error>
    <Input placeholder="Search..." />
  </Form.Field>
  <Form.Input error placeholder="Search..." />
</Form>
```

@adamhazon is there a use case when `Form.Input` does not work for you?

**Comment by adamhazon** [comment]
@layershifter Thank you for taking the time to investigate and write a proper answer 🙏 

I already fixed the problem by overriding the style,
changing the structure to use `Form.Input` or moving the `error` to `Form.Field` will not work in my case.

Update:
I just tried again to use `error` inside the `Form.Field` instead of overriding the style and it works 👍 

I'm just saying that using `Form.Field` inside a `Form` is pretty obvious and should be fixed. 😆 

Thanks again for your time and response, now the proper answer is here for anyone who faces this issue!
