### ISSUE TITLE
Un-toggling Radio makes it appear disabled

### ISSUE THREAD

**Issue by madyward** [Semantic-Org/Semantic-UI-React#3590]
## Bug Report
When a user toggles a radio, then un-toggles it, it appears as though it's disabled (even though it is not). If the user clicks on some other part of the screen, it goes back to normal and doesn't appear disabled anymore.

### Steps
1. Click to toggle the radio on (this could be done anywhere, but I will use the [docs](https://react.semantic-ui.com/addons/radio/) for example).
2. Now click to toggle the radio off and note the coloring and if it is the same as its initial state.
3. Click on a different part of the screen, or a different radio style and note the color.

### Expected Result
I would expect that the coloring stays the same as it was prior to toggling the radio on when you toggle the radio off.

### Actual Result
The radio was initially a light gray prior to toggling it on. When I toggled it off, it changed to a darker grey.

### Version
0.86.0 (and prior versions) 

### Testcase
[CodeSandbox](https://codesandbox.io/embed/4837j68l29)

**Comment by layershifter** [comment]
If I understand correctly, you it's an expected behavior because there are separate colors for focused state: https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/checkbox.less#L168

I.e. when you will click on a toggle it will receive focus, when you will click outside focus will be lost and colors will be changed.

**Comment by madyward** [comment]
@layershifter - that makes sense. Thanks for the clarification!
