### ISSUE TITLE
Restore default value in dropdown

### ISSUE THREAD

**Issue by mclarentgp** [Semantic-Org/Semantic-UI-React#362]
Just wondering if this is still possible as there is a way to do so in the js version.  And if it is possible are there examples to do so?

**Comment by levithomason** [comment]
I need more information to help you out here.  Can you provide some example code and the expected behavior?

Also, have you checked the [dropdown docs](http://technologyadvice.github.io/stardust/modules/dropdown), specifically the prop `defaultValue`?  This is a supported prop and works the same as vanilla React `defaultValue` on inputs.

**Comment by mclarentgp** [comment]
After further research ive discovered that the issue i was having was due to some of my own code.  I will close this issue.  Thanks for your time.

**Comment by levithomason** [comment]
Awesome, glad you found the fix.  Thanks for closing.
