### ISSUE TITLE
Docs: Theming instructions should work with Yarn Workspaces

### ISSUE THREAD

**Issue by ravgoundar** [Semantic-Org/Semantic-UI-React#3674]
### Steps
I have followed the [instructions](https://react.semantic-ui.com/theming) to set up theming with Create React App. My app is set up using the following structure using Yarn Workspaces:

| app
--| node_modules
--| packages
----| web
------| semantic-ui
------| craco.config.js

### Expected Result
Theme variables and overrides should work the way they do when not using Yarn Workspaces.

### Actual Result
semantic-ui-less in the Workspace root folder does not read the theme overrides set in the web folder. It does work if I copy the semantic-ui-less folder from app/node_modules and paste into app/packages/web/node_modules. However, this folder is deleted whenever I run yarn install.

### Version
"semantic-ui-less": "^2.4.1"

**Comment by layershifter** [comment]
Yarn Workspaces and actually monorepo setup are exclusions for a common use case and I am not sure that we should cover it in regular docs 🤔

**Comment by JamesYFC** [comment]
To fix this, you could use the [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) property of yarn workspaces, which keeps the package in the relevant child project's `node_modules` rather than the root's:

For example, this is the workspaces part of my updated root `package.json`:
```json
"workspaces": {
    "packages": ["my-app"],
    "nohoist": ["my-app/fomantic-ui-less"]
}
```
(use "**/fomantic-ui-less" if you need it to work in every package)

Then delete your `node_modules` folder and run `yarn install`.

@layershifter It would be great if we could get at least a small note in the docs for this case to save users debugging time, especially seeing as workspaces has been out for a while now and use of monorepos seems to be on the rise.

**Comment by calbrecht** [comment]
Found out you don't need to `nohoist` and copy. Just prefix more `../` followed by the package you are developing.

**Comment by brianespinosa** [comment]
Closing this issue for now. [Technically CRA is still not supported in a monorepo configuration](https://github.com/facebook/create-react-app/issues/1333). It is possible... I do this in a number of monorepo projects... but it requires a lot of understanding of the build pipeline. And since it is not supported by CRA, these configurations could break at any time.
