### ISSUE TITLE
Using Link from react-router-dom inside Modal

### ISSUE THREAD

**Issue by ktaras** [Semantic-Org/Semantic-UI-React#3696]
## Bug Report

Using `<Link>` component from `react-router-dom` (5.0.0) inside `<Modal>` component causes an error: `You should not use <Link> outside a <Router>`

`Modal` component is appended at the end of `<body>` and outside of a `<Router>` component, so `react-router-dom` throws the error.

### Steps
```
import React from 'react'
import { Modal } from 'semantic-ui-react'
import { Link } from 'react-router-dom'

const ModalModalExample = () => (
  <Modal>
    <Link to='...'>...</Link>
  </Modal>
)

```

### Expected Result
There should be no errors.

### Actual Result
Error:
```
You should not use <Link> outside a <Router>
```

### Version
0.80.2 but probably is valid for the lates version too.

**Comment by AntoniosProvidakis** [comment]
@ktaras 

Why do you expect no errors?
You already said it yourself: you have placed Link outside of a Router component.

**Comment by layershifter** [comment]
`0.80.2` is very old version, it was released more than a year ago.
You have this issue because `Portal` in that version uses deprecated `ReactDOM.unstable_renderSubtreeIntoContainer()` and it's not compatible with modern Context API. So, please upgrade ⚙️ 

It's not reproducible on latest version:
https://codesandbox.io/s/semantic-ui-react-example-8pll9
