### ISSUE TITLE
Popper shift modifier isn't working

### ISSUE THREAD

**Issue by pinikeizman** [Semantic-Org/Semantic-UI-React#3705]
## Bug Report
Popper.js defines the [shift](https://popper.js.org/popper-documentation.html#modifiers..shift) modifier which implements the popper [placment variations](https://popper.js.org/popper-documentation.html#Popper.placements) functionality and it doesn't implement in Popup component.
The reason for this issue is simple, Pupup is not mapping the 'left top', etc. in the position mapping, I don't mind to open a PR which enhance this list to handle all the possibilities. 
### Steps
Pass left-start and enable shift modifier.
### Expected Result
The popup should appear on the top left corner of the anchor.

### Actual Result
The popup appears in the top middle (default) of the anchor.

### Version
latest

### Testcase
https://codesandbox.io/embed/semantic-ui-react-1kz1k

**Comment by layershifter** [comment]
```
Warning: Failed prop type: Invalid prop `position` of value `left-start` supplied to `Popup`, expected one of ["top center","top left","top right","bottom center","bottom left","bottom right","right center","left center"].`
```

You have passed unsupported position, we have different position set due limitations of existing CSS.

**Comment by pinikeizman** [comment]
@layershifter That is the reason I've opened this bug report. We have wide use of Semantic UI React in our react system and we have use cases in which our Popup should open to the left top of the target, Does the package support this position or will support it in the future? This is supported by Popper.js with the `placement: top-start` and the shift modifier enabled.

**Comment by layershifter** [comment]
We have own position mapping to match SUI CSS otherwise pointer indicator will be broken. See:
https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.87.3/src/modules/Popup/lib/positions.js And some of `Popper` positions are not supported.

This mentioned in our docs:
![image](https://user-images.githubusercontent.com/14183168/61282228-429fc280-a7bb-11e9-994f-35315d9f8653.png)
https://react.semantic-ui.com/modules/popup/#variations-position

***

SUIR `top left` matches `top-start` from `Popper` so you should pass `top left` to our `Popup` component.

```jsx
<Popup
  position="top left"
  popperModifiers={{ shift: { enabled: true } }}
/>
```

BTW, `shift` is enabled by default: https://popper.js.org/popper-documentation.html#modifiers..shift.enabled

**Comment by pinikeizman** [comment]
@layershifter in my previous comment I mistakenly wrote `placement: top-start` but I actually meant `left-start`, Are you going to support this placement?

**Comment by layershifter** [comment]
> Are you going to support this placement?

No, because there are no proper CSS for that position in SUI CSS 😭 

https://semantic-ui.com/modules/popup.html#positioning

Sorry, but I was not able to understand your issue from the beginning.

**Comment by pinikeizman** [comment]
OK, thanks for your quick and helpful response! 👍
