### ISSUE TITLE
modal dialogs not centered any more

### ISSUE THREAD

**Issue by Seharad** [Semantic-Org/Semantic-UI-React#3714]
upgraded from 0.87.2 to 0.87.3
<Modal> component is no longer centered on the screen when using Internet Explorer. Has worked great with 0.87.2

**Comment by layershifter** [comment]
Positioning was fixed in https://github.com/Semantic-Org/Semantic-UI-React/pull/3679. Actually this PR fixed https://github.com/Semantic-Org/Semantic-UI-React/issues/3388 because previously positioning was really broken.

Please provide more details and repro, probably you're using outdated version of SUI. Tested on doc site, works perfectly:

![image](https://user-images.githubusercontent.com/14183168/61630406-eee41c00-ac87-11e9-9257-6d8296ed8066.png)

**Comment by Seharad** [comment]
Thank you for your prompt reply. A quick-fix for semantic-ui-less caused the error. Thanks for the hint.

**Comment by sliebner** [comment]
> quick-fix for semantic-ui-less

Do you remember what you had to change to make this work again?

**Comment by dguo** [comment]
@sliebner I was able to resolve the issue by upgrading the version of Semantic UI that I was using to 2.4.1 (the latest).
