### ISSUE TITLE
Popup: wrong positioning when `mountNode` uses `position: fixed`

### ISSUE THREAD

**Issue by twens** [Semantic-Org/Semantic-UI-React#3718]
### Steps
-add Popup control
-set mountNode property

### Expected Result
Popup should be renderer in a set node and visually be placed there

### Actual Result
Popup is rendered in a set node but visually is NOT placed there
It is placed far away outside
Wrong calculation of `transform` css value

### Version
0.87.3

In the version 0.86.0 all is ok

**Comment by petemahoney** [comment]
I was having a problem as well with the popup - the position of the popup was showing up over top of my content instead of `center left` where the `position` prop I had set up was telling to go.  The popup also didn't seem to "pop up" at the right time and place in response to the mouse hover.  I backed off to 0.86.0 and the problem goes away.  Hope this problem can be fixed - affects a lot of my components and UI - assume others would agree.

**Comment by petemahoney** [comment]
I'll add that this seemed to only affect popups that were positioned to the left (center left was my use case).  Those that were positioned to the right seemed to still work just fine.

**Comment by layershifter** [comment]
@twens @petemahoney please provide a minimal CodeSandbox with clear repro steps. I tried to reproduce the issue, but I failed 🤔  See my try: https://codesandbox.io/s/semantic-ui-react-example-ql988

I don't see visible reasons why it should fail because `mountNode` sets only place in DOM. Do you have specific styles on it?

**Comment by fxOne** [comment]
I don't know if this is the same issue, but I have some issues if the `mountNode` is a Node wich ist styled with `position: fixed;`

Here is my excample: https://codesandbox.io/s/semantic-ui-react-example-umbkj

**Comment by layershifter** [comment]
@fxOne you're are passing `null` to `mountNode` prop in your example. So it will be default.

```jsx
<Popup
  mountNode={ref.current} // is `null`
```

---

### 0.86.0

![image](https://user-images.githubusercontent.com/14183168/63424745-6041f680-c40f-11e9-8587-e44662bfcf9a.png)

### 0.87.3

![image](https://user-images.githubusercontent.com/14183168/63424779-72bc3000-c40f-11e9-911f-fbc06f8089b1.png)

As I see, the issue is an arrow position. Are there other issues?

**Comment by fxOne** [comment]
I don't think that `ref.current` is null because if i don't set it via `<div ref={ref}` I will get errors from ´<PortalInner> component´.

**Comment by layershifter** [comment]
@fxOne it's null, refs are set in the commit phase of React, https://stackoverflow.com/a/55248699/6488546.
***
![image](https://user-images.githubusercontent.com/14183168/63443800-bc1f7600-c435-11e9-868c-b756fb10efa8.png)
https://codesandbox.io/s/semantic-ui-react-example-n07mv

**Comment by fxOne** [comment]
Of course it is null in the beginning, but after I clicked trigger it is no longer null. 
![Unbenannt](https://user-images.githubusercontent.com/5929640/63444475-f76e7480-c436-11e9-9c75-a5bf9fe01a0a.PNG)

I'm sorry if I don't understand React good because I'm really new. If my example is wrong can you please tell how i can set the `mountNode` correct?

**Comment by layershifter** [comment]
@fxOne Can you please explain what are you trying to do? 🤔 

Why you need to use `mountNode`? It was designed to be used as an exceptional case as it changes where `Popup`'s `content` will be mounted in DOM 📦

**Comment by fxOne** [comment]
We have a system where we use multiple style systems. To separate them we prefix the css with an id selector and put all the html into a div with the same id. 

An other use case should be [native modal dialogs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) where the dialog will always be above the page content. So the only solution is to move the popup into the modal dialog.

I solved my issue by not using a `position: fixed;` node as a `mountNode` after finding this issue which works perfect. I only thought that I had the same issue and could provide a sample.

**Comment by layershifter** [comment]
@fxOne got it, thank you.

I created a clean repro of the issue: https://codesandbox.io/s/semantic-ui-react-example-n07mv. Thank you for the patience 🐱 

---

It looks like an issue with `Popper.JS`, as I was to reproduce it in plain usage: https://codesandbox.io/s/dazzling-tharp-rej7h. And it seems that it's related to https://github.com/FezVrasta/popper.js/issues/670.

However, `positionFixed` solved the issue: https://popper.js.org/popper-documentation.html#Popper.Defaults.positionFixed.

I tested it on https://codesandbox.io/s/semantic-ui-react-example-3sq5m, the arrow still has wrong position, but `Popup` itself is positioned properly. Can you please check?

**Comment by fxOne** [comment]
@layershifter yes, this works. Thanks for your help!

**Comment by layershifter** [comment]
Great, going to introduce `positionFixed` prop for `Popup` component to solve such issues 🐰 

However, @fxOne may be you want to contribute? ⭐️ You can use `eventsEnabled` prop in `Popup` as reference...

**Comment by fxOne** [comment]
@layershifter I'll try it this weekend.
