### ISSUE TITLE
Invalid argument supplied to oneOf, expected an instance of array.

### ISSUE THREAD

**Issue by Johnsel** [Semantic-Org/Semantic-UI-React#375]
I have this code:
`<Menu.Item label={<FormattedMessage {...linksMessages.inspections} />} href="/inspections" />`

The label works, but the console shows an error:
`warning.js?8a56:44 Warning: Invalid argument supplied to oneOf, expected an instance of array.
warning @   warning.js?8a56:44
createEnumTypeChecker   @   ReactPropTypes.js?3c83:214
(anonymous function)    @   Label.js?9d70:181`

Where Label.js:70:181 equals

`/** Size of the label. */
  size: _react.PropTypes.oneOf(Label._meta.props.sizes),`

`Label._meta = {
 ...,
  props: {
   ...
    size: sui.sizes,
   ....`

`var _semanticUtils = require('../../utils/semanticUtils');`

`var sui = _interopRequireWildcard(_semanticUtils);`

Any clues as to why this doesn't resolve properly?

**Comment by Johnsel** [comment]
Tested with a plain string value for "label" just now, same behavior

**Comment by levithomason** [comment]
yep, the propType arg points to `_meta.props.sizes` instead of `_meta.props.size`.  I fixed this [here](https://github.com/TechnologyAdvice/stardust/commit/b2fe3bb38bf76559733e1dc7e94c312d55d82172#diff-fde3c67bba82fd0efc2088a5fe1a4686R158) in the PR to support React 15.3.0 (#374) but hadn't made a release yet.

Released just now in `v0.28.1`, thanks!
