### ISSUE TITLE
Icons are missing ?

### ISSUE THREAD

**Issue by DouggyC** [Semantic-Org/Semantic-UI-React#3798]
### Steps
```
<Container>
  <List>
       <Icon color="red" name="users" />
       <p>User</p>
       <List.Item color="pink" icon="check">
         <p>Check</p>
       </List.Item>
   </List>
</Container>
```

Codesandbox example also does not show icons
https://codesandbox.io/s/vibrant-jennings-lzz2h

### Expected Result
Icons should appear automatically

### Actual Result
Icons missing ????? showing square box placeholder

### Version
0.88.1

### Testcase
https://codesandbox.io/s/vibrant-jennings-lzz2h

**Comment by DouggyC** [comment]
@levithomason @jlukic

**Comment by MiceXx** [comment]
You forgot to include the semantic-ui-css files.
`
npm install semantic-ui-css
`

Then add to the top of your index.js
`
import 'semantic-ui-css/semantic.min.css';
`

Or you can use the cdn: 
`
const styleLink = document.createElement("link");
styleLink.rel = "stylesheet";
styleLink.href =
  "https://cdn.jsdelivr.net/npm/semantic-ui/dist/semantic.min.css";
document.head.appendChild(styleLink);
`

Regarding your list element, it works when you take the icon out of the props and just pass it as a child component. (Note: color is not a valid <List.Item> prop)

See https://codesandbox.io/s/cranky-newton-tgfyl

**Comment by brianespinosa** [comment]
Thanks @MiceXx 

@DouggyC I am going to go ahead and close this based on the above solution.

**Comment by DouggyC** [comment]
I did as followed, but not working. : ( 
https://codesandbox.io/s/focused-wilson-fvgrw

Only worked when using cdn method:
```
Or you can use the cdn:
const styleLink = document.createElement("link"); styleLink.rel = "stylesheet"; styleLink.href = "https://cdn.jsdelivr.net/npm/semantic-ui/dist/semantic.min.css"; document.head.appendChild(styleLink);
```

However in my dev project I found that the icon tag was begin over written by font-family, 
and had to specifically ignore the <i> tag using :not() selector.
But cannot reproduce it on codesandbox.

**Comment by brianespinosa** [comment]
@DouggyC what is the CSS rule that was overriding the `font-family` property? Was it a class in your project coming from other CSS? This sounds like a CSS specificity issue and not related to SUIR or SUI.

**Comment by scottsandersdev** [comment]
@brianespinosa @MiceXx I'm having the same problems that @DouggyC  was having. If you click on DouggyC's codesandbox above it's a pretty good use case of how I imaging many people are using semantic ui react, and the icons are not showing. If you comment out the document.createElement("link") bit it will work, but that sure shouldn't be necessary. Is there another way to fix this?

**Comment by brianespinosa** [comment]
@scottsandersdev it is just one use case. If an icon is not present, it means that icon is not present in the font that the CSS you are using is pointing to. This could be an issue with:

- The version of the CSS you are using in your project has an older version of FontAwesome
- Your toolchain is not configured correctly to handle a font
- Lots of other toolchain bundler issues (missing loaders, bad configurations)
- Incorrect file path to the font files
- Missing font files

All of the above items are not anything we have control over in SUIR. If anyone has an issue with missing icons and you're doing something outside of the recommended steps, it is completely possible to get things working... but based on the permutations of what might be going on in all of these other scenarios, we can't really cover everything here.

All SUIR does from a styling perspective is let you specify props which will generate the correct classnames and markup structure for compiled CSS to work.

If you want to ask a question on StackOverflow about how to get this working, I am happy to help there. Please include information about your toolchain configuration and versions of SUIR and CSS being used.

**Comment by dawei-dai-exa** [comment]
Exactly the same issue I'm having here. 

With all else equal, if I load css this way,
import "semantic-ui-css/semantic.min.css";  //"semantic-ui-css": "^2.4.1",

Icon is not showing

If I load css from external cdn like this way:
styleLink.href =
 "https://cdn.jsdelivr.net/npm/semantic-ui/dist/semantic.min.css";

Icon is showing

Shouldn't they be the same? @brianespinosa

**Comment by brianespinosa** [comment]
@dawei-dai-exa not necessarily. 

Look at the CDN you are getting the CSS from. Where does the `@font-face` declaration say the path is for the font files? There is no guarantee that the CSS has the same path for everyone, as it is configurable from SUI's CSS build tools. Some CDNs might have set their compile of CSS up to also distribute the font files via CDN instead of locally.

The CDN you are using is expecting those font files to be local:
```
@font-face{font-family:Icons;src:url(themes/default/assets/fonts/icons.eot);src:url(themes/default/assets/fonts/icons.eot?#iefix)
```

So, if you don't have font files at that path, then they will not work.

Again... these are all variables that are inconsistent, not within our control, and for code that does not exist in the Semantic UI React repository.

**Comment by kitnato** [comment]
There wasn't enough information in any of the SUIR docs for me to understand why this issue was occurring when locally importing the minified CSS.

The problem is when importing the CSS locally, any icon paths will try to resolve locally too, but relative to where `semantic-ui-css` is installed - and since the files live in `node_modules` and not in your public folder, `http://yourdomain/themes/default/assets/fonts/icons.woff2` doesn't point anywhere and therefore fails to load anything. This is avoided by using the CDN instead since it resolves URLs instead of local file paths. However, if you want the icon assets to be bundled with your app, this isn't really a solution.

My solution was to **copy the entire `themes` folder from `node_modules/semantic-ui-css` into the app's public folder**. That way all paths resolve. This adds about 2MB to the app's payload though! This seems to be more or less in line with manually installing [Font Awesome](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers) via NPM (although since they use a different folder structure and file names, this wouldn't work with SUIR as far as I can tell).

EDIT: if you're only using a specific subset of icons (e.g. brand icons, outline icons etc.) you can delete all the other files and types that won't be used in your app, cutting down quite a bit on payload.

If anyone has found a less clunky way to use SUIR FA icons locally, I'm all ears.
