### ISSUE TITLE
search placeholder is implemented but not documented

### ISSUE THREAD

**Issue by mohammadavood** [Semantic-Org/Semantic-UI-React#3806]
hi.
in "react semantic ui" document
search placeholder API is not documented while is implemented for component
please add
tnx

**Comment by sohamsshah** [comment]
@mohammadavood I would like to work on this issue. Please assign me...

**Comment by Leomedina** [comment]
Hi, I'm a new developer and would the chance to work on this issue.

**Comment by nrj-kr** [comment]
Do assign me this issue. Together,we can complete the issue in minimal time

**Comment by shazm12** [comment]
Please assign me this issue.I want this to be my issue.

**Comment by sohamsshah** [comment]
@shazm12 My issue is my issue, none of your issue🤣 (anyways man you can start working on this, I am a bit busy this week. In the end our goal is to make this project good! So let me know if you face any roadblocks, and if you want you we can divide and work together too! Let me know so that I can share my contact w you; would love to collaborate!)

**Comment by RgnDunes** [comment]
Hey bro, I think I can resolve this issue as I've previously used Semantic UI with react once. So it would be great if you could assign it to me.

**Comment by rohanrav** [comment]
Hey!

I made a PR (#4282) that addresses this issue. I wasn't exactly sure what the action items were - so please feel free to check it out and let me know if there is stuff I should change!
