### ISSUE TITLE
I'm getting `Unexpected token` when I'm running the `npm run build:dist` on custom branch

### ISSUE THREAD

**Issue by asiniy** [Semantic-Org/Semantic-UI-React#381]
Kinda strange thing happens here. I specify custom branch of stardust in package.json:

```
"stardust": "asiniy/stardust#controlled-modal",
```

and then running `npm install && npm run build:dist` in the `node_modules/stardust` of my project. I'm getting `unexpected token`:

```
> stardust@0.29.0 prebuild:dist /my_project/node_modules/stardust
> rimraf dist


> stardust@0.29.0 build:dist /my_project/node_modules/stardust
> babel src -d dist

SyntaxError: src/addons/Confirm/Confirm.js: Unexpected token (10:19)
   8 | 
   9 | export default class Confirm extends Component {
> 10 |   static propTypes = {
     |                                  ^
  11 |     abortLabel: PropTypes.string,
  12 |     confirmLabel: PropTypes.string,
  13 |     header: PropTypes.string,
```

What's the hell?

**Comment by dvdzkwsk** [comment]
Do you have a `.babelrc` higher up in the project directory? Babel will merge configurations as it moves up the directory tree, which can lead to weird issues like this. If you do, try temporarily renaming/deleting it and then see if that changes the result. If it still doesn't work, we can look into it further.

Of course, this is not so much a solution as a diagnosis, so that will have to be considered.

**Comment by levithomason** [comment]
Looks like you're missing the babel preset that includes class properties. Try running npm install again. 

Also, just in case, make sure you have have node 6 per the CONTRIBUTING.md.

**Comment by levithomason** [comment]
bump

**Comment by levithomason** [comment]
bump @asiniy
