### ISSUE TITLE
Popup does not work with `div` as trigger

### ISSUE THREAD

**Issue by euvs** [Semantic-Org/Semantic-UI-React#3825]
### Steps
Popup does not behave correctly when trigger component is `div` 

### Expected Result
Popup to appear

### Actual Result
Popup is flashing and not appearing correctly

### Version
0.88.1

### Testcase
Please see the code sandbox for reproduction.

https://codesandbox.io/s/semantic-ui-react-9vx6p?fontsize=14

**Comment by brianespinosa** [comment]
Hi @euvs!

The issue is not due to a popup being attached to a div. There are lots of places in SUIR that a popup works attached to a div.

The problem in your example is you are trying to attach a popup that is being forced to appear outside of the viewport. Your div that contains the text runs the full width of your container. That means the popup is trying to render itself on the far right side of your container... which places it out of the viewport.

This is also why your div that has `display: inline-block` is working correctly since you are forcing the div to only take up the space of the content inside of it.

To see this in action, I took these divs and reduced the size of the parent container to limit it from taking the full viewport and you will see the div works now because it is attaching on the far right side of the div as you have configured.

If you want the popup to specifically target the size of some content inside of a div, and not the full width of the div, you would want to wrap your specific content inside of a span (default `display: inline`), or a div with `display: inline-block`

https://codesandbox.io/s/semantic-ui-react-kxrvo
