### ISSUE TITLE
Error: `debug is not a function` when using Jest mocking

### ISSUE THREAD

**Issue by dylankiss** [Semantic-Org/Semantic-UI-React#386]
![debug-error](https://cloud.githubusercontent.com/assets/5985577/17583081/804c0546-5faf-11e6-879b-9735285a9f84.png)

When using Stardust in a project that uses Jest for testing (which auto-mocks the Stardust components), we get this error concerning the `debug` function in `jquery.js`. The reason for this seems to be that the debug statements in `jquery.js` are executed, but the `debug` module does not load the debugger because of the `process.env.NODE_ENV !== 'test'` check.

**Comment by levithomason** [comment]
This must be due to another issue as the `else` branch of that logic assigns a `noop` function:

``` js
if (process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'test') {
  debug = require('debug')
  ...
} else {
  debug = () => noop
}
```

So, `debug` is always a function, even in production and tests.  I'm not sure what Jest is doing since we don't use it.  Though, I loosely recall something like `jest.dontMock()` which you may need to use.  This should be safe since, we've essentially already mocked it by returning a `noop`.

If this doesn't solve it, feel free to comment and I'll reconsider it.
