### ISSUE TITLE
Add your support for React Json Schema Form

### ISSUE THREAD

**Issue by jacqueswho** [Semantic-Org/Semantic-UI-React#3861]
### Problem description
No problem just a suggestion

### Proposed solution
Would you be interested in supporting [React JSON Schema Form](https://github.com/rjsf-team/react-jsonschema-form), to include your library as well? They currently support Material UI, I could include your library but would you continue to maintain it?

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by jacqueswho** [comment]
Have not heard anything yet

**Comment by MonkeyAlex** [comment]
Hi @jacqueswho ,

Here are some of the packages that ported **React JSON Schema Form** for Semantic UI.

https://www.npmjs.com/package/react-jsonschema-form-semanticui
https://www.npmjs.com/package/react-jsonschema-form-semanticui-fixed
https://www.npmjs.com/package/@naveego/react-jsonschema-form-semantic

However they are all at least 1 year old so most likely not up-to-date.

What's your plan?
What would you do differently from these existing packages?

I'm keen to know because I'm using one of them in one of my projects.

**Comment by jacqueswho** [comment]
hi @MonkeyAlex 

Here is the [issue request](https://github.com/rjsf-team/react-jsonschema-form/issues/1537) I logged on their repo.

So we make use of their withTheme() component. We include the package just as rjsf-material-ui did. I will create a merge request to include in [packages](https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages) one for semantic-ui. You could look at it and give any input, also assist with the readme. 

The problem with those repos you mentioned is they don't make use of the core of react-json-schema, so they fall behind on changes. With this approach, it's in one place and will be updated with the core.

**Comment by MonkeyAlex** [comment]
Thanks for the explanation.
It would be great to have a package that is up-to-date with the mainstream react-json-schema
so we don't miss out on bug fixes and new features.

**Comment by jacqueswho** [comment]
@MonkeyAlex please see my [pull request](https://github.com/rjsf-team/react-jsonschema-form/pull/1585). have a look and let me know what needs to be changed and whatever you wish to add. Semantic UI needs to give their input and help make this happen

**Comment by jacqueswho** [comment]
@MonkeyAlex the [release ](https://github.com/rjsf-team/react-jsonschema-form/tree/master/packages/semantic-ui)is coming soon.
