### ISSUE TITLE
Long text flows outside of label attached to image

### ISSUE THREAD

**Issue by kwayebopp** [Semantic-Org/Semantic-UI-React#3862]
### Steps
 Create an Image with a label attached to it. This is the component that is giving me the text sitting outside the label. 

```
    <Image
      size="tiny"
      circular
      src={imageSource}
      label={{
        attached: "bottom",
        basic: true,
        circular: true,
        content: "Luke Groundwalker"
      }}
    />
```

### Expected Result
I expected the text to sit completely within the label

### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/12959564/70544185-ab585480-1b39-11ea-9307-978fed29bd07.png)

### Version
0.88.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-4950g?fontsize=14

**Comment by levithomason** [comment]
Thanks for using SUIR!  This is a CSS bug and would be fixed in https://github.com/Semantic-Org/Semantic-UI which is the main repo where styles are stored.

In the meantime, I would likely add a custom style that targeted `.ui-label` and extended the styles with the look you after.

A more appropriate fix would be to use a custom theme that implemented the styles you preferred.  You can see more on that here: https://react.semantic-ui.com/theming.
