### ISSUE TITLE
Searchable Dropdown Not Clearable

### ISSUE THREAD

**Issue by mendeel** [Semantic-Org/Semantic-UI-React#3869]
## Bug Report
Hello, guys! So, I'm loving using Semantic UI for React, great job! I created a modal with searchable dropdowns with the "search" property but using this makes it so the "clearable" property has no effect. The "X" is appears but you can't click it as it just opens the menu like the rest of the element.

### Steps
Create a Dropdown element with "clearable" prop.

### Expected Result
You should be able to clear the dropdown.

### Actual Result
The entire dropdown element is clickable for opening the menu and the "X" icon has no effect.

### Version
0.88.2

### Testcase
https://codesandbox.io/s/vigilant-haslett-1ez9p

Can I also link a GIF here so you can see what happens?
https://imgur.com/a/80ej6EI

**Comment by vinicz** [comment]
For anyone, who is still facing this issue, a possible workaround is to change the `z-index` of the icon, like of you use styled-components, here is an example:
```
export const StyledDropDown = styled(Dropdown)`
  &&&& {
    .icon {
      z-index: 2;
    }
  }
`;
```

**Comment by brianespinosa** [comment]
@mendeel thank you for the report. This does appear to also be present in Semantic UI parent CSS files. @vinicz made a good suggestion on how this can be resolved by applying a z-index to the clickable icon itself. Since this is due to CSS in the parent SUI project, I am closing the issue with the above workaround noted. Please feel free to open an issue on the parent Semantic UI project for the issue with CSS.

**Comment by DamodarSojka** [comment]
Maybe it's worth considering adding a note in the docs.
