### ISSUE TITLE
Form.Field's error prop not working if the Input is its child (rather than itself)

### ISSUE THREAD

**Issue by Menci** [Semantic-Org/Semantic-UI-React#3872]
### Steps
Replace `<Form.Input>` with `<Form.Field><Input>`, the error prop on `Form.Field` is not working.

I can't use `<Form.Input>` because I need the input's `ref`.

### Expected Result
It works like a `<Form.Field control={Input}>` or `<Form.Input>`

### Actual Result
The error message is not shown. And a warning comes to the console:

```
Warning: Failed prop type: Invalid prop `error` supplied to `FormField`.
    in FormField (created by App)
    in App
```

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-ogm7p

**Comment by sholladay** [comment]
I agree it would be nice if your example worked as expected, but I think this has to do with how SUIR handles children. It looks like a more general issue.

For example, this doesn't show an input box at all, because we are giving a `label` to the field, which seems to take precedence over children:

```jsx
<Form.Field
    label="foo"
>
    <Input
        fluid
        icon="user"
        iconPosition="left"
    />
</Form.Field>
```

I guess for some reason `error` gets overridden by children instead of taking precedence. But the point is, it seems that we have to choose one way or the other: either provide children or provide props that create children. It looks like mixing and matching isn't possible.

I was able to fix your original example by doing this:

```jsx
<Form.Input
    error={{
        content: "error",
        pointing: "below"
    }}
    input={
        <Input
            fluid
            icon="user"
            iconPosition="left"
        />
    }
/>
```

**Comment by layershifter** [comment]
Actually the easiest way to obtain `ref` to `input` in `Form.Input` will be `<Form.Input input={{ ref }} />`. See CodeSandbox: https://codesandbox.io/s/semantic-ui-react-5yo5e?file=/index.js

**Comment by sholladay** [comment]
It's interesting that this works:

```js
<Form.Input
    error={{
        content: "error",
        pointing: "below"
    }}
    icon="user"
    iconPosition="left"
    input={{ ref: node => console.log(node) }}
/>
```

But this does not work (icon doesn't appear in the input):

```js
<Form.Input
    error={{
        content: "error",
        pointing: "below"
    }}
    input={{
        icon: "user",
        iconPosition: "left",
        ref: node => console.log(node)
    }}
/>
```

That's kind of hard to deduce from the documentation.

**Comment by layershifter** [comment]
> That's kind of hard to deduce from the documentation.

@sholladay do you have any suggestions how we can improve it?

**Comment by sholladay** [comment]
I'm not sure I entirely understand why the latter doesn't show the icon. Maybe the documentation should just recommend to pass everything to `Form.Input` directly instead of using the `input` prop whenever possible, and then mention `ref` as an exception?
