### ISSUE TITLE
Is maintenance for this package stopping? 

### ISSUE THREAD

**Issue by cam31007** [Semantic-Org/Semantic-UI-React#3885]
I was just wondering if there are further plans to continue maintaining this package? It has been almost 40 days since the last code merge, and I don't see much feedback from the authors on PRs and issues reported. I just want to figure if it's worth opening pull requests for new features/bugs, or if I should just fork instead. Since other semantic-ui projects seem to be dying, was wondering if this project was under the same path?

Thanks!

**Comment by reohjs** [comment]
Seems development focus moved here: https://github.com/microsoft/fluent-ui-react

**Comment by levithomason** [comment]
Hello folks, SUIR is not dead but is certainly slow and in more of a maintenance mode.  My focus is on Fluent UI at Microsoft at the moment.  Fluent UI started as a fork of Semantic UI React and underwent a lot of changes to support some enterprise needs.  The current evolution is now to merge its concepts and capabilities with Microsoft's other UI solution, UI Fabric.  I am very excited about the things we are targeting for this year under the new Fluent UI banner and will continue putting the majority of my effort there as architect.

For SUIR here, I will continue to address PRs, mostly those that are raised to me in email or messaging systems.  I will continue merging and releasing fixes at this pace until Fluent UI is further along it its mission.

Fluent UI plans to release tools and resources for improving open source projects like SUIR.  Once we get those tools out, I'd love to come back to SUIR and incorporate them and potentially resume some development.

Jack (Semantic Org founder) and I have remained in contact about SUIR and future goals.  We both have an interest in continuing open source UI work.  Right now, the majority of that focus is not on Semantic's iteration though.

**Comment by posita** [comment]
Thanks for the update, @levithomason. I have some follow-up questions:

1. Just based on the demos, it seems like Fluent lacks a lot of the polish (or at least browser compatibility?) that Semantic had. For example, compare [Semantic's Buttons](https://react.semantic-ui.com/elements/button/#types-button) (which are _**gorgeous**_) to [Fluent's button twiddler](https://fluentsite.z22.web.core.windows.net/components/button/definition) (screenshots below). Is my impression accurate?
1. It also seems like Fluent will be more of a plain vanilla UI component library (like Bootstrap) rather than having some unique gems like Semantic did. Is that fair? Can you comment on the differences in vision, particularly why someone would want to invest in Fluent over (e.g.) Bootstrap or Material UI, especially at this stage?
1. This project's README says, "Hey, **_we're in development_**. Prior to reaching [v1.0.0](https://github.com/Semantic-Org/Semantic-UI-React/milestone/1): …" (_**emphasis**_ mine). This no longer appears accurate. Has v1.0.0 development been abandoned? If not, can you at least update your most prominent surfaces (like your top-level README and https://react.semantic-ui.com/) to more accurately reflect [your comment above](https://github.com/Semantic-Org/Semantic-UI-React/issues/3885#issuecomment-603537041)? Right now those other surfaces seem misleading in light of this thread. FWIW, I spent about 5 minutes digging around to figure out the _**real**_ state of this project. Luckily I had some idea where to look. Others may not be so lucky and may take longer or miss this altogether.
1. Based on your work so far, do you see a straightforward migration path from Semantic to Fluent, or would that be more of a component-by-component rewrite for clients?

---
### Screenshots

#### Semantic 🤩

![semantic_button](https://user-images.githubusercontent.com/222581/85229229-65f4c980-b39d-11ea-8721-06889a9b2321.jpg)

#### Fluent 😞

![fluent_button](https://user-images.githubusercontent.com/222581/85229119-dea75600-b39c-11ea-94bd-58cbfd262335.jpg)

**Comment by villuv** [comment]
@posita also please check out this thread about Fluent / Fabric licensing https://github.com/microsoft/fluentui/issues/12488
Depending on your requirements this might be a showstopper for you. At least it is for us for the time being.

**Comment by posita** [comment]
Thanks @villuv! I think what I now understand is that this project is dead, but my advice is to make that clearer on landing surfaces. If my understanding is correct, by _**not**_ updating those surfaces, it misleadingly gives the impression that bugs are still being fixed, roadmaps are still being followed, PRs are still being accepted, etc.

#3980 was submitted a mere 12 days ago. I wonder if its author has any hope of receiving any attention on that?

**Comment by layershifter** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v1.0.0
https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v1.1.0

---



> #3980 was submitted a mere 12 days ago. I wonder if its author has any hope of receiving any attention on that?

Was released in `1.0.0`.
