### ISSUE TITLE
Vertical Divider inside a Grid doesn't collapse

### ISSUE THREAD

**Issue by aforty** [Semantic-Org/Semantic-UI-React#3912]
## Bug Report

I'm referring to this example: https://react.semantic-ui.com/elements/divider/#types-vertical-form

It says: A vertical divider will automatically swap to a horizontal divider at mobile resolutions when used inside a `stackable` `Grid`.

This example doesn't work however, when I change the window size the divider just sits in the middle of the grid (see screenshot). Also I find the wording a bit confusing "when used *inside* a stackable Grid" it's not really inside at all, it's outside the Grid but somehow shows inside it which seems a little magical and strange.

![Screen Shot 2020-03-19 at 12 27 11 PM](https://user-images.githubusercontent.com/523683/77090161-2359d480-69dd-11ea-8191-5cca1d35e2c9.png)

**Comment by brianespinosa** [comment]
Verified that this issue exists... however, this is an issue with the CSS files from Semantic UI. This issue is present in the [SUI docs which can be seen here](https://semantic-ui.com/elements/divider.html#vertical-divider).

There is a report already open for this issue there: https://github.com/Semantic-Org/Semantic-UI/issues/6637
