### ISSUE TITLE
The docs (https://react.semantic-ui.com) cause excessive CPU usage in Chrome

### ISSUE THREAD

**Issue by webdestroya** [Semantic-Org/Semantic-UI-React#3978]
## Bug Report

NOTE: Issue #3784 was accidentally closed (the PR to close was a README fix, so no way it solved the issue). This is a direct copy/paste from #3784 as this issue still persists (Sitting on the docs for semantic-ui easily causes 50% cpu usage)

### Steps
Use Chrome to open the documentation pages for any component which contains examples

### Expected Result
Chrome should not use more CPU than with other similar sites

### Actual Result
According to Chrome's dev tools, the Rendering task "Recalculate Styles" runs continuously.
After a few moments my laptops fan kicks in and the laptop turns into a heater

### Version
0.88.2

### Screenshot
![Screenshot](https://user-images.githubusercontent.com/7063124/64792368-39d82c80-d571-11e9-884e-5a1fd50295f8.png)

**Comment by webdestroya** [comment]
Further investigation:

* if you load a page (I was on Checkbox docs) and stay on the top, the CPU holds at 40-45%. for as long as you stay there.
* if you scroll to the bottom, the CPU drops back to normal (0.7%). You must scroll all the way until you see "This is the bottom".

This makes me think it has something to do with the Visibility component? 

Staying on the top (or even just above the bottom) of a page will keep the CPU at 44% for as long as you remain there. As soon as you scroll to the bottom the CPU will jump for 1 tick, then go back to normal.

**Comment by knight-coder-llc** [comment]
I agree that the issue is with react-visibility-sensor: https://github.com/joshwnj/react-visibility-sensor/issues/79
the module uses a function call getBoudingClientRect forcing web engine to recalculate the layout the function is known to be expensive.
VisibilitySensor._this.check @ visibility-sensor.js:250, a timer is also implemented which executes this function to handle edge cases when events may not be triggered by the user creates a performance bottleneck.

![VisibilitySensor-dropdown](https://user-images.githubusercontent.com/29669260/87214764-8a3d2980-c2fd-11ea-9c10-10b9b748e86f.PNG)

**Comment by knight-coder-llc** [comment]
A possible fix could be to either remove the module and replace using intersection observer api: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API or look into improving the performance for that function call, it has been suggested to implement a caching system in some way. I think intersection observer api may be the less expensive way to go performance wise because it uses a registered callback to handle entrance and exit of the view port, instead of firing constantly.

**Comment by layershifter** [comment]
Thanks for catching this ❤️  `react-visibility-sensor` should be replaced with `react-intersection-observer`. PRs are welcome 👍

**Comment by knight-coder-llc** [comment]
I added the react-intersection-observer, to the docs ComponentExample and there is some notable differences in layout recalculations as seen from previous snapshots.
This is the Drop down component examples page. Looks like more scripting and less render calculations not sure if there needs to be more of a balance there or not?
![Dropdown-intersection-observer](https://user-images.githubusercontent.com/29669260/87268032-5c8be800-c497-11ea-846d-dda208c209ab.PNG)

Here is a snapshot of the form examples, I posted this for comparison with a form performance snapshot above in a previous comment. What I see here is the rendering calculations start to plane out which I think is what you are looking for without the continuous cycle.

![Form-observer](https://user-images.githubusercontent.com/29669260/87268243-ec319680-c497-11ea-9112-b8ea574c8a8a.PNG)

**Comment by inactivist** [comment]
> (Sitting on the docs for semantic-ui easily causes 50% cpu usage)

I'm seeing this on a regular basis even now.  I can always tell when I have a tab open & active on one of these pages, my notebook fan is humming along at a good clip.

![image](https://user-images.githubusercontent.com/1195074/104029952-7d4fa480-517f-11eb-91f7-a34657905248.png)

**Comment by msjonker** [comment]
Yeah, I'm seeing the same thing.
