### ISSUE TITLE
Lazy Loading for nested accordion

### ISSUE THREAD

**Issue by piu** [Semantic-Org/Semantic-UI-React#4032]
Hi,
I have used Nested Accordion (https://react.semantic-ui.com/modules/accordion/#advanced-nested) to achieve a treeview in my application. And as the Treeview data can be huge, so I don't want any performance issues for the same.
_Is there any way to achieve the lazy loading for Nested accordion tree view that can be 4/5 level deep as well ?_ 

Although I see some lazy loading feature available with Dropdown component. So is there any solution or suggestion how can I prevent performance issue with Nested accordion by adding some lazy loading.

**Comment by brianespinosa** [comment]
Hi @piu 

This is something you would need to do in your React application using controlled components instead of relying on auto handled state with Semantic UI React. You could set your components up with a handleLoad() function that gets called when they are in an open state. The complexities of this depend on how you have set up your application state and how you do your data fetching.

This is above the scope of this project though. The only components SUIR has that allow loading of data are Search and Dropdown/Select.

Your best bet is to ask this question on StackOverflow and share an example of what you want to achieve and what you have tried so far. We use these issues to track bug reports.
