### ISSUE TITLE
Form validation does not work on any elements except Form.Input

### ISSUE THREAD

**Issue by dandalgatov** [Semantic-Org/Semantic-UI-React#4057]
## Bug Report
I'm creating a form that has required checkboxes and dropdowns. When I add the required attribute to Form.Checkbox and Form.Select, I see the asterisks, but the form is not being validated, and I'm able to submit without filling out checkboxes or dropdowns. It does validate for text input.

**Comment by brianespinosa** [comment]
@dandalgatov there is no form validation on any SUIR forms. This is because there are all kinds of ways an end user might end up needing to validate a form based on their use case. Marking an input as required only lets the user know visually with added styles that the value is required. There is no validation that the input is not empty or that it matches a validation pattern. You'll need to set that up based on your use case.
