### ISSUE TITLE
Can't see Loader inside Modal

### ISSUE THREAD

**Issue by nidu** [Semantic-Org/Semantic-UI-React#4062]
### Steps
Use Loader inside Modal.

### Expected Result
Loader is visible.

### Actual Result
Loader is not visible.

Modal has white background but is placed on top of a dimmer.
Loader white background inside a dimmer with `.ui.dimmer .ui.loader` rule.
So Loader ends up having white color on white background.

### Version
semantic-ui-react 1.2.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-nzwzh?file=/index.js

**Comment by brianespinosa** [comment]
Hi @nidu 

The loader is not visible because it is being rendered on a white background. The CSS from the parent repository does not allow the use of the `.inverted` class in this case. However, looking at the code examples, if we use the Loader with a Dimmer, the Loader will be visible as you expect:

```
<Dimmer active>
  <Loader />
</Dimmer>
```

If you do not like the color of the dimmer and would prefer white, you can use the `inverted` prop on the dimmer:

```
<Dimmer active inverted>
  <Loader />
</Dimmer>
```

**Comment by nidu** [comment]
Thanks @brianespinosa! This works pretty good though modal rounded corners are a bit distorted.

I just thought that Loader can be used without the Dimmer to localize "blocked" area.
