### ISSUE TITLE
How to create expandable area under a Table Row?

### ISSUE THREAD

**Issue by mrwappa** [Semantic-Org/Semantic-UI-React#4091]
Asked this question on StackOverflow but got no answer, so I'm posting it here as well.
I'm trying to create Table Rows in a Table that can expand by clicking on them (individually).

For example, if I would click on the specified area in the picture below, a Segment/Container (some sort of area) would drop down with content inside.

[![enter image description here][1]][1]

I've tried a solution that is mentioned [in this thread][2], but the underlying problem is that every element under a Table Row/Cell is subject to the rules and boundaries of the Table HeaderCell. So if I for example try to create a Table Row with a Segment under it, the result will look like this:

[![enter image description here][3]][3]

As you can see the Segment is inside the new Row but is limited to the size of the HeaderCell.

When doing this I also get this error:

    validateDOMNesting(...): <div> cannot appear as a child of <tr>.
        in div (created by Segment)

It seems that Segment under Table Row is therefore a prohibited element structure.

Any idea on how the element structure should look to create some kind of area under a Table Row?

  [1]: https://i.stack.imgur.com/J8h3J.png
  [2]: https://stackoverflow.com/questions/53240115/semantic-ui-react-map-accordion-in-every-table-row
  [3]: https://i.stack.imgur.com/rjej1.png

**Comment by brianespinosa** [comment]
@mrwappa I answered your question on Stack Overflow. Pretty sure that should get you there. Thanks for asking there first.

Here's a link to the original question in case anyone lands here instead of the original question: https://stackoverflow.com/questions/64336736/expandable-area-under-a-table-row-semantic-ui-react

Closing this issue so any other questions can happen on SO.
