### ISSUE TITLE
Ensure the official docs use the latest release and not some pre-relase version

### ISSUE THREAD

**Issue by hiredgunhouse** [Semantic-Org/Semantic-UI-React#4131]
Right now the latest relase on npm is using semantic-ui-css 2.4.1 while the official docs use version 2.4.2 (check the codesandbox.io samples) and the 2.4.2 has not been released.
I figured that out because 2.4.1 has a bug related to marking input field with "error" class. The style is not aplied because the specificity is the same as the general non-error case definition and it is defined later in the stylesheet.
Can you either release 2.4.2 or make sure the official docs use the latest public release.

**Comment by layershifter** [comment]
@hiredgunhouse publishing for 2.4.1 on some packages indeed failed, however `semantic-ui@2.4.2` is published on NPM and contains important fixes:

![image](https://user-images.githubusercontent.com/14183168/104458725-031e8600-55ac-11eb-9f36-af0033b97ca5.png)

The issue was released in the main repo: https://github.com/Semantic-Org/Semantic-UI/issues/6646. I also quote my reply from #3345.

> To clarify the issue:
> 
> * this bug was fixed in Semantic UI 2.4.1, [Semantic-Org/Semantic-UI@36d5857](https://github.com/Semantic-Org/Semantic-UI/commit/36d5857eaba7e6a51ca522521f8505f5c343405c)
> * `semantic-ui-css@2.4.2` and `semantic-ui-less@2.4.2` aren't published to NPM, [Semantic-Org/Semantic-UI#6646](https://github.com/Semantic-Org/Semantic-UI/issues/6646)
> * `semantic-ui@2.4.1` and `semantic-ui-css@2.4.1` has wrong prebuilt CSS and it points to [2.4.0](https://cdn.jsdelivr.net/npm/semantic-ui-css@2.4.1/semantic.min.css) which contains this bug 😭
> 
> I made a PR (#3367) that will fix this issue for our doc site. For users: please ensure that you're really using SUI 2.4.2.
