### ISSUE TITLE
Dropdown will break with too long text

### ISSUE THREAD

**Issue by liquidz** [Semantic-Org/Semantic-UI-React#4132]
### Steps

![2020-12-21 11 03 48 react semantic-ui com d767d4a8a609](https://user-images.githubusercontent.com/6941/102732016-d1cfe300-437c-11eb-92aa-d84562357fd2.png)

* Access to https://react.semantic-ui.com/modules/dropdown/#types-selection
* Update one of `text` in `friendOptions` to too long text

### Expected Result

* Displayed within a frame

### Actual Result

* Displayed outside the frame

### Version
2.0.1

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-815xq?file=/index.js

**Comment by brianespinosa** [comment]
@liquidz this repository does not contain any of the CSS that controls these styles. You could open an issue for this in the Semantic UI parent project.

This should only happen with long, unbroken string of text like this with no spaces.  My guess is that is probably outside of the use case for the dropdown Select. That being said, if you WANTED the unbroken line to break, you could add some CSS to force the line to wrap at the edge of the parent container. I am pretty sure this is not going to look good though. You may want to consider instead having an overfllow-hidden style, possibly with an ellipsis. These are just guesses because I do not know what content you are trying to display in your Select components this way. My guess is that you are displaying a long URL.

Since these styles are not contained in Semantic UI React itself, I am going to go ahead and close this issue.
