### ISSUE TITLE
Set disabled attribute for `Tab` item

### ISSUE THREAD

**Issue by corocoto** [Semantic-Org/Semantic-UI-React#4151]
Can I set `disabled` attribute for one of [`Tab`](https://react.semantic-ui.com/modules/tab/#types-basic) items?

**Comment by brianespinosa** [comment]
@corocoto Instead of passing a string for `menuItem` pass an object with the props you would like to set on the item. This is our shorthand API in SUIR. Pretty much any prop that accepts a string which also renders another component can also accept an object which can be used to set the props for that component instead of passing a string itself. 

```
menuItem: {
  content: 'Tab Label',
  disabled: true
}
```

**Comment by corocoto** [comment]
@brianespinosa, thanks a lot!
