### ISSUE TITLE
Fixed position elements positioned incorrectly when child of a modal

### ISSUE THREAD

**Issue by christrain91** [Semantic-Org/Semantic-UI-React#4180]
### Steps
Add an element with `position: fixed` as a child of a modal 

### Expected Result
The element should be positioned relative to the browser viewport

### Actual Result
The element is positioned relative to the modal

### Version
2.0.3

### Testcase
https://codesandbox.io/s/unruffled-fermat-65wb8

**Comment by brianespinosa** [comment]
Hi @christrain91 

This would not be possible because the parent styles for the Modal itself will always contain the `position: fixed` element. The only way to achieve this would be to break your element out of the Modal parent markup by rendering it in another Portal.

I updated your Codesandbox with an example of how this might look. https://codesandbox.io/s/modal-portal-qjpus
