### ISSUE TITLE
Modal border radius

### ISSUE THREAD

**Issue by dionkas** [Semantic-Org/Semantic-UI-React#4182]
Hey!

How can I change the border radius of the Modal? Without using any css important rules. 

Can someone post an example?

Thanks

**Comment by rbasto1** [comment]
No sure this is the preferred way, but this is how I've been overriding css attributes when using Semantic UI, without using !important: I use the Inspector to check what are the combination of classes being applied to the component, and that the browser is using to compute the relevant attribute.
Using as example your issue with the border radius, if you inspect the modal you will see that its border radiuses are set by these rules: `.ui.modal>:first-child:not(.icon)` and `.ui.modal>:last-child`. Let's say I don't want it round at all, here is what I would do:

```
/* jsx */
<Modal className="square-corners">
```
```
/* css */
.square-corners.ui.modal>:first-child:not(.icon) {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.square-corners.ui.modal>:last-child {
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
```

Since this is a more specific rule than what Semantic UI specifies, the browser will use it (for the specified attributes) instead.
For more information: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2

**Comment by dionkas** [comment]
Thank you very much for your thorough reply and the link provided!

I can now go ahead and start removing !important from my codebase.
