### ISSUE TITLE
Popup does not open in fullscreen mode

### ISSUE THREAD

**Issue by tkwant** [Semantic-Org/Semantic-UI-React#4191]
### Steps
I am using react-full-screen and there I have a Popup component. The Popout does not open in fullscreen mode. 

### Expected Result
Popup gets opened in fullscreen mode. 

### Actual Result
Popup does not open in fullscreen mode. 

### Version
2.0.3

### Testcase
Here is the test code:

```
import 'semantic-ui-css/semantic.min.css'
import {  Menu, Popup } from 'semantic-ui-react'

import { FullScreen, useFullScreenHandle } from "react-full-screen";
import { useState } from 'react';
export default function App() {
  const handle = useFullScreenHandle();
  const [isFilterOpen, setIsFilterOpen] = useState(false)
  const onFullscreenToggle = () => {
    if(handle.active){
      handle.exit()
    }else{
      handle.enter();
    }
  };

  return (
    <div className="App">
      <FullScreen handle={handle}>
        <button onClick={onFullscreenToggle}>Toggle Fullscreen</button>
        <Menu>
        <Popup
                    trigger={
                        <Menu.Item
                            active={isFilterOpen}
                            onClick={() => { setIsFilterOpen(!isFilterOpen) }}
                        >
                          Popup
                        </Menu.Item>
                    }
                    content={
                        <div>My content</div>}
                    position={"right center"}
                    // pinned
                    on="click"
                />
        </Menu>
      </FullScreen>
    </div>
  );
}


```

**Comment by layershifter** [comment]
I created a Codesandbox with a repro: https://codesandbox.io/s/semantic-ui-example-forked-pkets?file=/example.js
It's a valid bug, thx for reporting 👍

**Comment by layershifter** [comment]
@tkwant it's not an issue with `Popup`, it's a problem with `react-full-screen` and how it calls `.requestFullscreen()`, https://github.com/snakesilk/react-fullscreen/blob/273a73bf55166adafb444a9309b9469c8b5bb8da/src/index.tsx#L41. As it calls it on an element (not on `document.documentElement`, for example) in full screen view you will see only inner DOM of `FullScreen` component. In the same, `Popup` renders element on `document.body`, that's why it's invisible.

To workaround the problem, you can use `mountNode` prop, I prepared an example:
https://codesandbox.io/s/semantic-ui-example-forked-fmzzm?file=/example.js

---

The same issue in MUI, https://github.com/mui-org/material-ui/issues/15618.
