### ISSUE TITLE
Why is Jquery listed as dependency ? 

### ISSUE THREAD

**Issue by sandeep-kr-kgp** [Semantic-Org/Semantic-UI-React#4213]
The first thing on the website says that it's jquery free, yet it's there in the dependency list. Why ?

**Comment by brianespinosa** [comment]
@sandeep-kr-kgp these are the dependencies in the [package.json](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/package.json) file. There is no jquery.

```
"dependencies": { 
   "@babel/runtime": "^7.10.5", 
   "@fluentui/react-component-event-listener": "~0.51.6",
    "@fluentui/react-component-ref": "~0.51.6",
    "@popperjs/core": "^2.6.0",
    "@semantic-ui-react/event-stack": "^3.1.2",
    "clsx": "^1.1.1",
    "keyboard-key": "^1.1.0",
    "lodash": "^4.17.19",
    "lodash-es": "^4.17.15",
    "prop-types": "^15.7.2",
    "react-is": "^16.8.6 || ^17.0.0",
    "react-popper": "^2.2.4",
    "shallowequal": "^1.1.0" 
 },
```

**Comment by oguera** [comment]
I know that this is an old issue but i was wondering about the same. jQuery get's downloaded because of the css part of semantic ui:
```
yarn why v1.22.11
[1/4] 🤔  Why do we have the module "jquery"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "jquery@3.6.0"
info Reasons this module exists
   - "semantic-ui-css" depends on it
   - Hoisted from "semantic-ui-css#jquery"
info Disk size without dependencies: "1.71MB"
info Disk size with unique dependencies: "1.71MB"
info Disk size with transitive dependencies: "1.71MB"
info Number of shared dependencies: 0
✨  Done in 1.14s.
```

So even though jQuery ends up in the node_modules folder it's not used and therefore should not end up in the final build.

Hope that help everyone who might come across this in the future.

**Comment by brianespinosa** [comment]
@oguera the css is also not part of this repository.

**Comment by oguera** [comment]
While this is technically correct the "getting started" [instructions on the homepage](https://react.semantic-ui.com/usage) states that one should install `yarn add semantic-ui-react semantic-ui-css` - even though it's not declared in the package.json it appears to be a peer dependency.

**Comment by layershifter** [comment]
@oguera even if it's installed by `semantic-ui-css` package it will not be present in the bundle as only CSS is required. This repository does not use jQuery.

**Comment by oguera** [comment]
This is exactly what i was trying to say with my comment

>So even though jQuery ends up in the node_modules folder **it's not used** and therefore should **not end up in the final build**.

Maybe there is a slight misunderstanding here. I didn't want to point out that this repo actually uses jQuery i just wanted to provide a clarifying comment for others that might wonder why jQuery ends up in their node_modules folder (because of the `semantic-ui-css` package) and that it doesn't end up in their final build. :+1:
