### ISSUE TITLE
Recommended upgrade path from 0.x app?

### ISSUE THREAD

**Issue by dstpierre** [Semantic-Org/Semantic-UI-React#4216]
Hey,

What would you recommend as upgrade path from a 0.68 project.

Going to 2 or it would be better upgrading to 1 than 2.

Is it at all possible you think, or it's not very recommended?

Any pointers would be highly appreciated,
Thanks

**Comment by layershifter** [comment]
Hey @dstpierre.

To be clear, v1 was released more as a milestone release and does not have any breaking changes (v2 has them and has the guide). The problem is that every minor release from 0.68.0 till 0.88.2 has breaking changes (it's least 20 breaking changes 💥).

If you have time, I suggest to jump to v2 directly via the migration guide and check release notes for previous releases as there were a lot of fixes 🙄
