### ISSUE TITLE
Add 'color' prop for Radio toggle

### ISSUE THREAD

**Issue by zeddrix** [Semantic-Org/Semantic-UI-React#4223]
## Feature Request
Please add a way to style the Radio toggle type component 

### Problem description
There is no way to change the color of the Radio toggle like that of the other components like the Button.

### Proposed solution
Please add a prop called 'color' like that of the Button's so that we can customize the color. But about that, is there a way that you could make this 'color' prop accept different color values like HEX, RGB, etc.? So that we may pass in different colors that we like. I'd also like to have this because I would like to let my users change the color theme of my website, including the Radio toggle's color.

**Comment by brianespinosa** [comment]
Hi @zeddrix 

This React package is just the React bindings that output correct markup and class lists for the associated CSS styles that you would compile from Semantic UI. There are no styles contained in this repository.

In Semantic UI, the way you would change the toggle background color is by using their build tools and templating to output your own CSS. Those tools are beyond the scope of the React project. If you did not want to use those build tools, you could still use the default styles and then add your own CSS files to increase specificity and override the defaults, or you could inline your CSS onto the components themselves, provided the styles are attached to non-pseudo elements. I point out the pseudo element limitation in React because the Checkbox toggle makes use of `:before` and `:after`. In this case, inlining styles would not be possible and you would need to write actual CSS (or SCSS, less, etc). Or use any CSS in JS solution that is capable of applying more specific style rules than the default SUI classes.

Something like this: 
```
// In your JSX
<Checkbox 
  className='customBackground' 
  toggle 
/>

// In your CSS... as SCSS for brevity
.customBackground {
  &.ui.toggle.checkbox input:checked~.box:before, 
  &.ui.toggle.checkbox input:checked~label:before {
    background-color: rgba(200,10,50,.5);
  }
}
```
