### ISSUE TITLE
Wrong background color of a "basic" button in a group consisting of basic buttons

### ISSUE THREAD

**Issue by meglio** [Semantic-Org/Semantic-UI-React#4224]
## Bug Report

Create a button group of `basic` buttons. Make the last button have an icon. The icon will be rendered with a wrong background color:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/282177/125057125-0f614700-e0e8-11eb-9a16-7f06005155d4.png">

### Version

```
{
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^2.0.3",
}
```

**Comment by brianespinosa** [comment]
@meglio please use the bug reporting form and include a codepen/sandbox showing the code used to render these components. We include that to make it as easy as possible to show an example of what you are experiencing. Without it we can only guess how you are using the components. I am happy to take a look at this with you as soon as there is code to evaluate.

Closing but will reopen with a codepen example.

**Comment by meglio** [comment]
Dear team, I do understand this requirement, but it still is somewhat unreasonable to ask for additional effort while I already put an effort into reporting it instead of just ignoring it; -- which will save time for your QA people, I guess. I suggest it's your turn now to "pay back" by investing your effort into investigating a little bit more instead of just closing the issue.

**Comment by ivangomes** [comment]
@meglio edit your bug report adding a codepen example with your code. Please pay attention to the previous answer:

@brianespinosa said: 
"I am happy to take a look at this with you as soon as there is code to evaluate." 
"Closing but will reopen with a codepen example."

**Comment by meglio** [comment]
Why are not the exact reproduction steps enough?

**Comment by meglio** [comment]
Will this work?

https://codesandbox.io/embed/semantic-ui-react-forked-wpsm4?fontsize=14&hidenavigation=1&theme=dark&view=editor

**Comment by ivangomes** [comment]
@meglio  Yes!

https://codesandbox.io/s/semantic-ui-react-forked-wpsm4?from-embed

**Comment by ivangomes** [comment]
@meglio  check this: 
A button can use an icon as a label.
 <Button icon labelPosition='right'>
 <Button icon labelPosition='left'>
if you remove labelPosition the label Ibackground) will be removed. Unfortunately this is not a bug.

I usually use a menu compact like this:


`<Menu compact>
        <Menu.Item
          name='gamepad'
          active={activeItem === 'gamepad'}
          onClick={this.handleItemClick}
        >
          <Icon name='gamepad' />
          Games
        </Menu.Item>

        <Menu.Item
          name='video camera'
          active={activeItem === 'video camera'}
          onClick={this.handleItemClick}
        >
          <Icon name='video camera' />
          Channels
        </Menu.Item>

        <Menu.Item
          name='video play'
          active={activeItem === 'video play'}
          onClick={this.handleItemClick}
        >
          <Icon name='video play' />
          Videos
        </Menu.Item>
      </Menu>`

**Comment by meglio** [comment]
> if you remove labelPosition the label Ibackground) will be removed. Unfortunately this is not a bug.

How do I "align" the label then?

Also, the workaround is not delivering the same result, so it's not complete. Check the screenshot below that demonstrates how there is no more enough space around the icon:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/282177/125487381-75548a49-bac5-4a6a-b969-c0a645bf1dd6.png">

**Comment by ivangomes** [comment]
Try this:

https://codesandbox.io/s/08hut?module=/example.js&file=/example.js

Change your menu from:
   '< Menu icon=labeled >'
To: 
' < Menu compact >'

:)

**Comment by meglio** [comment]
It's not a menu. It's a button.

**Comment by meglio** [comment]
So... is there a workaround that actually works?

**Comment by brianespinosa** [comment]
> Why are not the exact reproduction steps enough?

@meglio the reason is that these were actually not exact reproduction steps. There is no way to tell if you used the shorthand API, the subcomponent API, if you have put some other code in your implementation that is causing a side effect. It is not uncommon to discover that putting a working code example together in isolation actually surfaces that things are working correctly and there is something else causing an issue in the ecosystem your code lives.

> it still is somewhat unreasonable to ask for additional effort

Understand that there was no way to tell how you had implemented your code so the only way anyone could have even helped you was just guessing. We did as much as possible to make it easy to get us all of the information needed and it was not provided. People want to help, but we need to know precisely what we are dealing with in order to do so.

Remember, this is open source work. 

I am going to dig into what your codepen is showing now.

**Comment by brianespinosa** [comment]
@ivangomes thanks for jumping in to try to help out here. Just a heads up, in your example, the button still has the `icon` prop on it. That adds a class name that removes horizontal padding on SUI icons, which is why there is no margin between the icon and the button text. Removing the prop will give the expected display.

https://codesandbox.io/s/basic-button-w-icon-wkwyp

```
<Button basic color="red">
    <Icon name="save" />
    Save
  </Button>
```

Closing again. No bug. This was a usage question for Stack Overflow.

**Comment by meglio** [comment]
> Removing the prop will give the expected display.

@brianespinosa , but that's how the documentation goes! Check this screenshot:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/282177/125885589-910444c9-0b1d-411b-b659-fdec82ee6603.png">


More to that, you not only removed `icon`, but also `labelPosition="left"`. Now, how do I align the icon to the right?

<img width="501" alt="image" src="https://user-images.githubusercontent.com/282177/125885509-959aeea2-d738-4110-8632-b1539fbf30c5.png">

P.S. Guys it is not encouraging to keep elaborating if you keep closing the issue without trying to understand what is being reported exactly. Please stop this behaviour.

**Comment by ivangomes** [comment]
![Screen Shot 2021-07-16 at 8 59 49 AM](https://user-images.githubusercontent.com/6374624/125951732-426195ff-9822-478e-8f44-43f56a26ca38.jpg)

**Comment by brianespinosa** [comment]
@meglio do you want a Labeled Button or do you want a button with an icon inside of it? They are two different things. You are looking at a labeled button. The labeled button explicitly has a slightly different background color for the icon. It is intentional, and it was what you were initially expecting. I see in your screenshot you are also trying to use Button.Group. Do you want the icon to be a separate button? If not, then you do not want to use Button.Group.

> Guys it is not encouraging to keep elaborating if you keep closing the issue without trying to understand what is being reported exactly. Please stop this behaviour.

Looking at your first screenshot, and the entire discussion until the comment telling us to stop closing tickets, you never mention you want the icon on the right. You were shown a solution to the exact thing you were asking for.

We use these tickets for reporting of bugs. If you need support using SUIR and getting your layout to look the way you want, it is going to be better to use StackOverflow with the correct tags. More people will see your questions and be able to answer you.

**Comment by meglio** [comment]
> I see in your screenshot you are also trying to use Button.Group. Do you want the icon to be a separate button? If not, then you do not want to use Button.Group.

My bug report is for the `<Button.Group>` because it is the case when I caught that bug. I do have a few buttons next to each other, hence using the group.

Back to my original question:

![image](https://user-images.githubusercontent.com/282177/126033444-c7fb3bd6-d135-43bc-b905-022fca101192.png)

So, you are saying that the grey background is what I should expect and there is no a clear way to let the icon have the same background as the button via API?

**Comment by brianespinosa** [comment]
If you are using the labeled button inside a button group, yes. That is 100% expected. If you want to not have the icon be in a separate label container then you should just define it as a child of the button itself and it will not have the different background color that all label elements will have, regardless of if the label contains an icon or text. The label is explicitly a separate element that is getting prepended or appended to the button or input.

**Comment by meglio** [comment]
@brianespinosa , what's the logic behind this expectation? If all my buttons are white, why would an icon have a grey background? What's the idea. And, more importantly, why can't I change it?

> If you are using the labeled button inside a button group, yes

**Comment by brianespinosa** [comment]
@meglio none of the styles for Semantic UI React are in this repository. This repository is _only_ the React bindings for the class names and functionality in Semantic UI. You are asking a design question why Jack Lukic made a style choice.

If there is something you do not like about those styles, Semantic UI has an extensive theme and style building system for you to change those values yourself and generate your own CSS. It is not part of this project, but you can definitely [generate your own CSS using the tooling in Semantic UI](https://github.com/Semantic-Org/Semantic-UI) and use it with Semantic UI React components.
