### ISSUE TITLE
Using an Icon in a Header ignores Icon size prop

### ISSUE THREAD

**Issue by adamvanaken** [Semantic-Org/Semantic-UI-React#4296]
### Steps
Using an `Icon` in a `Header` ignores the `Icon` size prop. 

I understand that I could easily override the styling, but I don't want to potentially break or miss out on future styling updates by doing so.

### Expected Result
I would expect to be able to size Icons inside Headers.

### Actual Result
The `.ui.header>.icon` style overrides the font-size that, as an example, the `i.small.icon` style sets.

### Version
2.0.4

### Testcase
https://codesandbox.io/s/semantic-ui-react-forked-38ue7

![image](https://user-images.githubusercontent.com/5086278/136974298-06141a11-478c-4739-93bb-195848944fa7.png)

**Comment by brianespinosa** [comment]
Hi @adamvanaken 

We can see from your example that the class names are being added as expected, as you can tell that those classes are being attached and then overridden by more specific class styles of the header. We do not have any of the CSS in this repository. I would recommend creating an issue in the parent SUI repository where our class names come from. I do not know if that was an intentional design decision, or if it was a miss.

**Comment by adamvanaken** [comment]
@brianespinosa fair enough; created an issue in the CSS repo: https://github.com/Semantic-Org/Semantic-UI-CSS/issues/73
