### ISSUE TITLE
Docs: Comparison width error

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#433]
On FHD screen I'm getting following:

![image](https://cloud.githubusercontent.com/assets/14183168/17939325/c68ec376-6a32-11e6-8fe8-7c4db83722e0.png)

Classes looks correctly:

![image](https://cloud.githubusercontent.com/assets/14183168/17939733/9cddc854-6a34-11e6-912a-cf9f4c52a661.png)

But width taken another:

![image](https://cloud.githubusercontent.com/assets/14183168/17939338/dc0bf82c-6a32-11e6-871a-bd76de589873.png)

Looks like issue with SUI or I am missing something :thought_balloon:

**Comment by levithomason** [comment]
Vertical dividers are broken due to a CSS spec change.  SUI core has opened issues with the w3c and Chrome:  https://github.com/Semantic-Org/Semantic-UI/issues/4342

Though, this might be as easy as adding `largeScreen='2'` to the column with the divider in it:

**Introduction.js**

``` diff
const Comparison = ({ jsx, html }) => (
  <Segment className='code-example'>
    <Grid columns='equal' centered textAlign='left'>
      <Grid.Column mobile='16' tablet='16' computer='8' largeScreen='7'>
        <Label size='tiny' attached='top left'>JSX</Label>
        <Highlight className='language-xml'>
          {jsx}
        </Highlight>
      </Grid.Column>
-      <Grid.Column only='large screen' textAlign='center'>
+      <Grid.Column only='large screen' largeScreen={2} textAlign='center'>
        <Divider vertical>
          <Icon name='right arrow circle' />
        </Divider>
      </Grid.Column>
      <Grid.Column mobile='16' tablet='16' computer='8' largeScreen='7'>
        <Label size='tiny' attached='top right'>Rendered HTML</Label>
        <Highlight className='language-html'>
          {html}
        </Highlight>
      </Grid.Column>
    </Grid>
  </Segment>
)
```

The other columns are set to `largeScreen='7'` so there should be 2 columns left over for the middle column.

**Comment by layershifter** [comment]
Seems, your was near, but not :crying_cat_face: 

![image](https://cloud.githubusercontent.com/assets/14183168/17940434/c9fb1d48-6a37-11e6-9b7a-df9326e5b564.png)

**Comment by levithomason** [comment]
I am a little confused on where you are seeing this issue.  Here is the current doc site in Chrome:

> http://technologyadvice.github.io/stardust/introduction

![doc site grid](http://g.recordit.co/jt1VI5ltdT.gif)

Also, the CSS you are comparing looks correct.  It should be `width: 50%` since that is the `eight wide computer` class:

![image](https://cloud.githubusercontent.com/assets/5067638/17943851/04459726-69f2-11e6-9e68-18ce7e70dcb1.png)

When I make the browser full width, I also see the `eight wide computer` width is overridden by the `seven wide large screen` width:

![image](https://cloud.githubusercontent.com/assets/5067638/17943911/49bbb72c-69f2-11e6-9fea-a768de8856a3.png)

Please confirm.

**Comment by layershifter** [comment]
Chrome 52, Windows 8, 1920x1080.

---

![image](https://cloud.githubusercontent.com/assets/14183168/17944182/50751126-6a47-11e6-8a73-839f04d11a6e.png)

Solution is:

``` diff
- <Grid.Column mobile='16' tablet='16' computer='8' largeScreen='7'>
+ <Grid.Column mobile='16' tablet='16' computer='8' largeScreen='7' widescreen='7'>
```

After it:

![image](https://cloud.githubusercontent.com/assets/14183168/17944274/b52f5b58-6a47-11e6-884d-286d5aeab56c.png)

**Comment by levithomason** [comment]
Ah!  Good call, `widescreen` is apparently the largest size which we were not accounting for.  I wish SUI Grids were mobile first, so the larger sizes were inherited from the next largest defined size.

Either way, would you like to open a PR?

**Comment by layershifter** [comment]
Made #438 :v:
