### ISSUE TITLE
Inline Styles

### ISSUE THREAD

**Issue by harmon25** [Semantic-Org/Semantic-UI-React#450]
Hi,
I am a big fan of semantic and react - am really digging this library.

Before this I was using material-ui quite a bit, and I  like their usage of [inline styles ](https://github.com/callemall/material-ui/blob/master/src/AppBar/AppBar.js#L19)\- which does a nice job encapsulating component logic with the styles. 

Their technique, through the use of a HOC also allows for themes, via component `context`

I thought I saw some discussion about this, but wondering if it might be worth for a future release to remove all Semantic-UI deps, and make this a completely standalone react component lib - without the need of any external css dependencies.

If it has been discussed and deemed not worth the effort/a bad idea feel free to ignore and close this.

**Comment by levithomason** [comment]
Hi there, it was actually one of our original motivations to make a CSS framework agnostic component library.  It is still something I'm interested in.  I've got 2 offline side projects that continue to investigate how this might be done.

We chose SUI CSS due to its amazing theming capabilities.  I believe SUI CSS offers the greatest support and flexibility for theming of any CSS framework there is.  The theming builds expose site variables, theme variables, and component variables in a way that allows you to control nearly every aspect of every component.  Here at TechnologyAdvice, we use multiple SUI themes with Stardust.

Currently, the best way to theme Stardust is via a precompiled SUI CSS theme.  See the theming docs for more on this, http://semantic-ui.com/usage/theming.html.  This of course gives you a precompiled theme which is the fastest possible rendering solution.  It also provides all the customization capabilities you may need.

We will continue to look at ways to allow theming from the component level.  Computing the entire style framework is not something we want to do on every render.  So, pre-calculating and caching styles as well as generating stylesheets is something we are looking at.  Essentially, this sounds like the ability to create a theme via definitions that have tighter cohesion with each component.

We'll continue to toy with component theming, but for now, this is at the very end of the priority chain in-house here at TechnologyAdvice.  A community effort would be very welcomed and supported however.

**Comment by harmon25** [comment]
Thanks for the response @levithomason !

I agree it should not be a priority - the customization options of SUI are pretty unreal, would be time consuming to move it all inline. 

I may try my hand at creating a HOC that encapsulates SUI themes that can be passed down to child components via context, similar to what [material-ui is doing](http://www.material-ui.com/#/customization/themes).

**Comment by levithomason** [comment]
Awesome, let me know if you get pretty far into this.  I may put some of my work up somewhere and we can toss ideas around.
