### ISSUE TITLE
Render empty label for Form Fields?

### ISSUE THREAD

**Issue by chuan137** [Semantic-Org/Semantic-UI-React#464]
I would propose to render a empty label when it is a empty string. A use case is as below,
an empty label will vertically align the following two fields side by side

```
<Form.Group>
<Form.Input label="Name" placeholder="First Name" />
<Form.Input label="" placeholder="Last Name" />
</Form.Group>
```

**Comment by levithomason** [comment]
This sounds sane to me, PR welcome.  Checkboxes also depend on an empty label.  Just include a comment in the code that notes why the empty element is being included.

**Comment by levithomason** [comment]
I was under the impression that SUI CSS required an empty label to align the fields, however, it appears that it just isn't supported markup.  An empty label does not align the fields:

![image](https://cloud.githubusercontent.com/assets/5067638/18258967/d2dc6f24-7393-11e6-88e9-36676caa7676.png)

It looks like there must be some content in the field label:

![image](https://cloud.githubusercontent.com/assets/5067638/18258973/e1565f60-7393-11e6-8305-f807a3973c3a.png)

I believe the proper way to do this is with the `inline` variation:

``` jsx
<Form.Group inline>
  <Form.Input label='Name' placeholder='First Name' />
  <Form.Input placeholder='Last Name' />
</Form.Group>
```

![image](https://cloud.githubusercontent.com/assets/5067638/18258991/15bfbbd4-7394-11e6-84c6-bcc700fd0d37.png)

Closing as the change required to align fields via an empty label needs to be opened with Semantic-UI since it requires a change of CSS.
