### ISSUE TITLE
Guideline for someone to just picking up the library/Support Roadmap

### ISSUE THREAD

**Issue by subodhpareek18** [Semantic-Org/Semantic-UI-React#546]
Hey @levithomason I'd been looking for a good semantic-ui and react integration for sometime now, glad that I came across stardust. I already use Semantic-UI in multiple projects and like it considerably and hence wanted to stick to it while making a react app. And since this library is going to be the official one I've decided to give it a shot, but before I do, have some questions.

1) What is the coverage % over semantic-ui components?
2) By when are you looking to port it over to semantic-org/semantic-ui-react?
3) When you do port it, what kind of breakages should we expect?
4) Any other important information someone just picking this library up for long-term should be aware of? 

Have gone through your docs here https://technologyadvice.github.io/stardust so actually Ques 1) is not that important I guess. Ques 2) mostly in relation with Ques 3) is what I'm looking at, because I'd like to heavily rely on this library in production as I'm starting on a new long term project very very soon. And therefore was looking to get some critical information from you.

Cheers!

**Comment by levithomason** [comment]
1. https://github.com/TechnologyAdvice/stardust#support
2. Soon as the #269 list is done
3. Nothing will break when ported. It will just move from TechnologyAdvice/stardust to Semantic-Org/Semantic-UI-React.  GitHub magically handles all the redirects for existing links. The docs will live at `react.semantic-ui.com`.  Lastly, it will be published on NPM under `semantic-ui-react` instead of `stardust`.  Aside from these naming changes, the library will be the exact same library.
4. Per the README "Minor versions may introduce breaking changes until the v1.0 release. You should read the CHANGELOG and related issues/PRs to stay up to date."  We'll hit v1 when we get 100% supprt of all SUI components.  This will ensure the component APIs are vetted.  Until then, we may decide to change some component's props APIs, like the recent decision to rework the `labeled` Button API #510.  These changes are now down to a minimum as the majority of the refactors have been done and good patterns are in place.

As far as I am aware, this is the best SUI + React library there is.  We have the best docs, most tests, most active development, most community support, most stars, and most momentum of any other integration library there is.  If there were a better effort, I likely would have joined that one instead.  So, you can rest assured it's the best decision available.  Cheers!

**Comment by subodhpareek18** [comment]
Great! All the best with this library, hoping to use it and watch it mature!
