### ISSUE TITLE
feat(search): allow multiple search terms

### ISSUE THREAD

**Issue by khalidamin** [Semantic-Org/Semantic-UI-React#558]
It would be nice to have a 'multiple' property for Search component, to allow the user to enter multiple search phrases (just like the Dropdown component which allows the user to select multiple entries and 'taggifies' those entries).  I would be more than happy to contribute but I am too new to javascript development.

**Comment by levithomason** [comment]
Could you confirm my understanding here?  The Dropdown is used to select items from a list. It takes a `multiple` prop which allows the user to select multiple items from the list.  The Search component is used to find an item (likely from a remote API).

Are you proposing that the Search takes a `multiple` prop that allows:
1. Searching for a results that match any word in the query?  So that `good movie` would return results for `Good show` and `Top movie`.
1. Somehow selecting multiple Search results, like the Dropdown can select multiple items.

**Comment by khalidamin** [comment]
Sorry for being ambiguous in my last post. This is how my proposed feature should work:
- User types in something in the search box
- Search results appear as a list
- User selects a result from the list
- That selected result appears as a removable Label (like a tag), and the cursor moves to the right of that Label to allow the user to type next query
- User types next query, selects a result from the list and that result also becomes a removable Label, and cursor moves to right
  and so on.
- The user can click the remove button or backspace to remove a Label

Here is an [example ](http://www.domain.com.au/). We can search for Melbourne, then Sydney and so on. This allows the user to specify multiple search terms.

**Comment by jeffcarbs** [comment]
I think the `multiple` prop on `Dropdown` would work for you. The `Dropdown` supports the use-case of fetching remote data using the `onSearchQuery`  callback and `allowAdditions` supports adding new options on the fly. See it in action: http://technologyadvice.github.io/stardust/modules/dropdown#selection

In the link you provided, the `Dropdown` would be the main search box that allows selecting multiple "tags" and then when you click search you'd provide the `value` of the `Dropdown`, which would be array of those tags, to wherever else you want.

**Comment by khalidamin** [comment]
@jcarbo I think using the Dropdown instead of Search component will mean _sacrificing_ the nice features the Search component provides (such as custom rendering of results, and categories).

**Comment by levithomason** [comment]
The search does not select items, so we won't add labels into the input itself.  Also, if we did add this, it would have to be done in SUI core since there is no markup nor CSS to handle that.

If I'm hearing correctly, this issue may need to shift toward adding item renderers for the Dropdown.  I would second what @jcarbo has suggested for the Dropdown usage here as well.

**Comment by jeffcarbs** [comment]
While there's nothing analogous to category rendering in the `Dropdown`, we've since added the ability to customize the render of `DropdownItem`s and of the selected labels in the multi-select.

I think that's about as far as we'd go with this since that seems like it should solve the issues raised here and I don't think we want to push too far past SUI-core.

**Comment by svenkatesh-nyros** [comment]
Hi, I have a feature request in search component.
  
      handleSearchChange = (e, { value }) => {
	    this.setState({ isLoading: true, search_value: value })
		setTimeout(() => {
	           if (this.state.search_value.length < 1) return this.resetComponent()
		   const re = new RegExp(_.escapeRegExp(this.state.value), 'i')
	           **const isMatch = result => **re.test(result.name)** // Here I want to filter the resulst by result.name, result.email and other fields also**
		  this.setState({
	        isLoading: false,
	        search_results: _.filter(this.state.labors, isMatch),
	      })
	    }, 300)
	  }


in the above code
  isMatch is filtering the results by name only.How can i add other fields in the search results.
