### ISSUE TITLE
dropdown button produces unwanted highlighted border

### ISSUE THREAD

**Issue by mclarentgp** [Semantic-Org/Semantic-UI-React#573]
I have the following code setup.  That when i click on an item in the menu of the dropdown button or the button itself, the dropdown button is highlighted with a blue border that does not go away unless i click anywhere else on the browser.  

`const options = [
  { text: 'One', value: 1 },
  { text: 'Two', value: 2 },
]`
`const trigger = (
    <Icon name='user' />
)`
`<Dropdown button simple options={options}  trigger={trigger} />`
### Expected Behavior

click on dropdown button or item in dropdown button menu and no highlighted border around dropdown button
### Actual Behavior

click on dropdown button or item in dropdown button menu and a highlighted border appears and will not disappear until an area on the browser that is not the dropdown button is clicked.

Stardust: `0.48.3`
Browser: firefox and chrome
OS: windows 8

I noticed that if i remove the tabindex from the rendered html, that the dropdown button behaves as I would expect it to.  Is this correct that the rendered html has the tabindex on there for a dropdown button?

`<div class="ui button simple dropdown" tabindex="0"><i class="user icon"></i><i class="dropdown icon"></i><div class="menu transition"><div class="selected item" style="pointer-events: all;"><!-- react-text: 51 -->One<!-- /react-text --></div><div class="item" style="pointer-events: all;"><!-- react-text: 53 -->Two<!-- /react-text --></div></div></div>`

**Comment by levithomason** [comment]
The dropdown element retains focus when clicking on the menu since the menu is a child of the dropdown.  The focus style contains a CSS rule for the blue border.  This should be posted on [Semantic-UI](https://github.com/Semantic-Org/Semantic-UI) itself as it is a CSS issue.

Though, it is unlikely that SUI will change the focus style to not include the highlight.  This is essential when tabbing through components.  It is also a web precedent that elements become active (usually a colored border) when they are focused.

Regarding `tabIndex`, without this a `div` cannot obtain focus via the tab key.  It removes the blue border because you are then unable to focus the dropdown at all.  So, tabbing to the dropdown is not possible.

At any rate, here are some potential solutions if you are set on removing the border:
1. Add your own dropdown focus override CSS
2. Build a custom SUI theme that does not have the active style on focused dropdowns
3. Set `tabIndex='-1'` to prevent focus altogether.
