### ISSUE TITLE
Notifying of breaking changes in the changelog

### ISSUE THREAD

**Issue by jeffcarbs** [Semantic-Org/Semantic-UI-React#592]
In the readme it says:

> Hey, we're in development. Minor versions may introduce breaking changes until the v1.0 release. You should read the CHANGELOG and related issues/PRs to stay up to date.

I don't think it's reasonable to expect people to actually look at all the linked issues to figure out if something is going to break. Could we add a `Breaking Changes` sub-section to each version (only if applicable)?

In the most recent version (`0.52.0`), 2 breaking changes were introduced in `Dropdown` which I'd imagine is one of the most used components:

``` diff
-onChange(e, value)
+onChange(e, { name, value })

-onAddItem(value)
+onAddItem(e, { name, value })
```

**Comment by levithomason** [comment]
It's generated by a CLI, so we'd have to add a PR to [github-changelog-generator](https://github.com/skywinder/github-changelog-generator) (Ruby).

I think updating the README and changing our practice a bit is a good approach.  Currently, I release a minor for every breaking change and a patch for any backward compat change.  So it is like the numbers are shifted one slot.  However, I also release new components (major features) as a minor.  I should stop doing that and just say "minors are breaking, everything else is patch" in the README.

Also, we could adopt what [`semantic-release`](https://github.com/semantic-release/semantic-release) has done and use `BREAKING CHANGE: msg` for PRs that are breaking.  This way the change log is much more clear and the version numbers actually reliable.

**Comment by levithomason** [comment]
Also I should note, in general we'll be much more disciplined and calculated once we hit v1.  We'll include deprecation warnings instead of removing features.  The version after the deprecation warnings will remove the feature.  I also plan to keep rc branches and delegate issues / features to the appropriate version.

Currently, I want to avoid much of anything slowing us down.  Either way though, being disciplined about noting breaking changes and incrementing the minor/patch predictably is a no brainer.  So this is still well received.

**Comment by jeffcarbs** [comment]
👍 sounds good. Agree on not wanting to slow down before reaching v1 - we're getting close!

**Comment by levithomason** [comment]
Cool, thanks for closing.  I'll take care to be more disciplined on this from here forward.  Appreciate you raising this.
