### ISSUE TITLE
bug(Docs): 404 on old docs

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#635]
@levithomason seems we missed something on migration, on [old docs url](http://technologyadvice.github.io/stardust) - 404 :crying_cat_face:

**Comment by levithomason** [comment]
Yes, GitHub handles redirects for _almost_ everything.  Unfortunately, GitHub [does not support redirects for GitHub pages](https://help.github.com/articles/about-repository-transfers/#whats-transferred-with-a-repository) sites when transferring :(

> If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. _However, we don't redirect GitHub Pages associated with the repository._

The only way to get `technologyadvice.github.io/stardust` to redirect to the new docs is to create a TechnologyAdvice/stardust repo with gh-pages site and an index.html that redirects to the new gh-pages site.  The reason I do not want to do this, is that it will break the repo redirects since there will be an actual repo there.  That means everyone's forks, remotes, and GitHub links will be broken.

I've considered adding TechnologyAdvice/stardust with a README.md that points users here.  Then, also publish a gh-pages site with a redirect from the old docs to the new docs.  Again, this would break GitHub links (forks, remotes), but perhaps that is actually better if we then save doc site users?  Maybe people trying to use GitHub can find their way here easier than those trying to use the doc site.

/cc @jcarbo what do you think?

**Comment by levithomason** [comment]
OK, I went ahead with breaking developers workflow while preserving doc site users' workflow.  The old doc site URLs now redirect to the new doc site.

**Attention: @jcarbo @layershifter @Chris-R3 @dpkwhan @debrice @tomitrescak @Jlassos**

Odds are, you will have issues with your forks.  Please see the instructions on the old repo: https://github.com/TechnologyAdvice/stardust
