### ISSUE TITLE
Bug: Grid doesn't resize properly when window resizes

### ISSUE THREAD

**Issue by keeslinp** [Semantic-Org/Semantic-UI-React#639]
### Steps
1. Create a grid with a row and column floated right.
2. Resize the window horizontally
### Expected

When the window resizes the column floated to the right should stay in the window view.
### Result

The Right floated column gets cut off.

Here is what is looks like before the resize:

![screen shot 2016-10-06 at 11 57 09 am](https://cloud.githubusercontent.com/assets/3063404/19164476/5a3a4aa4-8bbd-11e6-8618-b68a39356310.png)

And here it is after the resize.

![screen shot 2016-10-06 at 11 57 22 am](https://cloud.githubusercontent.com/assets/3063404/19164474/53ca90b6-8bbd-11e6-9251-e10a1a8f6cb0.png)
### Testcase

http://codepen.io/anon/pen/LRQGpP?editors=0010
### More info

I was able to use largeScreen and Width to make things a little better but it wasn't smooth (column cut off until it reached smaller size then jumped back in).

**Comment by jeffcarbs** [comment]
Hey @keeslinp thanks for the report! This project only handles generating valid SUI markup and this sounds like an issue with the CSS - the container width is handled by CSS media queries from SUI core.

That being said, I looked at your test case and I think your issue is that the button has a certain width, and at some screen size the width of the button is bigger than the width of the column, so it extends outside it. I resized to just before the button gets cut off and you can see the button starting to break outside of the column padding: 
<img width="125" alt="screen shot 2016-10-06 at 2 24 22 pm" src="https://cloud.githubusercontent.com/assets/847027/19165138/ac2e9c76-8bd0-11e6-97b8-e343b2cbd49e.png">

Also, `floated='right'` floats the column, not the content. You can see when the column is wider than the button, the button is aligned left within the column:
<img width="156" alt="screen shot 2016-10-06 at 2 25 33 pm" src="https://cloud.githubusercontent.com/assets/847027/19165190/dd7f0f0e-8bd0-11e6-8a84-52e9b5d0b04f.png">

Hope this helps! Going to close this since it's not an issue with this project.

**Comment by levithomason** [comment]
You can also add `celled` to the `Grid` to see the column issue more clearly: http://codepen.io/levithomason/pen/ORQrQx

![image](https://cloud.githubusercontent.com/assets/5067638/19165287/0eb58c38-8bb8-11e6-8d56-e62b9e654a55.png)

**Comment by keeslinp** [comment]
Thanks guys. I appreciate your help :).

EDIT: adding a min-width to the column did the trick. Not sure if that's the proper way or not but it worked. Thanks again.
