### ISSUE TITLE
fix(Modal): close on escape not responding

### ISSUE THREAD

**Issue by L3V147H4N** [Semantic-Org/Semantic-UI-React#652]
**Steps to Reproduce**

``` JSX
<Modal
  open={this.state.open}
  basic size='small'>
  <Header icon='archive' content='Archive Old Messages' />
  <Modal.Content>
    <p>Your inbox is getting full, would you like us to enable automatic archiving of old messages?</p>
  </Modal.Content>
  <Modal.Actions>
    <Button basic color='red' inverted>
      <Icon name='remove' /> No
    </Button>
    <Button color='green' inverted>
      <Icon name='checkmark' /> Yes
    </Button>
  </Modal.Actions>
</Modal>
```

**Expected**
Modal closes on escape pressed

**Result**
Modal doesn't close

Maybe I'm missing something

I'm importing `import 'semantic-ui/dist/semantic.min.css';` in my entry file
and then

```
import {
  Modal
} from 'semantic-ui-react';
```

Everything else seems to work fine

**Comment by levithomason** [comment]
Please note a code snippet is not a sufficient substitute for steps to reproduce a bug.  All of the Modal doc examples are functioning correct regarding close on escape:

http://react.semantic-ui.com/modules/modal

Feel free to provide reproducible step by step instructions on how to create this bug and we can investigate.

**Comment by dantedubonc** [comment]
I have the exact same problem described above. If I have this code, the modal never close on escape: 

```
  <Modal open>
    <Modal.Header>Select a Photo</Modal.Header>
    <Modal.Content image>
      <Image wrapped size='medium' src='http://semantic-ui.com/images/avatar2/large/rachel.png' />
      <Modal.Description>
        <Header>Default Profile Image</Header>
        <p>We've found the following gravatar image associated with your e-mail address.</p>
        <p>Is it okay to use this photo?</p>
      </Modal.Description>
    </Modal.Content>
  </Modal>
```

Here is my webpackbin: http://www.webpackbin.com/Ekiwi2_1M

**Comment by levithomason** [comment]
You have `<Modal open={true} />` which is a permanently open Modal.  It will never close because it is a "controlled" component.  It is called controlled because you are passing a value to the `open` prop.  That means you'll need to handle the key event yourself and update the `open` prop to `false` to close it.

If you'd like to modal to be "uncontrolled" and manage it's own `open` state, remove the `open` prop.

@L3V147H4N this is likely your issue as well.  I'm betting your `this.state.open` is true and never toggled to false.  You'd need to add an `onClose` event handler and toggle the `open` state when the user tries to close the Modal.

Here's a working example: http://react.semantic-ui.com/modules/modal#multiple-modals
Here's the React docs controlled/uncontrolled:  https://facebook.github.io/react/docs/forms.html
