### ISSUE TITLE
Support for custom Anchor elements - React Router

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#669]
Hi, how can I change the default anchor element in links to be a custom "Link" element of React Router? Thanks!

**Comment by levithomason** [comment]
If you'd like to update your PR https://github.com/Semantic-Org/Semantic-UI-React/pull/544 per the comments, we can merge that.  I notice it included config for this.

Otherwise, you can use the `as` prop.  `<Segment as='a' />` for example.  The inferred link element is only chosen if you do not define an `as` prop _and_ you provided an `href` prop.

**Comment by tomitrescak** [comment]
I just did ;)
