### ISSUE TITLE
Dropdown "text" in callback

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-React#754]
Hi, currently the "text" value in the dropdown callback is always null. It takes the prop name from the dropdown, not from the selected item for some reason. Is this a feature? Is it possible to also include "text" value in the onchange callback? Thanks

PS: I promise I searched your issues if this has been reported.

**Comment by levithomason** [comment]
>PS: I promise I searched your issues if this has been reported.

😍

I just went to update this, however, I'm not sure it is as simple as I thought.  The `value` there can either be a single value or an array of values (when `multiple`).  It is also synonymous with the `<Dropdown value={...} />` so it can be captured `onChange`, updated, and passed back to the Dropdown.

Lastly, it is also used as the `value` of the hidden `select` element for form submissions.  React wants arrays of values for multiple selects and strings for single selects.

In conclusion, we _could_ technically update all these areas to resolve the full props of the item that was passed in, however, I'm thinking it is best to keep the `value` as the Dropdown value.

Since you have all the items, and the value, can you look up the text yourself like so?:

```js
const options = [{ text: 'One', value: 1 }, { text: 'Two', value: 2 }]

const handleChange = (e, { value }) => {
  const option = _.find(options, { value })
  console.log(`Changed to text: ${option.text}`)
}

<Dropdown selection onChange={handleChange} options={options} />
```

**Comment by tomitrescak** [comment]
If it's too complex, then your solutions is ok. It is exactly as I had it solved now ;) Thanks.

**Comment by tomitrescak** [comment]
One question though, what does that `name` actually represents?

**Comment by levithomason** [comment]
The name of the hidden input. All prop names, types, and descriptions are documented:

http://react.semantic-ui.com/modules/dropdown

Glad it's working. Thanks for closing!
