### ISSUE TITLE
modal keeps opening recursively

### ISSUE THREAD

**Issue by packetstracer** [Semantic-Org/Semantic-UI-React#794]
Using modal, if bootstrap.css file is imported, the animation of the modal opening never stops. The Modal methods setPosition() and render() keeps executing over and over again. 

Why am I using both? I need bootstrap for React Bootstrap Table and thus need bootstrap.

Anyone having this issue or knowing how to solve it? 

Thanks.

**Comment by levithomason** [comment]
I would highly recommend not using both Semantic-UI and Bootstrap.  There are bound to be several conflicting issues.  Aside from this, your package will be severely bloated as you're including two very large CSS frameworks and two React component libraries.

That said, I can't think of a reason that the Semantic-UI-React Modal's internal methods would be called recursively like this.  This might be a bug and unrelated to CSS.

Could you create a repro on Codepen (fork codepen.io/levithomason/pen/ZpBaJX), or a minimal repo for investigation?

**Comment by levithomason** [comment]
@packetstracer any update here?

**Comment by levithomason** [comment]
Closing this issue for good housekeeping. We have no plans to support loading other CSS frameworks on top of Semantic UI components since there are a potentially infinite number of conflicts.

**Comment by sag1v** [comment]
@levithomason 
I know this issue is closed and i can understand the decision of not supporting 2 overlapping UI frameworks. 
However,  there are some use cases where one would need (or want) to use more than one framework.  
For example, building a widget based on SUI, that will "live" inside a website that uses bootstrap or any other conflicted UI framework.
Or migrating a website from one UI framework to another in small phases where you can't do all the changes in one go.
I'm sure there are more valid use cases.

Is there a way to prefix or suffix the generated `CSS` class names that `semantic-ui-react` produces?  
Some of the challenges here are:

1. To sync it with the `semantic-ui` CSS lib, this will require from the user to do the same changes to the class names inside the css lib as well.

2. To keep the new build of `semantic-ui-react` in sync with all the bug fixes and updates from the base repo.

If we could let the users isolate the framework we will give SUI the power and flexibility to co-exist with any other framework. 

As far as i know, the maintainers of `semantic-ui-react` works closely with the maintainers of `semantic-ui`. So maybe it is possible to do this change in a next major version? As i mentioned, isolation of this kind will let SUI get more powerful and flexible  than any other UI framework out there.  
In our world the word `component` is a key word, i see no reason to avoid this approach with styling and frameworks.
Thanks for reading 😄
