### ISSUE TITLE
Search Results Not Visible With Default Example

### ISSUE THREAD

**Issue by dcurletti** [Semantic-Org/Semantic-UI-React#803]
### Steps
1. Added the example Search component to a project
2. Ensured that it was receiving the correct result props.

### Expected Result
A visible list of result components

### Actual Result
The list of results is not visible.  I see that the results are in the DOM, but when the class node `<div class="results transition">` get the `visible` class, it doesn't inherit any new CSS properties.  I'm assuming this is a CSS error?  I have both the Semantic Search and States modules, so I'm not sure why. 

I checked this against the native JS semantic site, and their example gets an inline property applied: `<div class="results transition visible" style="display: block !important;">`.  They too apply a `visible`, but it doesn't come with any CSS properties.

EDIT: 
I see that their `.visible.transition` class does add the `display: block` property as a backup.  Seems like I need the transition CSS module.

### **SOLUTION**
This component needs the `transition` and `search` css modules.

**Comment by levithomason** [comment]
To clarify for others as well, you must include Semantic-UI CSS in order to use Semantic-UI-React.  Use one of the options noted in http://react.semantic-ui.com/usage#css.

Example, if you can include `semantic.css` from any of the methods noted in the docs above.  This would provide the styling for _all_ components.

Semantic UI also ships a CSS file for every individual component. If you do want to include the entire Semantic-UI CSS framework, then you can opt to include the CSS file for every component that you are using.  You can use any of the CSS delivery methods detailed in the docs link above.  If you're using `link` tags in your HTML `head`, for example:

``` html
<link href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/components/search.css" rel="stylesheet" />
```

This would only provide styling for the `<Search />`, you then need to include the stylesheet for _every_ other component you are using as well.
