### ISSUE TITLE
bug(customPropTypes): demand validation is broken with defaultProps

### ISSUE THREAD

**Issue by layershifter** [Semantic-Org/Semantic-UI-React#827]
Thanks to @meze for report in #809.

----

#809 introduced new propType validation for `Label`:

```js
removeIcon: customPropTypes.every([
  customPropTypes.demand(['onRemove']),
  customPropTypes.itemShorthand,
]),
```

And seems there is bug with `defaultProps` and `customPropTypes.demand`. Looks that validation for  `removeIcon` is called **always** even it's not passed to component.

```jsx
<Label>
  <Icon name='mail' /> 23
</Label>
```

```
Warning: Failed prop type: `removeIcon` prop in `Label` requires props: `onRemove`.
    in Label (created by LabelExampleBasic)
    in LabelExampleBasic
```

_This_ issue in Label can be solved with:

```diff
- static defaultProps = {
-  removeIcon: 'delete',
-}

+ {onRemove && Icon.create(removeIcon, { onClick: this.handleRemove })}
- {onRemove && Icon.create(removeIcon || 'delete', { onClick: this.handleRemove })}
``` 

However, I don't like this because it will not solve real problem. Any better proposals?

**Comment by jeffcarbs** [comment]
Unfortunately within the props validations you only receive the props object _after_ it's been merged with defaultProps: https://github.com/facebook/react/blob/38c22252f4deb2dd7f10644404ae122f1fd0cb88/docs/docs/typechecking-with-proptypes.md#default-prop-values

> The propTypes typechecking happens after defaultProps are resolved, so typechecking will also apply to the defaultProps.

Two options:
1. Remove the `demand` validation here
2. Implement the idea @layershifter just suggested (`removeIcon || 'delete'`)

I lean option 1 because with option 2 we'd have to take care to respect the rules of shorthand props manually (e.g. `undefined` should defer to the default, `null` or `''` should override the default). If we ever change this logic in the shorthand factory it's unlikely we'll remember to update here.

Also propType validations are helping hints for the developer during development. In this particular circumstance, I think it's an edge-case that you'd be trying to customize the `removeIcon` without providing an `onRemove` callback.

**Comment by jeffcarbs** [comment]
Just submitted a PR to fix this. There was the same issue with `renderLabel` in `Dropdown` which I fixed as well.

In general, I kinda think we should only use `demand` when the component would otherwise be broken or have unexpected behavior. Aside from fixing the React warning, removing the `demand` from the `renderLabel` prop within `Dropdown` enables a use-case I have in my app.

### My use-case

I'm writing a component that wraps `Dropdown` and adds default rendering for a particular API-resource type. I want to define a `renderLabel` in that component so if the component is used with `multiple` it will render as I want:

``` js
// ItemDropdown.js
const itemToOptions = (item) => ({ text: item.name, value: item.id })

const renderLabel = (item) => ({
  basic: true,
  color: 'blue',
  content: item.text
})

const ItemDropdown = ({ items, ...props }) => (
  <Dropdown options={items.map} renderLabel={renderLabel} {...props} />
)

// Somewhere else in the app

// Single-select
<ItemDropdown items={items} />

// Multi-select
<ItemDropdown multiple items={items} />
```

If we were to `demand` that multiple were passed, I'd have to check within `ItemDropdown` and optionally pass `renderLabel`. In this case, passing `renderLabel` is harmless and is just ignored.
