### ISSUE TITLE
button in Form.Group size not honored

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI-React#834]
a Button inside of Form.Group does not render consistently

### Steps

![form-group-button mov](https://cloud.githubusercontent.com/assets/1003261/20201482/350dcb4a-a76d-11e6-884c-309dab7c8bdc.gif)

```jsx
  <Form>
    <Form.Group>
      <Form.Input label='field-1' value='best value' />
      <Form.Input label='field-2' value='greatest value' />
      <Button size='small' primary>will this work</Button> {/* <== renders HUGE */}
    </Form.Group>
    ...
  </Form>
```

```jsx
  <Form>
    <Form.Group>
      <Form.Input label='field-1' value='best value' />
      <Form.Input label='field-2' value='greatest value' />
    </Form.Group>
    <Button size='small' primary>will this work</Button> {/* <== renders ok */}
    ...
  </Form>
```

### Expected Result

- consistent rendering of button

### Actual Result

- inconsistent rendering of button

### Version

0.59.x

### Testcase
http://codepen.io/cdaringe/pen/jVWaWg

**Comment by levithomason** [comment]
This would be a css issue, so it would need to be opened over at Semantic-UI.  Semantic-UI-React only concerns itself with JavaScript components that render valid Semantic-UI HTML.

Though, it looks like you just need to wrap it in a FormField.  A FormGroup should only contain FormFields.  The FormInput is shorthand for an Input wrapped in a FormField, so that is valid.  You can also use a FormButton, which is shorthand for a Button wrapped in a FormField.  When I do this, the button is correctly sized.  I think this makes sense, since the FormGroup is expecting all immediate children to be FormFields.

http://codepen.io/levithomason/pen/qqbxoN

![image](https://cloud.githubusercontent.com/assets/5067638/20205563/bf93bf60-a78e-11e6-8838-0cc2db44d891.png)

**Comment by cdaringe** [comment]
cool! thanks again!
