### ISSUE TITLE
Dropdown: Customize selected label for single-select

### ISSUE THREAD

**Issue by jeffcarbs** [Semantic-Org/Semantic-UI-React#852]
### Background
For the `Dropdown` component in SUI-core, dropdown options can have both `text` and `name` properties to distinguish b/w how the option should look within the dropdown menu and how it should look as the selected item (see a more in depth description here: https://github.com/Semantic-Org/Semantic-UI-React/pull/682#discussion_r84160476)

In my app I'm using a node for the `text` prop for each dropdown option to show more complex markup. Here's a rough example: http://codepen.io/jeffcarbs/pen/VmjmYo?editors=0010:
<img width="974" alt="screen shot 2016-11-14 at 1 05 36 pm" src="https://cloud.githubusercontent.com/assets/847027/20276657/2c86fb4e-aa6b-11e6-9ca2-8d827d272a88.png">

For multi-select, you can now specify the `renderLabel` to customize how the selected items should be rendered.

There's no such equivalent to be able to customize how/what the single-select should render the selected item. In that same example, when you select something it renders the same complex node: 
<img width="198" alt="screen shot 2016-11-14 at 1 32 51 pm" src="https://cloud.githubusercontent.com/assets/847027/20277510/e0f879ba-aa6e-11e6-8362-66fceb60f79e.png">

I'd like it to show something else (e.g. just the simple text)

### Question

Should/could we:
- Enable specifying different text/name options (names of those props could change)?
- Use the `renderLabel` for both single/multiple? The third argument to that function is the dropdown props so one could dynamically do something different for single/multiple.
- Add a different `render*` function for that?

Thoughts?

**Comment by levithomason** [comment]
I'm a little concerned about how far we're deviating from SUI core here.  Since custom labels and custom dropdown items are not technically supported by SUI, they are working by chance really.  There is no guarantee that an update shipped to SUI core today won't break this.

That said, we've come this far and the ability to have a correctly rendered single select seems like a must.  I suppose we can always PR any conflicts that may arise in SUI core CSS due to our special usage here.

I think I am leaning toward number 3: "Add a different render\* function for that?", but could you expound a bit on what you mean by number 1?

**Comment by jeffcarbs** [comment]
@levithomason - just put up a PR with option 1, which is explained more clearly in the description of the PR. It's the approach that is supported by SUI-core so this should bring us more in line.

**Comment by levithomason** [comment]
Perfect, will follow up there 👍
