### ISSUE TITLE
Docs site down

### ISSUE THREAD

**Issue by mbeaudru** [Semantic-Org/Semantic-UI-React#863]
I noticed the [webdocs](http://react.semantic-ui.com/) were down , I don't know if opening an issue for signaling this is appropriate but it may help... 😃 

![image](https://cloud.githubusercontent.com/assets/8942633/20324080/742c06f0-ab7f-11e6-9c41-4d4b11ab195f.png)

**Comment by levithomason** [comment]
Thanks, checking...

**Comment by levithomason** [comment]
Fixed in https://github.com/Semantic-Org/Semantic-UI-React/commit/aa8d40935732ec7c13971cc9c7dde06fcb6450fa.  We were caching handled props by `Component._meta.name` but not all components had a `_meta` property.  We now cache on the Component itself, which is what the babel plugin will do once merged, #731.

Appreciate the rapid notice.  Doc site tests are on the bucket list, so we don't ship busted docs.
