### ISSUE TITLE
No loader inside a modal?

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI-React#879]
Not sure if it's a SUI core or SUI react issue...

### Testcase
[codepen.io](http://codepen.io/anon/pen/VmKOOY?editors=0010)

**Comment by levithomason** [comment]
Ah, appears to be a CSS issue.  I would open an issue on SUI core, linking to here.

A Loader in a Modal is a child of a Dimmer (since the Modal has a Dimmer).  So, the Loader is white as the CSS expects it to be displayed directly on the Dimmer (black), not on something white (Modal) inside of the Dimmer.

If you wrap the Loader in an inverted Segment, this is clear:

``` jsx
// ...in a Modal
<Segment basic inverted>
  <Loader active inline='centered' />
</Segment>
```

![image](https://cloud.githubusercontent.com/assets/5067638/20371411/7f8cafa0-ac19-11e6-89fd-ce73613a9b20.png)

# Workarounds

Either removing the Dimmer, or using an inverted (white) Dimmer will allow the Loader to be visible.

## No Dimmer

``` jsx
<Modal dimmer={false} />
```

![image](https://cloud.githubusercontent.com/assets/5067638/20371455/bbdd0946-ac19-11e6-86a3-14a3e4e030ac.png)

## Inverted Dimmer (white)

``` jsx
<Modal dimmer='inverted' />
```

![image](https://cloud.githubusercontent.com/assets/5067638/20371479/ea294ac6-ac19-11e6-99ae-b467ec9cf18e.png)

**Comment by levithomason** [comment]
## Basic Modal

You could also use a `<Modal basic />` which has no background:

![image](https://cloud.githubusercontent.com/assets/5067638/20371549/6abcb36c-ac1a-11e6-82a0-1d6601c3a70d.png)

**Comment by scherroman** [comment]
Another workaround is to surround your loader with an extra inverted dimmer

```
<Dimmer active inverted>
    <Loader active inline='centered'/>
</Dimmer>
```

This will actually dim the entire content of the modal, but it gets the job done
