### ISSUE TITLE
question about SUI-React vs SUI

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI-React#882]
Is there any real difference between using a SUI-React component like Icon vs. just writing out the HTML: `<i className="green checkmark icon"/>` ? 

I understand that for modules I should definitely use the components, but are there any advantages to using components for basic basic views/elements?

Cheers!

**Comment by levithomason** [comment]
What you've noted will work.  Though, I would advise using the components anyway.  I started a more detailed response but don't have time to finish it right now.  I also plan to put the answer to this question in the README and/or docs, since it touches some of the paramount features of SUIR.

I've marked this issue for review so I know to come back to it and give a prpoer response when I am able.  Thanks for raising the question!

**Comment by Maxhodges** [comment]
thanks very curious to hear the answer. I'm pretty much ONLY using the modules-type components, because so far I haven't heard a reason to do otherwise ;)

**Comment by jeffcarbs** [comment]
To me, it's similar to the choice b/w hard-coding a value vs using a variable/constant:
- hardcoding: `<i className="green checkmark icon"/>`
- variable: `<Icon color='green' name='checkmark' />`

Using this library adds a level of abstraction over Semantic UI that protects you against:
- Typos
  - There are propType validations to ensure you're using a valid values for things like color and icon name.
  - Automatically adds the appropriate class (`icon` in this case), which you could accidentally misspell or something.
- Mistakes in usage
  - Sometimes class names are order-dependent (e.g. `Grid` text alignment expects `left aligned`, `aligned left` would not produce the same results). Using `<Grid textAlign='left' />` means that you won't accidentally mess this up.
  - Sometimes you need the `ui` class, sometimes you don't. This library automatically adds it where necessary.
- Underlying SUI changes
  - Imagine SUI were to change the class name associated with `icon` to `glyph` or change the default element type to `span`. In that case, if you hard-coded you'd be stuck going back through your code and updating everything. If you used `Icon`, you would just need to upgrade to the latest version of this package and it would be fixed for you.

I'm also interested to hear Levi's answer, but hope this helps in the meantime.

**Comment by levithomason** [comment]
Agree fully with @jcarbo's points.

I should first clarify that even if you inline HTML, your bundle will still include many element components, like Icons, Labels, and Buttons, because they are imported as dependencies of other components.  For instance, the Dropdown imports the Icon, the Form imports the Button and Input, the Input imports the Label, which Imports the Image, etc.

I'll try to show why I believe the APIs are clearer, more consistent, more DRY, and far more powerful.  I'll organize and boil some of this down for docs later.  Note, I also use "HTML" below to reference "the standard set of DOM components that ship with React" (`div`, `p`, etc), I do not mean literal HTML.

### Shorthand

Most everything that I'll cover below deals with shorthand.  It is pervasive to the entire library and has to be the premier feature.  We've created a factory that allows you to create components from a primitive value (string|number), a props object, or another element.

When a primitive value is used, it is mapped to the most likely prop.  So, you can create an Icon by `name`, an Image by `src`, a Button by its `content`, etc.

When a props object or element is used, the props and classNames are merged.

```jsx
// internal API!
Icon.create('user')            // primitive, mapped to `name`
Icon.create({ name: 'user' })  // props object
Icon.create(<YourIcon />)      // some other element
```

These shorthand `create` factories are what power all shorthand props, making this possible:

```jsx
<Button icon='user' />
<Button icon={{ name: 'user' }} />
<Button icon={<YourIcon />} />
```

Another example, Inputs can have an `action` which is a button.  The `action` prop is then passed to the `Button.create()` shorthand method.  So you can define Input actions in several flexible ways, like so:

```jsx
<Input action='Search' />
<Input action={{ content: 'search', color: 'blue' }} />
<Input action={<YourButton />} />
```

It also means you can create an Input with an action Buton and an Icon, while only importing the Input:
```jsx
import { Input } from 'semantic-ui-react'

<Input icon='search' action='Search' />
```

Hopefully, some of the guiding principles of this library are shown here. We want to work with powerful, high-level, declarative component APIs rather than rebuild components from lower level markup every time we use one.

### Write clearer and more concise code

Using the component APIs, especially with their shorthand, means that you have less code to read and maintain and the payload is a bit smaller as you're leaving the HTML expansion to the component logic. It is also less DRY to write `<button className='ui button' />` every time when you could just write `<Button />`.

```jsx
<Header icon='plug' content='Uptime Guarantee' />

// vs

<div className="ui header">
  <i className="icon plug" />
  <div className="content">
    Uptime Guarantee
  </div>
</div>
```
```jsx
<Message
  success
  icon='thumbs up'
  header='Nice job!'
  content='Your profile is complete.'
/>

// vs

<div className="ui success message">
  <i className="thumbs up icon"></i>
  <div className="content">
    <div className="header">
      Nice job!
    </div>
    Your profile is complete.
  </div>
</div>
```

### Focus on features, not markup intricacies

I think of components as "what properties should this have" not "what shape is the markup again?" Depending on which variations of a component you want to use, the markup can vary wildly.  There are even exceptions to this between components.

The Message above is one example, you don't need to know that the `icon` must go outside of the `content` and the `header` must go inside the `content`, or that the `content` is not even required if there is no `header` nor `icon`... If I want an icon, I just want to write `icon='settings'` and move on.  I can't do that with verbose and inconsistent markup, but I can with a powerful and declarative component API.

### Data Driven UIs

Second to shorthand, this is one of the biggest reasons to use APIs, IMO.  Generating the DOM from data has several advantages, like:
- greater portability, data can go anywhere, components cannot (get menu items or breadcrumbs from an API)
- delegate parent-child coupling to one place, the component logic
- abstracting away HTML intricacies

You can still do this with HTML by looping over data, but you'll be re-inventing the wheel for some use cases that we've already provided props for.

Consider this breadcrumb, notice you don't need to define all the `divider` elements.  The `sections` prop inserts those for you.  Many components have logic that loops data to create markup, if you write the markup yourself, odds are you'll be repeating these utilities.

If you want a `|` divider, just pass `divider='|'`, ir if you want to use a right angle icon divider, pass `icon='right angle'`.

```jsx
import pages from './some-place' // ['Home', 'Registration', 'Personal Information']

<Breadcrumb sections={pages} />

// vs

<div className="ui breadcrumb">
  <a className="section">Home</a>
  <div className="divider">/</div>
  <a className="section">Registration</a>
  <div className="divider">/</div>
  <div className="active section">Personal Information</div>
</div>
```

### Library-Wide Features

Per #837, we'll be adding shorthand for things like `popup`, `transition`, and `dropdown` to _all_ components.  So you can do things like:

```jsx
<Button popup='Snooze for 1 day' content='Later' />

// vs

<Popup
  trigger={<button className="ui button">Later</button>}
  content='Snooze for 1 day'
/>
```

The trend of adding integrated features and optimizations will continue.  If you're not using the component APIs, you're going to miss out on all these features as well.

### My Philosophy

Really, I think this comes down to philosophy alone

I believe simplicity and consistency are king (separate rant), for me that means using all HTML markup, or none.  I regard consistency as essential both for tooling and for developer sanity.

I also see a stark fundamental difference between working with HTML and component APIs.  Humans think like this, "I need a button here."  We don't think, "I need a `div` with the className `ui button` here."  I don't want to "build" a component from a lower level technology every time I need one, I want to "implement" one that is already built.

```jsx
<Button />
// vs
<div className="ui button" />
```

I actually don't want to build "components" at all, I'm trying to build "apps".  Building components is a necessary distraction.  I think this distinction is actually very important to our cognitive load and productivity, especially to newcomers.

This is more obvious in reverse.  When building an application, you _never_ fire up assembly and start bit shifting, why? Because you want to work with the highest level abstraction closest to your end goal, it's why we create and share libraries, it's why we don't write machine code.  As far as I'm concerned, in today's web apps, HTML is machine code.

This is also what I think is so attractive about SUI.   It doesn't feel rigid or like tech jargon, it is natural.  If you want a big red button, you define a `big red button`.  If @jlukic had the power to define the tag name and attribute names when he created SUI, I'm sure he would have, but he didn't.  We do have that power, so we've done exactly that.

**Comment by levithomason** [comment]
Here's a perfect example of why you should use the component APIs. We [just added](https://github.com/Semantic-Org/Semantic-UI-React/issues/890) a11y linting and we'll begin making our components accessible.  Web accessibility is obviously extremely important for real production sites and apps.  If you're using the APIs, you'll begin to get this for free.

If you're using inline markup, adding and maintaining accessibility is up to you alone.  Adding accessibility manually will add a _serious_ amount of tedious and duplicate code to your app.  There are several props that many components will need to be accessible.  I don't think it makes sense to repeat these in every usage of every component.

Also, with the component APIs, you're benefiting from OSS.  We all band together to work on one awesome implementation of accessibility and we all reap the benefits.  Your ROI is massive and [everything is awesome](https://youtu.be/StTqXEQ2l-Y):

- everything is cool when you're part of a team
- everything is awesome, when you're livin a dream
- everything is better when we stick together
- side-by-side, you and I gonna win forever ...let's party forever 🎉

**Comment by levithomason** [comment]
Closing in favor of #561 where the shorthand docs will be added including much of the information from this issue.
