### ISSUE TITLE
Modal 'onOpen' and 'onClose' not firing when they should

### ISSUE THREAD

**Issue by AlvMF1** [Semantic-Org/Semantic-UI-React#901]
Looks like `onOpen` and `onClose` are fired when `open` changes (and when mounted?).

### Testcase
[codepen.io](http://codepen.io/anon/pen/XNpdbR?editors=0011)
Check `console`.

**Comment by levithomason** [comment]
Thanks for the codepen!  Actually, the console functions are called on every render because they are not wrapped in a function:
```jsx
onOpen={console.warn('onOpen')} 
// vs
onOpen={() => console.warn('onOpen')} 
```

The first example is assigning the return value of `console.warn()` to the `onOpen` handler, which returns `undefined`, so it is the same as having no `onOpen`/`onClose` handlers at all.

The second example gives a function, that when called, logs the messages.  Seems to be working correct with the fix.  Here's a fork:

http://codepen.io/levithomason/pen/aBJvZR

**Comment by AlvMF1** [comment]
Got it. But doing that, I don't see `console` messages in your fork when opening or closing...

**Comment by levithomason** [comment]
There might be a design flaw here.  It looks like successful auto controlled open/close events do not call the handlers, which they should.  Whereas, unsuccessful auto open/close events do call the handlers.

Example, clicking the button successfully opens the Modal, so no `onOpen` is called.  Clicking the "close" button successfully closes the Modal, so no `onClose` is called.  However, I see `onClose` when I press escape or click on the dimmer which is _trying_ to close the Modal but is unsuccessful.

I've reopened and renamed this issue to investigate this.

**Comment by Arthelon** [comment]
It seems to be an issue with delegation to the Portal component. Some of the handlers aren't being registered if the "trigger" Portal prop isn't passed to the Modal.

**Comment by luski** [comment]
As far as I understood the current code, modals can be closed only when the trigger prop is passed or the onClose prop is a function setting the "open" state to false. When the user clicks outside the modal or presses ESC the this.close() inner method of the Portal component is called and within it:
 `this.prop.onClose()` is called and
`this.trySetState({ open: false }) (Portal.js:334) `
is called.
The problem is the "trySetState" doesn't do anything. It tries to generate a new state, but always generates just an empty object. I don't understand what this function is supposed to do and why don't use just
`this.setState({ open: false })`
which solves this part of the issue?

The `onClose` and `onOpen` callbacks are not called when the user clicks the trigger because they are called in `this.open` and `this.close` inner methods and these methods are not called in some cases.
I think it would be better to call `this.open`/`this.close` (or at least `onOpen`/`onClose` callbacks) only in the `componentDidUpdate` method when the "open" state is changed. It assures the `open`/`close` methods are called always when the "open" state is really changed and not when the user only tries to change this state.

But I don't know the code and concepts good enough so treat it more like questions than suggestions :smile:

**Comment by micahbule** [comment]
I'm currently having a problem with this one since we're heavily relying on proper callback functionalities for firing certain events in our app.

According to my analysis of the internal code, everything is fine when events are propagated from the `trigger` prop, as well as anything within the `Modal`'s scope (`Portal` scope if we dive deeper) in a sense that the node who fired the event is either passed as a `trigger` prop or a child component of the underlying `Portal` component, as well as the dimmer.

The problem exists when the trigger node (in most cases a button) lies outside the scope, meaning the `Modal` nor the `Portal` component doesn't have an idea which node caused the change, it just know that the value of the `open` prop changed.

A quick clarification to @levithomason: Since you're mounting/unmounting the modal node when we open/close the modal (respectively), what's the ideal sequence of callbacks firing?

**Comment by micahbule** [comment]
I've found a much graceful "hack" for now until a better solution comes up.

Instead of controlling the `Modal` component's `open` prop and setting it to `true` or `false` to show or hide the modal, you can basically get a reference of the `Modal` component and manually trigger the open/close handlers via `handleOpen()`/`handleClose()` methods, respectively.

The advantages of this hack:
1. By leaving the control of the `open` prop to the component (via AutoControl), you're sure that the underlying mechanisms (ex. underlying `Portal` component) would still work as is.
2. Using this approach, you can now bind the visibility handlers to triggers outside the scope of the `Modal` component. Refer to my fork of your Codepen [here](http://codepen.io/anon/pen/pejBLR?editors=0011). You can even manually trigger the handlers on other events such as a props or state changes (ex. a Redux or Flux state tree change).

The only caveat of this hack is that whenever you trigger the handlers from events that does not provide React's SyntheticEvent, your `onOpen()`'s and `onClose()`'s first argument would either be undefined or anything that you pass as the first argument of your `handleOpen()` and `handleClose` calls.

**Comment by levithomason** [comment]
Heads up, I'd highly recommend not using the `ref` hack.  Those methods are not advertised and are subject to change at any time. They are usually meant to be used in very specific ways.  Only the public API is tested, so using internal methods can be dangerous territory.

After reconsidering this, I don't think there is a bug here actually.  The current behavior is inline with vanilla HTML events as well as vanilla React component events.

### Works like a regular controlled component

Consider a controlled input.  The `value` is derived from state while the `onChange` sets state when the user tries to change value:
```jsx
handleChange = e => this.setState({ value: e.target.value })

render() {
  return <input value={this.state.value} onChange={this.handleChange} />
}
```

The `onChange` handler **is not called** when the `value` is changed programmatically.  Otherwise, it would enter an infinite loop: onChange -> setState -> value update -> onChange > ...

Instead, the `onChange` handler **is only called** when the user attempts to change the `value`.  This way, the attempted new value is passed to the handler and the handler can do with it what it may.

### Calling them again is not necessary

There is one other good reason, there is no need to call Modal `onOpen` when the `open` prop changes, since, the method that changed the state can do the same work.  When changing the `open` state, simply set state first, then perform the work that would have been done in the `onOpen` callback.

***

### Wrong proposed `open` value

It is an issue that the `open` value in the `onOpen` and `onClose` is the current value, rather than the proposed new value.  This issue can be tracked in #1280.

**Comment by micahbule** [comment]
Oh, my bad. Yeah, I got your point and your suggestion worked. Thanks for that.

**Comment by crispamares** [comment]
I can see a situation where the proposed design does not fit. You said:

> There is one other good reason, there is no need to call Modal onOpen when the open prop changes, since, the method that changed the state can do the same work. When changing the open state, simply set state first, then perform the work that would have been done in the onOpen callback.

But consider a component that is a wrapper of a controlled Modal. The Modal contains an Input inside. I want to focus the Input `onOpen`, with the current design I need to focus the input in the method that performs the state (`open`) change, which obviously has no reference to the Input.

Am I obliged to implement `componentDidUpdate` in the Modal wrapper to call `onOpen` manually? 

Very good work with the library BTW :)

**Comment by levithomason** [comment]
Use the `setState` callback to call focus on the `ref`:

https://codepen.io/levithomason/pen/vZMeKN

```jsx
class App extends React.Component {
  state = { open: false }
  handleRef = component => (this.ref = component)
  open = () => this.setState({ open: true }, () => this.ref.focus())
  close = () => this.setState({ open: false })

  render() {
    return (
      <div>
        <Button primary content='Open' onClick={this.open} />
        <Modal open={this.state.open} onClose={this.close}>
          <Modal.Content>
            <Input ref={this.handleRef} />
          </Modal.Content>
        </Modal>
      </div>
    )
  }
}
```
