### ISSUE TITLE
Do Inline Fields Work?

### ISSUE THREAD

**Issue by eanplatter** [Semantic-Org/Semantic-UI-React#92]
I wanted to do something like this:
<img width="505" alt="screen shot 2015-10-26 at 5 48 29 pm" src="https://cloud.githubusercontent.com/assets/3782604/10744694/e2e5de8c-7c09-11e5-8e8f-591efe4d6190.png">

With syntax like this:

``` jsx
<Field
  width={8}
  label='Name'
  className='inline'
>
<Input
  placeholder='First Name'
  onChange={this.handleChange}
  value={this.state.user.firstName}
/>
```

but I got this:
<img width="402" alt="screen shot 2015-10-26 at 5 52 20 pm" src="https://cloud.githubusercontent.com/assets/3782604/10744772/5681d59e-7c0a-11e5-81b9-3add6612e270.png">

Is my syntax off or is this a real issue?

**Comment by levithomason** [comment]
Per our debugging, the issue here is the input component.  It uses the div wrapped markup.  This extra div breaks the field layout when the `<Input />` is put in a `<Field />`.

I'll add an issue for the input to dynamically add the wrapper div _only_ if there are input labels, actions, or an icon.  In the case of a plain input, the div is not required.

It will then work with the input as there will be no wrapper div.

**Comment by levithomason** [comment]
Turns out we already had a preemptive issue for this.  I'm going to close this issue an keep churn on #38.
