### ISSUE TITLE
Statistic size Prop doesn't work inside Statistic.Group

### ISSUE THREAD

**Issue by L3V147H4N** [Semantic-Org/Semantic-UI-React#970]
```jsx
<Statistic.Group widths="4">
  <Statistic size="mini" color="black" value={value} label="label" />
  <Statistic size="mini" color="red" value={value} label="label" />
  <Statistic size="mini" color="orange" value={value} label="label" />
  <Statistic size="mini" color="green" value={value} label="label" />
</Statistic.Group>

This should display 4 mini-sized statistics "in a row" but they are always regular size
Is there other way to specify the size?

**Comment by jeffcarbs** [comment]
Looks like there's a more specific rule on `Statistic.Group (.ui.statistics)` that's overriding the font-size:
<img width="862" alt="screen shot 2016-12-01 at 9 53 54 am" src="https://cloud.githubusercontent.com/assets/847027/20798251/3ce83716-b7ac-11e6-9201-e1d0e9b863c9.png">

Semantic-UI-React only concerns itself with React components that generate valid Semantic-UI markup. There is no HTML nor CSS code in this project. This may be an issue you can raise in the core Semantic-UI repo.

However, since in your case all of the statistics are the same size you can defined `size='mini'` on the `StatisticGroup` instead. **NOTE** This won't work in the current version because the `size` prop isn't yet handled on the group. I just opened a PR to add it (#972):
<img width="758" alt="screen shot 2016-12-01 at 10 07 45 am" src="https://cloud.githubusercontent.com/assets/847027/20798758/09ec0c6e-b7ae-11e6-9de5-a7c9f2bcac41.png">

**Comment by schnubor** [comment]
Hi @jcarbo 

Thanks for the PR! I'm running on 0.62.0 now but the `size` prop still isn't working for me. I use it like this:

```html
<Statistic.Group items={stats} widths={stats.length} size="small" />
```

The "size" class (in this case `small`) isn't applied at all:

![image](https://cloud.githubusercontent.com/assets/5865010/20979338/d133c28c-bcac-11e6-93bc-c30a1ecf0a9e.png)

I also tried adding the `size` prop to my `stats` array, but still get the same result since the class is applied to the individual stats, but overwritten by the parent as already mentioned in this issue.

```js
const stats = [
            {
                label : 'Failing',
                value : failedTestCount,
                color : 'grey',
                size  : 'small'
            },
            {
                label : statusText,
                value : percentage,
                color : statusColor,
                size  : 'small'
            },
            {
                label : 'Passing',
                value : passedTestCount,
                color : 'green',
                size  : 'small'
            }
]
```

Everything else except the size seems to be working.

Any ideas?

Cheers,
Christian

**Comment by levithomason** [comment]
@schnubor this has got to be something with the project.  The docs, codepen, and tests show this is working.  Here is an example:

http://codepen.io/levithomason/pen/dOKYXw

Not sure what could be going on in the project.

**Comment by schnubor** [comment]
Thanks @levithomason !
