### ISSUE TITLE
Consider Adding "container" prop to Grid.js

### ISSUE THREAD

**Issue by cpheimbach** [Semantic-Org/Semantic-UI-React#983]
The Container element in Semantic UI allows to be combined with the Grid collection. This ensures that the grid content "use all of the layout and alignment available for grids including responsive patterns" as described in more detail here: http://semantic-ui.com/elements/container.html#/examples

**Comment by levithomason** [comment]
Thanks for the issue.  I think we should do this.

**Comment by tarang9211** [comment]
@levithomason im excited to pick this one up! could you brief me up with the info?

**Comment by cpheimbach** [comment]
Hey @tarang9211, thank you for looking into this. I figured that the only way to enable a grid component to also behave like a container is via adding it as a CSS class
```<Grid className='container' />```. I think with levithomason we thought this is better solved by adding a boolean props which activates the behaviour. So ```<Grid container />``` would achieve the above.

Let me know if that makes things clear.

**Comment by tarang9211** [comment]
@cpheimbach yes, that makes sense! Could you give me some more info on where to start and what to start digging through?

**Comment by levithomason** [comment]
@tarang9211 There are several boolean props (i.e. `centered`) already present in the Grid, you can duplicate that code and just update it for `container`.

Please have a look at our [CONTRIBUTING.md](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md) for more info.  It is a step-by-step guide to developing in our stack and writing components, so you'll want to read it starting at the top and going to the bottom.  Since you've already contributed, you can skip much of the setup.

Each section is very brief and includes code examples.  There are sections for [API](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md#api), [Testing](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md#testing), and [Documentation](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/.github/CONTRIBUTING.md#documentation).  They will guide you through how and where to add the prop, the test, and the docs for it.

Cheers!

**Comment by tarang9211** [comment]
this might be a noob question, but when I add a `prop` to a component, where does it pick up the class name from? does it get the class name from the semantic ui css stylesheet somehow? im just trying to figure out the flow of things.

**Comment by tarang9211** [comment]
@levithomason I'm receiving some phantom js errors when I run the command `npm test` as screen in the screen shot below. Any idea what this could be? I don't think the tests are running because of this.

<img width="947" alt="screen shot 2016-12-23 at 6 37 38 pm" src="https://cloud.githubusercontent.com/assets/5876249/21454497/1952e928-c93f-11e6-99f0-3a40666d146a.png">

**Comment by tarang9211** [comment]
@levithomason Here's the PR for this issue! https://github.com/Semantic-Org/Semantic-UI-React/pull/1085

**Comment by tarang9211** [comment]
This issue can be closed right?

**Comment by levithomason** [comment]
Thanks much!
