### ISSUE TITLE
fix(Form): Form doesn't serialize array form fields

### ISSUE THREAD

**Issue by vcanales** [Semantic-Org/Semantic-UI-React#998]
**Steps to Reproduce**
1. Build a form with array name fields (data[one], data[two])
```
<Form.Input name="data[one]"></Form.Input>
<Form.Input name="data[two]"></Form.Input>
```

**Expected**
Form should serialize those fields into a single object
```
formData: {
  data: {
    one: 'value',
    two: 'value'
  }
}
```

**Result**
Form does this: 

```
formData : {
  data[one]: 'value',
  data[two]: 'value'
}
```

**Testcase**
http://codepen.io/anon/pen/VmxEKQ (see output in console)

**Comment by levithomason** [comment]
The current form serializer is DOM based and will likely be replaced once we implement form validation, #407.  I'm hesitant to extend it as the current paradigm is not "the React way" and the future implementation will not be based no HTML names.

**Comment by vcanales** [comment]
@levithomason I understand. Any idea on how the case displayed here will be handled in the future then?

**Comment by levithomason** [comment]
All form serialization and validation will be accomplished using the [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components) pattern where the value of each form control is captured and placed in state somewhere, probably a higher order form component.  You can refer to [react-reformed](https://github.com/davezuko/react-reformed) for some ideas.

We'll likely bake something like this into SUIR and attempt to simplify the API and usage a bit to reduce the workload of wiring this up.

So, in that case, instead of using the `name` attribute in the DOM to find values and serialize them, your virtual DOM change handlers will be placing the value in the correct place in the form's state model.  This is preferred since the data is then handled inside of React, instead of the browser's real DOM.  Aside from the fact that using the real DOM is an antipattern, using React's virtual DOM makes testing a breeze, keeps the app fast, and is better for integrating other tools like validation and local storage.

You might also find some of these other react form libraries helpful:
https://github.com/erikras/redux-form/
https://github.com/christianalfoni/formsy-react
https://github.com/prometheusresearch/react-forms

Cheers!

**Comment by vcanales** [comment]
Thanks, this gave me an albeit obvious idea of how to fix my particular issue.

**Comment by levithomason** [comment]
Glad to hear it :)
